"""Canonical MMA technique definitions used beneath broad fight actions."""

from dataclasses import dataclass

from constants import DETAILED_SKILL_GROUPS, STYLES


ALL_POSITIONS = frozenset({
    "range", "pocket", "clinch", "cage", "failed shot", "standing back control",
    "guard", "half guard", "side control", "mount", "back control", "turtle",
    "front headlock", "leg entanglement",
})
STANDING_POSITIONS = frozenset({"range", "pocket"})
CLINCH_POSITIONS = frozenset({"clinch", "cage", "standing back control"})
GROUND_POSITIONS = frozenset({
    "guard", "half guard", "side control", "mount", "back control", "turtle",
    "front headlock", "leg entanglement",
})


@dataclass(frozen=True)
class MoveDefinition:
    move_id: str
    name: str
    parent_action: str
    positions: frozenset
    targets: frozenset = frozenset()
    attack_skills: tuple = ()
    defense_skills: tuple = ()
    preferred_styles: tuple = ()
    minimum_skill: int = 0
    energy: float = 1.0
    miss_risk: float = 1.0
    counter_risk: float = 1.0
    follow_ups: tuple = ()
    tags: tuple = ()
    side: str = ""
    range_band: str = ""
    defense_families: tuple = ()
    entry_family: str = ""
    finish_positions: tuple = ()
    attack_path: str = ""
    failure_outcomes: tuple = ()
    components: tuple = ()


@dataclass(frozen=True)
class DefenseDefinition:
    defense_id: str
    name: str
    families: tuple
    positions: frozenset
    skills: tuple
    tags: tuple = ()


def defense(defense_id, name, families, positions, skills, tags=()):
    return DefenseDefinition(defense_id, name, tuple(families), frozenset(positions), tuple(skills), tuple(tags))


DEFENSE_DEFINITIONS = (
    defense("high_guard", "high guard", ("block", "shell", "slip-block"), STANDING_POSITIONS, ("guard_defence", "composure"), ("strike", "block")),
    defense("outside_parry", "outside parry", ("parry", "parry-check"), STANDING_POSITIONS, ("guard_defence", "reflexes"), ("strike", "parry")),
    defense("slip_exit", "slip and angle exit", ("evade", "sidestep", "pullback"), STANDING_POSITIONS, ("head_movement", "footwork"), ("strike", "evasion")),
    defense("shin_check", "shin check", ("check", "block-check"), STANDING_POSITIONS, ("kick_defence", "mobility"), ("kick", "check")),
    defense("kick_catch", "kick catch", ("catch",), STANDING_POSITIONS, ("reflexes", "takedown_defence_detail"), ("kick", "catch")),
    defense("knee_jam", "knee-and-elbow jam", ("jam",), STANDING_POSITIONS | CLINCH_POSITIONS, ("clinch_defence", "reflexes"), ("clinch", "frame")),
    defense("hip_sprawl", "hips-heavy sprawl", ("sprawl",), ALL_POSITIONS, ("sprawl", "takedown_defence_detail"), ("wrestling", "sprawl")),
    defense("whizzer_balance", "whizzer and balance", ("whizzer", "balance", "wide base", "base"), ALL_POSITIONS, ("clinch_defence", "strength"), ("wrestling", "whizzer")),
    defense("fence_post", "fence post and hip frame", ("fence post", "hip pressure"), CLINCH_POSITIONS | frozenset({"failed shot"}), ("cage_wrestling", "strength"), ("cage", "frame")),
    defense("underhook_turn", "underhook hip turn", ("underhook", "hip turn", "hip block"), CLINCH_POSITIONS, ("clinch_defence", "cage_wrestling"), ("clinch", "underhook")),
    defense("limp_leg", "limp-leg withdrawal", ("limp leg", "hop"), ALL_POSITIONS, ("scrambles", "mobility"), ("wrestling", "escape")),
    defense("hand_fight_escape", "two-on-one hand fight", ("hand fight",), CLINCH_POSITIONS | GROUND_POSITIONS, ("get_ups", "scrambles"), ("control", "escape")),
    defense("guard_frame", "guard frame and hip escape", ("frame", "guard frame"), GROUND_POSITIONS, ("guard_work", "bottom_control"), ("ground", "frame")),
    defense("submission_hand_fight", "submission hand fighting", ("submission defense",), GROUND_POSITIONS, ("submission_defence_detail", "composure"), ("submission", "grip-defense")),
    defense("stack_escape", "stack-and-turn escape", ("stack",), GROUND_POSITIONS, ("submission_defence_detail", "strength"), ("submission", "escape")),
    defense("knee_line_escape", "knee-line escape", ("leg escape",), frozenset({"guard", "half guard", "leg entanglement"}), ("submission_defence_detail", "mobility"), ("leg-lock", "escape")),
    defense("wall_walk", "wall-walk escape", ("wall walk", "cage escape"), CLINCH_POSITIONS | GROUND_POSITIONS, ("get_ups", "cage_wrestling"), ("cage", "escape")),
    defense("technical_scramble", "technical scramble", ("scramble", "back step", "back take"), ALL_POSITIONS, ("scrambles", "transitions"), ("scramble", "escape")),
)
DEFENSE_REGISTRY = {definition.defense_id: definition for definition in DEFENSE_DEFINITIONS}


def validate_defense_registry():
    issues = []
    known_skills = {key for group in DETAILED_SKILL_GROUPS.values() for key in group}
    if len(DEFENSE_REGISTRY) != len(DEFENSE_DEFINITIONS):
        issues.append("Defense IDs must be unique")
    for definition in DEFENSE_DEFINITIONS:
        if not definition.families:
            issues.append(f"{definition.defense_id}: requires a defense family")
        if not definition.positions or not definition.positions <= ALL_POSITIONS:
            issues.append(f"{definition.defense_id}: contains an unknown position")
        unknown = set(definition.skills) - known_skills
        if unknown:
            issues.append(f"{definition.defense_id}: unknown skills {', '.join(sorted(unknown))}")
    return issues


DEFENSE_REGISTRY_ERRORS = tuple(validate_defense_registry())
if DEFENSE_REGISTRY_ERRORS:
    raise ValueError("Invalid MMA defense registry: " + "; ".join(DEFENSE_REGISTRY_ERRORS))


def legal_defenses(families, position):
    families = set(families or ())
    return tuple(definition for definition in DEFENSE_DEFINITIONS
                 if position in definition.positions and families.intersection(definition.families))


def move(move_id, name, action, positions, **kwargs):
    return MoveDefinition(move_id, name, action, frozenset(positions), **kwargs)


MOVE_DEFINITIONS = (
    move("single_jab", "single jab", "jab", STANDING_POSITIONS,
         attack_skills=("punch_technique", "hand_speed"), defense_skills=("head_movement", "guard_defence"),
         preferred_styles=("Boxer", "Kickboxer"), follow_ups=("one_two", "jab_to_shot"), tags=("strike", "punch", "setup")),
    move("double_jab", "double jab", "jab", STANDING_POSITIONS,
         attack_skills=("punch_technique", "combination_punching", "conditioning"), defense_skills=("head_movement", "footwork"),
         preferred_styles=("Boxer", "MMA Generalist"), energy=1.08, follow_ups=("one_two", "double_jab_cross"), tags=("strike", "combination")),
    move("body_jab", "jab to the body", "jab", STANDING_POSITIONS, targets=frozenset({"body"}),
         attack_skills=("body_punching", "punch_technique", "feints"), defense_skills=("guard_defence", "reflexes"),
         preferred_styles=("Boxer",), counter_risk=1.08, tags=("strike", "punch", "body")),
    move("one_two", "one-two", "power_punch", STANDING_POSITIONS,
         attack_skills=("combination_punching", "punch_technique", "hand_speed"), defense_skills=("guard_defence", "head_movement"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), energy=1.08, follow_ups=("lead_hook_cross",), tags=("strike", "combination")),
    move("lead_hook_cross", "lead hook to rear cross", "power_punch", STANDING_POSITIONS,
         attack_skills=("combination_punching", "creative_punches", "punch_power"), defense_skills=("head_movement", "reflexes"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), minimum_skill=55, energy=1.16, counter_risk=1.12,
         tags=("strike", "combination", "power")),
    move("double_jab_cross", "double jab to rear cross", "power_punch", STANDING_POSITIONS,
         attack_skills=("combination_punching", "hand_speed", "punch_technique"), defense_skills=("guard_defence", "footwork"),
         preferred_styles=("Boxer", "Kickboxer"), minimum_skill=54, energy=1.2, counter_risk=1.14,
         tags=("strike", "combination")),
    move("cross_hook_cross", "cross-hook-cross", "power_punch", STANDING_POSITIONS,
         attack_skills=("combination_punching", "punch_power", "creative_punches"), defense_skills=("head_movement", "guard_defence"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), minimum_skill=58, energy=1.24, counter_risk=1.18,
         tags=("strike", "combination", "power")),
    move("body_head_change", "shovel hook to cross", "power_punch", STANDING_POSITIONS,
         attack_skills=("body_punching", "combination_punching", "punch_power"), defense_skills=("guard_defence", "head_movement"),
         preferred_styles=("Boxer", "Kickboxer"), minimum_skill=55, energy=1.16, counter_risk=1.12,
         tags=("strike", "combination", "body-head")),
    move("jab_cross_lead_hook", "jab-cross-lead hook", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("combination_punching", "punch_technique", "hand_speed"),
         defense_skills=("guard_defence", "head_movement"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), minimum_skill=56, energy=1.2, counter_risk=1.14,
         follow_ups=("rear_uppercut",), tags=("strike", "combination", "power", "head")),
    move("jab_uppercut_lead_hook", "jab-rear uppercut-lead hook", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("combination_punching", "creative_punches", "punch_power"),
         defense_skills=("head_movement", "guard_defence"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), minimum_skill=60, energy=1.24, counter_risk=1.18,
         tags=("strike", "combination", "power", "head")),
    move("double_jab_body_cross", "double body jab to cross upstairs", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("combination_punching", "body_punching", "punch_technique"),
         defense_skills=("guard_defence", "footwork"),
         preferred_styles=("Boxer", "MMA Generalist"), minimum_skill=56, energy=1.2, counter_risk=1.12,
         tags=("strike", "combination", "body-head", "head")),
    move("cross_body_hook_lead_hook", "cross-body hook-lead hook", "power_punch", STANDING_POSITIONS,
         attack_skills=("combination_punching", "body_punching", "creative_punches"),
         defense_skills=("guard_defence", "head_movement"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), minimum_skill=59, energy=1.24, counter_risk=1.18,
         tags=("strike", "combination", "body-head", "power")),
    move("stance_shift_cross_hook", "stance-shift cross to lead hook", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("combination_punching", "footwork", "punch_technique"),
         defense_skills=("head_movement", "reflexes"),
         preferred_styles=("Karate", "Boxer", "MMA Generalist"), minimum_skill=62, energy=1.2,
         counter_risk=1.16, tags=("strike", "combination", "stance-shift", "head")),
    move("boxing_pressure_flurry", "jab-cross-hook pressure flurry", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("combination_punching", "hand_speed", "conditioning"),
         defense_skills=("guard_defence", "composure"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), minimum_skill=68, energy=1.36, miss_risk=1.12,
         counter_risk=1.3, tags=("strike", "combination", "pressure", "head")),
    move("rear_uppercut", "rear uppercut", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("punch_power", "creative_punches", "hand_speed"),
         defense_skills=("head_movement", "guard_defence"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), minimum_skill=62, energy=1.18, miss_risk=1.08,
         counter_risk=1.16, tags=("strike", "punch", "power", "head", "finisher")),
    move("corkscrew_cross", "corkscrew cross", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("punch_power", "punch_technique", "counter_timing"),
         defense_skills=("guard_defence", "head_movement"),
         preferred_styles=("Boxer", "Karate"), minimum_skill=61, energy=1.16, miss_risk=1.06,
         counter_risk=1.14, tags=("strike", "punch", "power", "head", "finisher")),
    move("spinning_backfist", "spinning backfist", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("creative_punches", "hand_speed", "mobility"),
         defense_skills=("reflexes", "head_movement"),
         preferred_styles=("Karate", "Sanda", "MMA Generalist"), minimum_skill=66, energy=1.28,
         miss_risk=1.26, counter_risk=1.34,
         tags=("strike", "punch", "power", "spinning", "head", "finisher")),
    move("check_hook", "check hook", "power_punch", STANDING_POSITIONS,
         attack_skills=("counter_timing", "footwork", "punch_technique"), defense_skills=("head_movement", "guard_defence"),
         preferred_styles=("Boxer", "Karate"), minimum_skill=56, counter_risk=0.82,
         tags=("strike", "punch", "counter")),
    move("pull_counter", "pull counter", "power_punch", STANDING_POSITIONS,
         attack_skills=("counter_timing", "head_movement", "punch_power"), defense_skills=("reflexes", "guard_defence"),
         preferred_styles=("Boxer", "Kickboxer"), minimum_skill=58, energy=1.05, miss_risk=1.08, counter_risk=0.84,
         tags=("strike", "punch", "counter")),
    move("slip_cross", "slip and rear cross", "power_punch", STANDING_POSITIONS,
         attack_skills=("counter_timing", "head_movement", "hand_speed"), defense_skills=("reflexes", "guard_defence"),
         preferred_styles=("Boxer", "MMA Generalist"), minimum_skill=55, counter_risk=0.8,
         tags=("strike", "punch", "counter")),
    move("overhand", "rear overhand", "power_punch", STANDING_POSITIONS,
         attack_skills=("punch_power", "feints"), defense_skills=("head_movement", "footwork"),
         preferred_styles=("Wrestler", "Sambo", "Boxer"), energy=1.14, miss_risk=1.12, counter_risk=1.14,
         follow_ups=("double_leg_entry",), tags=("strike", "power", "level-change")),
    move("inside_low_kick", "inside low kick", "kick", STANDING_POSITIONS, targets=frozenset({"leg"}),
         attack_skills=("low_kick_technique", "low_kick_speed"), defense_skills=("kick_defence", "reflexes"),
         preferred_styles=("Muay Thai", "Kickboxer", "Sanda"), tags=("strike", "kick", "leg"),
         side="lead", range_band="kicking", defense_families=("check", "pullback", "catch")),
    move("outside_low_kick", "outside low kick", "kick", STANDING_POSITIONS, targets=frozenset({"leg"}),
         attack_skills=("low_kick_power", "low_kick_technique"), defense_skills=("kick_defence", "mobility"),
         preferred_styles=("Muay Thai", "Dutch Kickboxer"), energy=1.08, tags=("strike", "kick", "leg"),
         side="rear", range_band="kicking", defense_families=("check", "pullback", "catch")),
    move("body_round_kick", "round kick to the body", "kick", STANDING_POSITIONS, targets=frozenset({"body"}),
         attack_skills=("high_kick_technique", "low_kick_power", "flexibility"), defense_skills=("kick_defence", "guard_defence"),
         preferred_styles=("Kickboxer", "Muay Thai", "Sanda"), energy=1.1, tags=("strike", "kick", "body"),
         side="rear", range_band="kicking", defense_families=("block", "catch", "evade")),
    move("head_round_kick", "round kick to the head", "kick", STANDING_POSITIONS, targets=frozenset({"head"}),
         attack_skills=("high_kick_power", "high_kick_technique", "high_kick_speed"), defense_skills=("kick_defence", "head_movement"),
         preferred_styles=("Kickboxer", "Taekwondo", "Karate"), minimum_skill=58, energy=1.22,
         miss_risk=1.16, counter_risk=1.18, tags=("strike", "kick", "head", "power"),
         side="rear", range_band="kicking", defense_families=("block", "evade", "catch")),
    move("calf_kick", "rear calf kick", "kick", STANDING_POSITIONS, targets=frozenset({"leg"}),
         attack_skills=("low_kick_technique", "low_kick_speed", "creative_kicks"), defense_skills=("kick_defence", "mobility"),
         preferred_styles=("Kickboxer", "Muay Thai", "MMA Generalist"), minimum_skill=52, energy=1.06,
         tags=("strike", "kick", "leg"), side="rear", range_band="kicking",
         defense_families=("check", "pullback", "stance switch")),
    move("low_kick_counter", "check-return low kick", "kick", STANDING_POSITIONS, targets=frozenset({"leg"}),
         attack_skills=("counter_timing", "low_kick_speed", "low_kick_technique"), defense_skills=("kick_defence", "reflexes"),
         preferred_styles=("Muay Thai", "Dutch Kickboxer"), minimum_skill=57, counter_risk=0.82,
         tags=("strike", "kick", "leg", "counter"), side="rear", range_band="kicking",
         defense_families=("check", "pullback")),
    move("lead_teep", "lead teep", "kick", STANDING_POSITIONS, targets=frozenset({"body"}),
         attack_skills=("creative_kicks", "low_kick_technique", "footwork"), defense_skills=("kick_defence", "reflexes"),
         preferred_styles=("Muay Thai", "Sanda"), tags=("strike", "kick", "body", "intercept"),
         side="lead", range_band="long", defense_families=("parry", "catch", "sidestep")),
    move("side_kick", "lead side kick", "kick", STANDING_POSITIONS, targets=frozenset({"body"}),
         attack_skills=("creative_kicks", "high_kick_technique", "mobility"), defense_skills=("kick_defence", "footwork"),
         preferred_styles=("Karate", "Taekwondo", "Sanda"), minimum_skill=54, energy=1.08,
         tags=("strike", "kick", "body"), side="lead", range_band="long",
         defense_families=("sidestep", "catch", "pullback")),
    move("question_mark_kick", "question-mark kick", "kick", STANDING_POSITIONS, targets=frozenset({"head"}),
         attack_skills=("creative_kicks", "high_kick_technique", "feints"), defense_skills=("kick_defence", "head_movement"),
         preferred_styles=("Kickboxer", "Karate", "Taekwondo"), minimum_skill=64, energy=1.2, miss_risk=1.18, counter_risk=1.2,
         tags=("strike", "kick", "head", "creative"), side="rear", range_band="kicking",
         defense_families=("block", "evade", "catch")),
    move("wheel_kick", "wheel kick", "kick", STANDING_POSITIONS, targets=frozenset({"head"}),
         attack_skills=("creative_kicks", "high_kick_speed", "flexibility"), defense_skills=("kick_defence", "reflexes"),
         preferred_styles=("Taekwondo", "Karate"), minimum_skill=70, energy=1.34, miss_risk=1.32, counter_risk=1.36,
         tags=("strike", "kick", "head", "spinning", "high-risk"), side="rear", range_band="long",
         defense_families=("evade", "duck", "jam")),
    move("spinning_back_kick", "spinning back kick", "kick", STANDING_POSITIONS, targets=frozenset({"body"}),
         attack_skills=("creative_kicks", "low_kick_power", "mobility"), defense_skills=("kick_defence", "footwork"),
         preferred_styles=("Taekwondo", "Karate", "Sanda"), minimum_skill=66, energy=1.3, miss_risk=1.28, counter_risk=1.32,
         tags=("strike", "kick", "body", "spinning", "high-risk"), side="rear", range_band="long",
         defense_families=("sidestep", "jam", "catch")),
    move("switch_body_kick", "switch kick to the body", "kick", STANDING_POSITIONS, targets=frozenset({"body"}),
         attack_skills=("high_kick_technique", "low_kick_speed", "footwork"), defense_skills=("kick_defence", "guard_defence"),
         preferred_styles=("Muay Thai", "Kickboxer"), minimum_skill=57, energy=1.16,
         tags=("strike", "kick", "body", "stance-shift"), side="lead", range_band="kicking",
         defense_families=("block", "catch", "evade")),
    move("jab_low_kick", "jab to outside low kick", "kick", STANDING_POSITIONS, targets=frozenset({"leg"}),
         attack_skills=("combination_punching", "low_kick_technique", "hand_speed"), defense_skills=("guard_defence", "kick_defence"),
         preferred_styles=("Kickboxer", "Dutch Kickboxer"), minimum_skill=55, energy=1.18, counter_risk=1.12,
         tags=("strike", "kick", "leg", "mixed-combination"), side="rear", range_band="pocket-to-kicking",
         defense_families=("parry-check", "pullback", "catch")),
    move("cross_body_kick", "cross to body kick", "kick", STANDING_POSITIONS, targets=frozenset({"body"}),
         attack_skills=("combination_punching", "high_kick_technique", "punch_technique"), defense_skills=("head_movement", "kick_defence"),
         preferred_styles=("Kickboxer", "Muay Thai"), minimum_skill=58, energy=1.22, counter_risk=1.15,
         tags=("strike", "kick", "body", "mixed-combination"), side="rear", range_band="pocket-to-kicking",
         defense_families=("slip-block", "catch", "evade")),
    move("hook_low_kick", "lead hook to low kick", "kick", STANDING_POSITIONS, targets=frozenset({"leg"}),
         attack_skills=("combination_punching", "low_kick_power", "creative_punches"), defense_skills=("guard_defence", "kick_defence"),
         preferred_styles=("Dutch Kickboxer", "Muay Thai"), minimum_skill=59, energy=1.24, counter_risk=1.18,
         tags=("strike", "kick", "leg", "mixed-combination"), side="rear", range_band="pocket-to-kicking",
         defense_families=("block-check", "pullback", "catch")),
    move("punch_head_kick", "one-two to head kick", "kick", STANDING_POSITIONS, targets=frozenset({"head"}),
         attack_skills=("combination_punching", "high_kick_technique", "creative_kicks"), defense_skills=("guard_defence", "head_movement"),
         preferred_styles=("Kickboxer", "Taekwondo"), minimum_skill=65, energy=1.34, miss_risk=1.2, counter_risk=1.28,
         tags=("strike", "kick", "head", "mixed-combination", "high-risk"), side="rear", range_band="pocket-to-kicking",
         defense_families=("shell", "evade", "jam")),
    move("double_jab_low_kick", "double jab to outside low kick", "kick", STANDING_POSITIONS,
         targets=frozenset({"leg"}),
         attack_skills=("combination_punching", "low_kick_technique", "hand_speed"),
         defense_skills=("guard_defence", "kick_defence"),
         preferred_styles=("Dutch Kickboxer", "Kickboxer"), minimum_skill=58, energy=1.24,
         counter_risk=1.16, tags=("strike", "kick", "leg", "mixed-combination"), side="rear",
         range_band="pocket-to-kicking", defense_families=("parry-check", "pullback", "catch")),
    move("cross_hook_body_kick", "cross-lead hook to body kick", "kick", STANDING_POSITIONS,
         targets=frozenset({"body"}),
         attack_skills=("combination_punching", "high_kick_technique", "punch_power"),
         defense_skills=("guard_defence", "kick_defence"),
         preferred_styles=("Dutch Kickboxer", "Muay Thai"), minimum_skill=61, energy=1.28,
         counter_risk=1.2, tags=("strike", "kick", "body", "mixed-combination", "power"), side="rear",
         range_band="pocket-to-kicking", defense_families=("shell", "catch", "evade")),
    move("axe_kick", "axe kick", "kick", STANDING_POSITIONS, targets=frozenset({"head"}),
         attack_skills=("creative_kicks", "high_kick_technique", "flexibility"),
         defense_skills=("kick_defence", "reflexes"),
         preferred_styles=("Taekwondo", "Karate"), minimum_skill=68, energy=1.3, miss_risk=1.28,
         counter_risk=1.34, tags=("strike", "kick", "head", "power", "finisher"), side="rear",
         range_band="long", defense_families=("sidestep", "evade", "jam")),
    move("jumping_front_kick", "jumping front kick", "kick", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("creative_kicks", "high_kick_speed", "mobility"),
         defense_skills=("kick_defence", "footwork"),
         preferred_styles=("Karate", "Taekwondo", "Sanda"), minimum_skill=69, energy=1.34,
         miss_risk=1.32, counter_risk=1.38,
         tags=("strike", "kick", "head", "flying", "power", "finisher"), side="lead",
         range_band="long", defense_families=("sidestep", "evade", "jam")),
    move("intercepting_knee", "intercepting knee", "power_punch", STANDING_POSITIONS,
         attack_skills=("knees", "counter_timing", "reflexes"), defense_skills=("footwork", "takedown_defence_detail"),
         preferred_styles=("Muay Thai", "Sanda"), minimum_skill=60, energy=1.18, counter_risk=1.08,
         tags=("strike", "knee", "counter")),
    move("jab_cross_rear_knee", "jab-cross to rear knee upstairs", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("combination_punching", "knees", "punch_technique"),
         defense_skills=("guard_defence", "clinch_defence"),
         preferred_styles=("Muay Thai", "Kickboxer"), minimum_skill=60, energy=1.26,
         counter_risk=1.2, tags=("strike", "combination", "knee", "head", "mixed-combination")),
    move("hook_elbow_knee", "lead hook-rear elbow-lead knee", "power_punch", STANDING_POSITIONS,
         attack_skills=("combination_punching", "elbows", "knees"),
         defense_skills=("guard_defence", "reflexes"),
         preferred_styles=("Muay Thai", "Sanda"), minimum_skill=64, energy=1.3, miss_risk=1.1,
         counter_risk=1.24, tags=("strike", "combination", "elbow", "knee", "power")),
    move("flying_knee", "flying knee", "power_punch", STANDING_POSITIONS,
         attack_skills=("knees", "creative_kicks", "strength"), defense_skills=("reflexes", "footwork"),
         preferred_styles=("Muay Thai", "Kickboxer"), minimum_skill=72, energy=1.42, miss_risk=1.4, counter_risk=1.45,
         tags=("strike", "knee", "flying", "high-risk")),
    move("switch_flying_knee", "switch flying knee", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("knees", "creative_kicks", "footwork"),
         defense_skills=("reflexes", "head_movement"),
         preferred_styles=("Muay Thai", "Kickboxer", "Sanda", "MMA Generalist"), minimum_skill=70, energy=1.38,
         miss_risk=1.34, counter_risk=1.4,
         tags=("strike", "knee", "flying", "power", "head", "finisher")),
    move("step_in_elbow", "step-in elbow", "power_punch", STANDING_POSITIONS,
         attack_skills=("elbows", "hand_speed", "footwork"), defense_skills=("guard_defence", "reflexes"),
         preferred_styles=("Muay Thai", "Sanda"), minimum_skill=60, energy=1.14, counter_risk=1.15,
         tags=("strike", "elbow")),
    move("spinning_elbow", "spinning elbow", "power_punch", STANDING_POSITIONS,
         attack_skills=("elbows", "creative_punches", "mobility"), defense_skills=("reflexes", "head_movement"),
         preferred_styles=("Muay Thai", "Sanda"), minimum_skill=70, energy=1.32, miss_risk=1.32, counter_risk=1.4,
         tags=("strike", "elbow", "spinning", "high-risk")),
    move("boxer_double_jab_pivot_cross_hook", "double jab-pivot-cross-hook", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("combination_punching", "footwork", "punch_technique"),
         defense_skills=("guard_defence", "head_movement"), preferred_styles=("Boxer",), minimum_skill=62,
         energy=1.24, counter_risk=1.16, tags=("strike", "punch", "combination", "style-combination", "head"),
         components=("jab", "jab", "pivot cross", "lead hook")),
    move("kickboxer_cross_hook_switch_kick", "cross-hook-switch body kick", "kick", STANDING_POSITIONS,
         targets=frozenset({"body"}), attack_skills=("combination_punching", "high_kick_technique", "footwork"),
         defense_skills=("guard_defence", "kick_defence"), preferred_styles=("Kickboxer",), minimum_skill=61,
         energy=1.28, counter_risk=1.18, tags=("strike", "kick", "mixed-combination", "style-combination", "body"),
         side="lead", range_band="pocket-to-kicking", defense_families=("shell", "catch", "evade"),
         components=("cross", "lead hook", "switch body kick")),
    move("dutch_high_guard_hook_cross_low_kick", "high-guard hook-cross-low-kick chain", "kick", STANDING_POSITIONS,
         targets=frozenset({"leg"}), attack_skills=("combination_punching", "low_kick_power", "conditioning"),
         defense_skills=("guard_defence", "kick_defence"), preferred_styles=("Dutch Kickboxer",), minimum_skill=62,
         energy=1.3, counter_risk=1.2,
         tags=("strike", "kick", "mixed-combination", "style-combination", "leg", "pressure"), side="rear",
         range_band="pocket-to-kicking", defense_families=("block-check", "pullback", "catch"),
         components=("high guard entry", "lead hook", "rear cross", "outside low kick")),
    move("muay_thai_teep_cross_elbow_knee", "teep-cross-elbow-knee chain", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("combination_punching", "elbows", "knees"),
         defense_skills=("guard_defence", "clinch_defence"), preferred_styles=("Muay Thai",), minimum_skill=64,
         energy=1.32, counter_risk=1.22,
         tags=("strike", "combination", "style-combination", "elbow", "knee", "head"),
         components=("lead teep", "rear cross", "lead elbow", "rear knee")),
    move("karate_blitz_cross_hook_exit", "blitz cross-hook angle exit", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("combination_punching", "footwork", "hand_speed"),
         defense_skills=("head_movement", "reflexes"), preferred_styles=("Karate",), minimum_skill=62,
         energy=1.2, miss_risk=1.08, counter_risk=1.1,
         tags=("strike", "punch", "combination", "style-combination", "stance-shift", "head"),
         components=("blitzing straight", "reverse cross", "lead hook", "angle exit")),
    move("taekwondo_side_back_round_chain", "side-kick-back-kick-round-kick chain", "kick", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("creative_kicks", "high_kick_speed", "flexibility"),
         defense_skills=("kick_defence", "reflexes"), preferred_styles=("Taekwondo",), minimum_skill=68,
         energy=1.36, miss_risk=1.2, counter_risk=1.28,
         tags=("strike", "kick", "combination", "style-combination", "spinning", "head"), side="rear",
         range_band="long", defense_families=("sidestep", "evade", "jam"),
         components=("lead side kick", "spinning back kick", "rear round kick to head")),
    move("sanda_side_kick_overhand_shot", "side-kick-overhand-to-shot chain", "shoot", STANDING_POSITIONS,
         attack_skills=("creative_kicks", "punch_technique", "takedown_setup"), defense_skills=("kick_defence", "sprawl"),
         preferred_styles=("Sanda",), minimum_skill=59, energy=1.24, follow_ups=("single_leg_finish",),
         tags=("strike", "wrestling", "entry", "mixed-combination", "style-combination"),
         components=("lead side kick", "rear overhand", "single-leg entry")),
    move("wrestler_jab_overhand_double", "jab-overhand-double-leg chain", "shoot", STANDING_POSITIONS,
         attack_skills=("takedown_setup", "takedowns", "punch_power"), defense_skills=("head_movement", "sprawl"),
         preferred_styles=("Wrestler",), minimum_skill=58, energy=1.22, follow_ups=("double_leg_finish",),
         tags=("strike", "wrestling", "entry", "mixed-combination", "style-combination"),
         components=("jab", "rear overhand", "double-leg entry")),
    move("freestyle_feint_reshot_chain", "level-change-feint to re-shot chain", "shoot", STANDING_POSITIONS,
         attack_skills=("takedown_speed", "chain_wrestling", "scrambles"),
         defense_skills=("sprawl", "takedown_defence_detail"), preferred_styles=("Freestyle Wrestler",),
         minimum_skill=60, energy=1.22, follow_ups=("single_leg_finish",),
         tags=("wrestling", "entry", "scramble", "style-combination"),
         components=("level-change feint", "outside single", "re-shot")),
    move("catch_snapdown_go_behind_chain", "collar-tie snapdown-go-behind chain", "clinch", STANDING_POSITIONS,
         attack_skills=("clinch_control", "chain_wrestling", "ride_control"), defense_skills=("clinch_defence", "scrambles"),
         preferred_styles=("Catch Wrestler",), minimum_skill=60, energy=1.18, follow_ups=("body_lock_trip",),
         tags=("clinch", "entry", "front-headlock", "style-combination"),
         components=("collar tie", "snapdown", "go-behind")),
    move("bjj_arm_drag_back_take_chain", "arm-drag-back-take-seatbelt chain", "advance_position",
         frozenset({"guard", "half guard", "side control", "mount", "turtle"}),
         attack_skills=("transitions", "back_control", "submission_attack"),
         defense_skills=("scrambles", "submission_defence_detail"), preferred_styles=("BJJ",), minimum_skill=61,
         energy=1.16, follow_ups=("back_take_transition", "rear_naked_choke"),
         tags=("ground", "transition", "back-take", "style-combination"),
         components=("arm drag", "back take", "seatbelt control")),
    move("luta_knee_line_leg_entanglement_chain", "knee-line entry to leg-entanglement chain", "sweep",
         frozenset({"guard", "half guard", "leg entanglement"}),
         attack_skills=("leg_locks", "scrambles", "bottom_control"),
         defense_skills=("submission_defence_detail", "guard_work"), preferred_styles=("Luta Livre",), minimum_skill=62,
         energy=1.18, follow_ups=("heel_hook",), tags=("ground", "leg-lock", "scramble", "style-combination"),
         components=("knee-line entry", "leg entanglement", "heel-hook threat")),
    move("sambo_overhand_body_lock_trip", "overhand-body-lock-outside-trip chain", "clinch", STANDING_POSITIONS,
         attack_skills=("punch_power", "clinch_control", "throws"), defense_skills=("head_movement", "clinch_defence"),
         preferred_styles=("Sambo",), minimum_skill=60, energy=1.22, follow_ups=("outside_trip",),
         tags=("strike", "clinch", "entry", "trip", "style-combination"),
         components=("rear overhand", "body lock", "outside trip")),
    move("judo_grip_foot_sweep_throw_chain", "grip-foot-sweep-hip-throw chain", "clinch", STANDING_POSITIONS,
         attack_skills=("clinch_control", "throws", "mobility"), defense_skills=("clinch_defence", "strength"),
         preferred_styles=("Judo",), minimum_skill=61, energy=1.2, follow_ups=("inside_trip",),
         tags=("clinch", "entry", "throw", "trip", "style-combination"),
         components=("collar grip", "foot sweep", "hip-turn throw")),
    move("grappler_jab_body_lock_mat_return", "jab-body-lock-mat-return chain", "clinch", STANDING_POSITIONS,
         attack_skills=("takedown_setup", "clinch_control", "positional_ability"),
         defense_skills=("guard_defence", "clinch_defence"), preferred_styles=("Grappler",), minimum_skill=58,
         energy=1.18, follow_ups=("body_lock_trip",),
         tags=("strike", "clinch", "entry", "control", "style-combination"),
         components=("jab", "body lock", "mat-return entry")),
    move("submission_grappler_pass_back_take_chain", "pass-back-take-choke chain", "advance_position",
         frozenset({"guard", "half guard", "side control", "mount", "turtle"}),
         attack_skills=("transitions", "back_control", "submission_attack"), defense_skills=("guard_work", "scrambles"),
         preferred_styles=("Submission Grappler",), minimum_skill=62, energy=1.18,
         follow_ups=("back_take_transition", "top_submission_chain"),
         tags=("ground", "transition", "back-take", "choke", "style-combination"),
         components=("guard pass", "back-take transition", "choke threat")),
    move("well_rounded_jab_low_kick_level_change", "jab-low-kick-level-change chain", "shoot", STANDING_POSITIONS,
         attack_skills=("combination_punching", "low_kick_technique", "takedown_setup"),
         defense_skills=("guard_defence", "kick_defence", "sprawl"), preferred_styles=("Well-Rounded",), minimum_skill=59,
         energy=1.22, follow_ups=("double_leg_finish",),
         tags=("strike", "low-kick", "wrestling", "entry", "mixed-combination", "style-combination"),
         components=("jab", "outside low kick", "level change")),
    move("mma_generalist_cross_kick_clinch_chain", "cross-body-kick-clinch chain", "kick", STANDING_POSITIONS,
         targets=frozenset({"body"}), attack_skills=("combination_punching", "high_kick_technique", "clinch_control"),
         defense_skills=("guard_defence", "kick_defence"), preferred_styles=("MMA Generalist",), minimum_skill=59,
         energy=1.24, counter_risk=1.16,
         tags=("strike", "kick", "mixed-combination", "style-combination", "body"), side="rear",
         range_band="pocket-to-kicking", defense_families=("slip-block", "catch", "evade"),
         components=("rear cross", "body kick", "collar-tie entry")),
    move("boxer_shift_step_cross_finisher", "shift-step rear cross", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("punch_power", "punch_technique", "footwork"),
         defense_skills=("head_movement", "guard_defence"), preferred_styles=("Boxer",), minimum_skill=65,
         energy=1.2, miss_risk=1.08, counter_risk=1.16,
         tags=("strike", "punch", "power", "head", "finisher", "style-finisher")),
    move("kickboxer_cross_high_kick_finisher", "rear cross to high kick", "kick", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("combination_punching", "high_kick_power", "high_kick_technique"),
         defense_skills=("guard_defence", "head_movement"), preferred_styles=("Kickboxer",), minimum_skill=66,
         energy=1.3, miss_risk=1.16, counter_risk=1.24,
         tags=("strike", "kick", "head", "power", "mixed-combination", "finisher", "style-finisher"),
         side="rear", range_band="pocket-to-kicking", defense_families=("shell", "evade", "jam"),
         components=("rear cross", "high kick")),
    move("dutch_high_guard_cross_hook_finisher", "high-guard cross-hook finish", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("combination_punching", "punch_power", "conditioning"),
         defense_skills=("guard_defence", "head_movement"), preferred_styles=("Dutch Kickboxer",), minimum_skill=66,
         energy=1.26, miss_risk=1.1, counter_risk=1.2,
         tags=("strike", "punch", "combination", "head", "power", "finisher", "style-finisher"),
         components=("high guard entry", "rear cross", "lead hook")),
    move("muay_thai_frame_elbow_finisher", "collar-frame slicing elbow", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("elbows", "thai_plum", "killer_instinct"),
         defense_skills=("guard_defence", "clinch_defence"), preferred_styles=("Muay Thai",), minimum_skill=66,
         energy=1.22, miss_risk=1.08, counter_risk=1.18,
         tags=("strike", "elbow", "power", "head", "finisher", "style-finisher")),
    move("karate_blitz_reverse_cross_finisher", "blitzing reverse cross", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("punch_power", "hand_speed", "footwork"),
         defense_skills=("head_movement", "reflexes"), preferred_styles=("Karate",), minimum_skill=65,
         energy=1.18, miss_risk=1.1, counter_risk=1.16,
         tags=("strike", "punch", "power", "head", "stance-shift", "finisher", "style-finisher")),
    move("taekwondo_spinning_hook_kick_finisher", "spinning hook kick", "kick", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("creative_kicks", "high_kick_power", "flexibility"),
         defense_skills=("kick_defence", "reflexes"), preferred_styles=("Taekwondo",), minimum_skill=70,
         energy=1.36, miss_risk=1.3, counter_risk=1.38,
         tags=("strike", "kick", "head", "power", "spinning", "finisher", "style-finisher"), side="rear",
         range_band="long", defense_families=("evade", "duck", "jam")),
    move("sanda_jumping_side_kick_finisher", "jumping side kick to the head", "kick", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("creative_kicks", "high_kick_speed", "mobility"),
         defense_skills=("kick_defence", "footwork"), preferred_styles=("Sanda",), minimum_skill=67,
         energy=1.32, miss_risk=1.24, counter_risk=1.3,
         tags=("strike", "kick", "head", "power", "flying", "finisher", "style-finisher"), side="lead",
         range_band="long", defense_families=("sidestep", "evade", "jam")),
    move("wrestler_wrist_ride_hammerfist_finisher", "wrist-ride hammerfist barrage", "ground_strikes",
         frozenset({"half guard", "side control", "turtle"}),
         attack_skills=("ground_striking", "ride_control", "punch_power"),
         defense_skills=("bottom_control", "get_ups"), preferred_styles=("Wrestler",), minimum_skill=62,
         energy=1.22, counter_risk=1.14, tags=("ground", "strike", "punch", "power", "style-finisher"),
         components=("wrist ride", "hammerfist", "short punch", "hammerfist")),
    move("freestyle_mat_return_ground_pound_finisher", "mat-return ground-and-pound barrage", "ground_strikes",
         frozenset({"half guard", "side control", "turtle"}),
         attack_skills=("ground_striking", "chain_wrestling", "conditioning"),
         defense_skills=("scrambles", "get_ups"), preferred_styles=("Freestyle Wrestler",), minimum_skill=62,
         energy=1.24, counter_risk=1.14, tags=("ground", "strike", "punch", "power", "style-finisher"),
         components=("mat return", "short punch", "hammerfist", "ride punch")),
    move("catch_cradle_neck_crank_finisher", "cradle neck crank", "submission",
         frozenset({"side control", "turtle"}),
         attack_skills=("submission_attack", "ride_control", "strength"),
         defense_skills=("submission_defence_detail", "scrambles"), preferred_styles=("Catch Wrestler",),
         minimum_skill=64, energy=1.16, counter_risk=1.14,
         tags=("ground", "submission", "joint", "style-finisher"), attack_path="cradle-and-neck isolation",
         failure_outcomes=("retain ride", "concede guard", "lose the cradle")),
    move("bjj_triangle_armbar_finisher", "triangle-to-armbar finish", "bottom_submission",
         frozenset({"guard"}), attack_skills=("submission_attack", "guard_work", "transitions"),
         defense_skills=("submission_defence_detail", "composure"), preferred_styles=("BJJ",), minimum_skill=65,
         energy=1.16, counter_risk=1.14,
         tags=("ground", "submission", "guard", "joint", "choke", "style-finisher"),
         attack_path="triangle lock chained to arm extension",
         failure_outcomes=("retain guard", "concede pass", "return neutral")),
    move("luta_outside_heel_hook_finisher", "outside heel hook finish", "bottom_submission",
         frozenset({"guard", "half guard"}), attack_skills=("leg_locks", "submission_attack", "scrambles"),
         defense_skills=("submission_defence_detail", "mobility"), preferred_styles=("Luta Livre",), minimum_skill=66,
         energy=1.18, counter_risk=1.18, tags=("ground", "submission", "leg-lock", "style-finisher"),
         attack_path="outside ashi heel exposure",
         failure_outcomes=("retain entanglement", "recover guard", "concede top")),
    move("sambo_rolling_kneebar_finisher", "rolling kneebar finish", "bottom_submission",
         frozenset({"guard", "half guard"}), attack_skills=("leg_locks", "submission_attack", "throws"),
         defense_skills=("submission_defence_detail", "mobility"), preferred_styles=("Sambo",), minimum_skill=65,
         energy=1.18, counter_risk=1.18, tags=("ground", "submission", "leg-lock", "style-finisher"),
         attack_path="rolling knee-line isolation",
         failure_outcomes=("retain entanglement", "recover guard", "concede top")),
    move("judo_kesa_armbar_finisher", "kesa-gatame armbar", "submission",
         frozenset({"side control"}), attack_skills=("submission_attack", "top_control", "throws"),
         defense_skills=("submission_defence_detail", "scrambles"), preferred_styles=("Judo",), minimum_skill=64,
         energy=1.14, counter_risk=1.12, tags=("ground", "submission", "joint", "style-finisher"),
         attack_path="scarf-hold arm isolation",
         failure_outcomes=("retain side control", "concede half guard", "lose the arm")),
    move("grappler_arm_triangle_finisher", "mounted arm-triangle finish", "submission",
         frozenset({"side control", "mount"}),
         attack_skills=("submission_attack", "top_control", "positional_ability"),
         defense_skills=("submission_defence_detail", "scrambles"), preferred_styles=("Grappler",), minimum_skill=64,
         energy=1.14, counter_risk=1.12, tags=("ground", "submission", "choke", "style-finisher"),
         attack_path="head-and-arm compression from top",
         failure_outcomes=("retain mount", "retain side control", "concede half guard")),
    move("submission_grappler_rear_triangle_finisher", "rear-triangle finish", "submission",
         frozenset({"back control", "mount"}),
         attack_skills=("submission_attack", "back_control", "transitions"),
         defense_skills=("submission_defence_detail", "scrambles"), preferred_styles=("Submission Grappler",),
         minimum_skill=66, energy=1.16, counter_risk=1.14,
         tags=("ground", "submission", "choke", "back-control", "style-finisher"),
         attack_path="back-control leg triangle",
         failure_outcomes=("retain back control", "concede guard", "lose the triangle")),
    move("well_rounded_cross_head_kick_finisher", "rear cross to head-kick finish", "kick", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("combination_punching", "high_kick_power", "adaptability"),
         defense_skills=("guard_defence", "head_movement"), preferred_styles=("Well-Rounded",), minimum_skill=66,
         energy=1.3, miss_risk=1.16, counter_risk=1.24,
         tags=("strike", "kick", "head", "power", "mixed-combination", "finisher", "style-finisher"),
         side="rear", range_band="pocket-to-kicking", defense_families=("shell", "evade", "jam"),
         components=("rear cross", "head kick")),
    move("mma_generalist_elbow_knee_finisher", "step-in elbow to rear knee", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("elbows", "knees", "combination_punching"),
         defense_skills=("guard_defence", "clinch_defence"), preferred_styles=("MMA Generalist",), minimum_skill=65,
         energy=1.28, miss_risk=1.12, counter_risk=1.22,
         tags=("strike", "elbow", "knee", "power", "head", "finisher", "style-finisher"),
         components=("step-in elbow", "rear knee")),
    move("double_leg_entry", "double-leg entry", "shoot", STANDING_POSITIONS,
         attack_skills=("takedowns", "takedown_setup", "takedown_speed"), defense_skills=("sprawl", "takedown_defence_detail"),
         preferred_styles=("Wrestler", "Freestyle Wrestler"), energy=1.15, follow_ups=("double_leg_finish",), tags=("wrestling", "entry")),
    move("single_leg_entry", "single-leg entry", "shoot", STANDING_POSITIONS,
         attack_skills=("takedowns", "chain_wrestling", "takedown_speed"), defense_skills=("sprawl", "scrambles"),
         preferred_styles=("Wrestler", "Sanda", "Sambo"), follow_ups=("single_leg_finish",), tags=("wrestling", "entry")),
    move("collar_tie_entry", "collar-tie entry", "clinch", STANDING_POSITIONS,
         attack_skills=("clinch_control", "hand_speed"), defense_skills=("clinch_defence", "footwork"),
         preferred_styles=("Muay Thai", "Wrestler"), follow_ups=("clinch_knee",), tags=("clinch", "entry")),
    move("body_lock_entry", "body-lock entry", "clinch", STANDING_POSITIONS,
         attack_skills=("clinch_control", "strength", "cage_pressure"), defense_skills=("clinch_defence", "mobility"),
         preferred_styles=("Judo", "Sambo", "Wrestler"), follow_ups=("body_lock_trip",), tags=("clinch", "entry")),
    move("over_under_entry", "over-under entry", "clinch", STANDING_POSITIONS,
         attack_skills=("clinch_control", "clinch_defence", "strength"), defense_skills=("clinch_defence", "footwork"),
         preferred_styles=("Wrestler", "Judo", "Sambo"), follow_ups=("outside_trip",), tags=("clinch", "entry")),
    move("double_underhooks", "double-underhook entry", "clinch", STANDING_POSITIONS,
         attack_skills=("clinch_control", "cage_pressure", "strength"), defense_skills=("clinch_defence", "mobility"),
         preferred_styles=("Wrestler", "Freestyle Wrestler"), minimum_skill=56, energy=1.1,
         follow_ups=("knee_tap",), tags=("clinch", "entry", "underhooks")),
    move("thai_plum_entry", "Thai-plum entry", "clinch", STANDING_POSITIONS,
         attack_skills=("thai_plum", "clinch_control", "hand_speed"), defense_skills=("clinch_defence", "strength"),
         preferred_styles=("Muay Thai",), minimum_skill=55, follow_ups=("clinch_knee",), tags=("clinch", "entry")),
    move("short_clinch_boxing", "short clinch boxing", "dirty_boxing", CLINCH_POSITIONS,
         attack_skills=("dirty_boxing", "punch_technique"), defense_skills=("clinch_defence", "guard_defence"),
         preferred_styles=("Boxer", "Catch Wrestler", "Sanda"), tags=("clinch", "strike", "punch")),
    move("clinch_knee", "knee from the clinch", "dirty_boxing", CLINCH_POSITIONS,
         attack_skills=("knees", "thai_plum", "clinch_control"), defense_skills=("clinch_defence", "strength"),
         preferred_styles=("Muay Thai", "Kickboxer"), energy=1.12, tags=("clinch", "strike", "knee")),
    move("double_leg_finish", "double-leg finish", "takedown", CLINCH_POSITIONS,
         attack_skills=("takedowns", "chain_wrestling", "strength"), defense_skills=("takedown_defence_detail", "sprawl"),
         preferred_styles=("Wrestler", "Freestyle Wrestler"), energy=1.18, tags=("wrestling", "takedown"),
         defense_families=("sprawl", "whizzer", "fence post"), entry_family="double leg",
         finish_positions=("guard", "half guard")),
    move("single_leg_finish", "single-leg finish", "takedown", CLINCH_POSITIONS,
         attack_skills=("takedowns", "chain_wrestling", "cage_wrestling"), defense_skills=("takedown_defence_detail", "scrambles"),
         preferred_styles=("Wrestler", "Sanda"), tags=("wrestling", "takedown"),
         defense_families=("whizzer", "limp leg", "balance"), entry_family="single leg",
         finish_positions=("guard", "half guard")),
    move("body_lock_trip", "body-lock trip", "takedown", CLINCH_POSITIONS,
         attack_skills=("clinch_takedowns", "throws", "clinch_control"), defense_skills=("clinch_defence", "mobility"),
         preferred_styles=("Judo", "Sambo", "Sanda"), tags=("clinch", "takedown", "trip"),
         defense_families=("base", "underhook", "hip turn"), entry_family="body lock",
         finish_positions=("guard", "half guard")),
    move("inside_trip", "inside trip", "takedown", CLINCH_POSITIONS,
         attack_skills=("throws", "clinch_takedowns", "clinch_control"), defense_skills=("clinch_defence", "mobility"),
         preferred_styles=("Judo", "Sambo", "Muay Thai"), minimum_skill=54, energy=1.08,
         tags=("clinch", "takedown", "trip"), defense_families=("wide base", "hip turn", "whizzer"),
         entry_family="over-under", finish_positions=("guard", "half guard")),
    move("outside_trip", "outside trip", "takedown", CLINCH_POSITIONS,
         attack_skills=("clinch_takedowns", "throws", "clinch_control"), defense_skills=("clinch_defence", "strength"),
         preferred_styles=("Judo", "Sambo"), minimum_skill=56, energy=1.12,
         tags=("clinch", "takedown", "trip"), defense_families=("hop", "underhook", "hip turn"),
         entry_family="over-under", finish_positions=("guard", "half guard")),
    move("high_crotch_finish", "high-crotch finish", "takedown", CLINCH_POSITIONS,
         attack_skills=("takedowns", "chain_wrestling", "slams"), defense_skills=("takedown_defence_detail", "scrambles"),
         preferred_styles=("Freestyle Wrestler", "Wrestler"), minimum_skill=58, energy=1.2,
         tags=("wrestling", "takedown", "chain"), defense_families=("whizzer", "hip pressure", "limp leg"),
         entry_family="high crotch", finish_positions=("guard", "half guard")),
    move("knee_tap", "knee-tap takedown", "takedown", CLINCH_POSITIONS,
         attack_skills=("clinch_takedowns", "chain_wrestling", "cage_wrestling"), defense_skills=("clinch_defence", "sprawl"),
         preferred_styles=("Wrestler", "Freestyle Wrestler"), minimum_skill=55, energy=1.12,
         tags=("wrestling", "takedown", "chain"), defense_families=("underhook", "sprawl", "fence post"),
         entry_family="underhook", finish_positions=("guard", "half guard")),
    move("hip_toss", "hip toss", "takedown", CLINCH_POSITIONS,
         attack_skills=("throws", "clinch_takedowns", "strength"), defense_skills=("clinch_defence", "mobility"),
         preferred_styles=("Judo", "Sambo"), minimum_skill=60, energy=1.18, counter_risk=1.16,
         tags=("clinch", "takedown", "throw"), defense_families=("hip block", "back step", "underhook"),
         entry_family="over-under", finish_positions=("side control", "guard")),
    move("lateral_drop", "lateral drop", "takedown", CLINCH_POSITIONS,
         attack_skills=("throws", "clinch_control", "strength"), defense_skills=("clinch_defence", "scrambles"),
         preferred_styles=("Catch Wrestler", "Sambo", "Judo"), minimum_skill=66, energy=1.3, miss_risk=1.22, counter_risk=1.3,
         tags=("clinch", "takedown", "throw", "high-risk"), defense_families=("base", "hip turn", "back take"),
         entry_family="over-under", finish_positions=("side control", "guard")),
    move("fence_pressure", "fence pressure", "cage_control", CLINCH_POSITIONS | STANDING_POSITIONS,
         attack_skills=("cage_pressure", "cage_wrestling", "clinch_control"), defense_skills=("clinch_defence", "get_ups"),
         preferred_styles=("Wrestler", "Sambo"), tags=("clinch", "control", "cage")),
    move("pummel_to_underhook", "pummel to underhook", "cage_control", CLINCH_POSITIONS,
         attack_skills=("clinch_control", "cage_wrestling", "conditioning"), defense_skills=("clinch_defence", "strength"),
         preferred_styles=("Wrestler", "Freestyle Wrestler"), energy=1.06,
         tags=("clinch", "control", "cage", "underhooks")),
    move("shoulder_pressure", "shoulder pressure on the fence", "cage_control", CLINCH_POSITIONS,
         attack_skills=("cage_pressure", "clinch_control", "strength"), defense_skills=("clinch_defence", "conditioning"),
         preferred_styles=("Wrestler", "Sambo", "Catch Wrestler"), tags=("clinch", "control", "cage")),
    move("pivot_exit", "pivoting clinch exit", "break_clinch", CLINCH_POSITIONS,
         attack_skills=("clinch_defence", "footwork", "mobility"), defense_skills=("clinch_control", "cage_pressure"),
         preferred_styles=("Boxer", "Karate", "Taekwondo"), tags=("clinch", "escape")),
    move("frame_exit", "frame-and-circle exit", "break_clinch", CLINCH_POSITIONS,
         attack_skills=("clinch_defence", "guard_defence", "footwork"), defense_skills=("clinch_control", "cage_pressure"),
         preferred_styles=("Boxer", "Kickboxer", "Muay Thai"), tags=("clinch", "escape", "frame")),
    move("ankle_pick_entry", "ankle-pick entry", "shoot", STANDING_POSITIONS,
         attack_skills=("takedown_setup", "takedown_speed", "creative_punches"), defense_skills=("sprawl", "mobility"),
         preferred_styles=("Wrestler", "Freestyle Wrestler", "Judo"), minimum_skill=58, energy=1.08,
         follow_ups=("single_leg_finish",), tags=("wrestling", "entry")),
    move("reactive_shot", "reactive double-leg shot", "shoot", STANDING_POSITIONS,
         attack_skills=("counter_timing", "takedown_speed", "takedowns"), defense_skills=("sprawl", "reflexes"),
         preferred_styles=("Wrestler", "Freestyle Wrestler"), minimum_skill=57, energy=1.12,
         follow_ups=("double_leg_finish",), tags=("wrestling", "entry", "counter")),
    move("jab_to_shot", "jab to double-leg entry", "shoot", STANDING_POSITIONS,
         attack_skills=("takedown_setup", "punch_technique", "takedown_speed"), defense_skills=("guard_defence", "sprawl"),
         preferred_styles=("Wrestler", "MMA Generalist"), minimum_skill=54, energy=1.14,
         follow_ups=("double_leg_finish",), tags=("wrestling", "entry", "mixed-combination")),
    move("overhand_to_double", "overhand to double-leg entry", "shoot", STANDING_POSITIONS,
         attack_skills=("takedown_setup", "punch_power", "chain_wrestling"), defense_skills=("head_movement", "sprawl"),
         preferred_styles=("Wrestler", "Sambo"), minimum_skill=58, energy=1.2, counter_risk=1.15,
         follow_ups=("double_leg_finish",), tags=("wrestling", "entry", "mixed-combination")),
    move("chained_reshot", "chained re-shot", "re_shot", frozenset({"failed shot"}),
         attack_skills=("chain_wrestling", "takedown_speed", "conditioning"), defense_skills=("sprawl", "scrambles"),
         preferred_styles=("Wrestler", "Freestyle Wrestler"), minimum_skill=58, energy=1.24,
         tags=("wrestling", "chain", "entry")),
    move("whizzer_recovery", "whizzer recovery", "recover_shot", frozenset({"failed shot"}),
         attack_skills=("clinch_defence", "scrambles", "strength"), defense_skills=("chain_wrestling", "cage_wrestling"),
         preferred_styles=("Wrestler", "Sambo"), tags=("wrestling", "defense", "scramble")),
    move("lift_mat_return", "lift-and-return mat return", "mat_return", frozenset({"standing back control"}),
         attack_skills=("slams", "ride_control", "strength"), defense_skills=("get_ups", "scrambles"),
         preferred_styles=("Wrestler", "Sambo"), minimum_skill=58, energy=1.22,
         tags=("wrestling", "takedown", "mat-return"), defense_families=("hand fight", "hip turn", "fence post"),
         entry_family="rear body lock", finish_positions=("back control", "guard")),
    move("rear_waist_ride", "rear-waist standing ride", "standing_back_ride", frozenset({"standing back control"}),
         attack_skills=("ride_control", "cage_wrestling", "conditioning"), defense_skills=("get_ups", "clinch_defence"),
         preferred_styles=("Wrestler", "Catch Wrestler"), tags=("wrestling", "control", "ride")),
    move("limp_leg_escape", "limp-leg escape", "standing_escape", frozenset({"standing back control"}),
         attack_skills=("scrambles", "mobility", "clinch_defence"), defense_skills=("ride_control", "cage_wrestling"),
         preferred_styles=("Freestyle Wrestler", "Sanda"), tags=("wrestling", "escape", "scramble")),
    move("snapdown_front_headlock", "snapdown to front headlock", "front_headlock", frozenset({"failed shot"}),
         attack_skills=("sprawl", "clinch_control", "submission_attack"), defense_skills=("scrambles", "get_ups"),
         preferred_styles=("Wrestler", "Catch Wrestler", "BJJ"), minimum_skill=55,
         tags=("wrestling", "front-headlock", "transition")),
    move("front_headlock_go_behind", "front-headlock go-behind", "take_back", frozenset({"front headlock"}),
         attack_skills=("submission_attack", "transitions", "ride_control"), defense_skills=("scrambles", "back_control"),
         preferred_styles=("Wrestler", "BJJ", "Catch Wrestler"), minimum_skill=56, energy=1.12,
         tags=("wrestling", "transition", "back-take")),
    move("posture_punches", "postured ground punches", "ground_strikes", GROUND_POSITIONS,
         attack_skills=("ground_striking", "top_control", "punch_power"), defense_skills=("guard_work", "bottom_control"),
         preferred_styles=("Wrestler", "Sambo"), tags=("ground", "strike", "punch")),
    move("short_ground_elbows", "short ground elbows", "ground_strikes", GROUND_POSITIONS,
         attack_skills=("ground_striking", "elbows", "positional_ability"), defense_skills=("guard_work", "scrambles"),
         preferred_styles=("Muay Thai", "BJJ"), minimum_skill=52, tags=("ground", "strike", "elbow")),
    move("body_head_ground_chain", "body-head ground-punch chain", "ground_strikes", GROUND_POSITIONS,
         attack_skills=("ground_striking", "combination_punching", "top_control"), defense_skills=("bottom_control", "guard_work"),
         preferred_styles=("Wrestler", "Sambo", "MMA Generalist"), minimum_skill=54, energy=1.12,
         tags=("ground", "strike", "combination")),
    move("ride_wrist_punches", "wrist-ride punches", "ground_strikes", frozenset({"turtle", "back control", "half guard"}),
         attack_skills=("ride_control", "ground_striking", "top_control"), defense_skills=("scrambles", "get_ups"),
         preferred_styles=("Wrestler", "Catch Wrestler"), minimum_skill=55,
         tags=("ground", "strike", "ride")),
    move("guard_posture_elbows", "posture-punch and elbow chain from guard", "ground_strikes", frozenset({"guard"}),
         attack_skills=("ground_striking", "elbows", "top_control"), defense_skills=("guard_work", "bottom_control"),
         preferred_styles=("Muay Thai", "Wrestler", "MMA Generalist"), minimum_skill=54, energy=1.12,
         follow_ups=("headquarters_pass",), tags=("ground", "strike", "elbow", "combination", "guard")),
    move("half_guard_crossface_strikes", "crossface striking chain from half guard", "ground_strikes", frozenset({"half guard"}),
         attack_skills=("ground_striking", "top_control", "punch_power"), defense_skills=("bottom_control", "guard_work"),
         preferred_styles=("Wrestler", "Sambo", "Catch Wrestler"), minimum_skill=55, energy=1.1,
         follow_ups=("underhook_half_guard_pass",), tags=("ground", "strike", "punch", "combination", "pressure")),
    move("crucifix_elbows", "crucifix elbows", "ground_strikes", frozenset({"side control"}),
         attack_skills=("ground_striking", "elbows", "positional_ability"), defense_skills=("scrambles", "bottom_control"),
         preferred_styles=("BJJ", "Wrestler", "Muay Thai"), minimum_skill=60, energy=1.18,
         follow_ups=("arm_triangle",), tags=("ground", "strike", "elbow", "control")),
    move("mounted_hammerfist_flurry", "mounted hammerfist flurry", "ground_strikes", frozenset({"mount"}),
         attack_skills=("ground_striking", "mount_control", "punch_power"), defense_skills=("bottom_control", "composure"),
         preferred_styles=("Wrestler", "Sambo", "MMA Generalist"), minimum_skill=58, energy=1.2,
         follow_ups=("arm_triangle", "top_armbar"), tags=("ground", "strike", "punch", "combination", "mount", "power")),
    move("back_control_short_punches", "short punches from back control", "ground_strikes", frozenset({"back control"}),
         attack_skills=("ground_striking", "back_control", "hand_speed"), defense_skills=("submission_defence_detail", "scrambles"),
         preferred_styles=("BJJ", "Wrestler", "Submission Grappler"), minimum_skill=56, energy=1.08,
         follow_ups=("rear_naked_choke",), tags=("ground", "strike", "punch", "back-control")),
    move("turtle_wrist_ride_strikes", "wrist-ride striking chain against turtle", "ground_strikes", frozenset({"turtle"}),
         attack_skills=("ride_control", "ground_striking", "elbows"), defense_skills=("get_ups", "scrambles"),
         preferred_styles=("Wrestler", "Catch Wrestler", "Sambo"), minimum_skill=57, energy=1.14,
         tags=("ground", "strike", "ride", "combination")),
    move("position_pass", "guard-passing transition", "advance_position", frozenset({"guard", "half guard"}),
         attack_skills=("transitions", "positional_ability", "top_control"), defense_skills=("guard_work", "bottom_control"),
         preferred_styles=("BJJ", "Submission Grappler"), follow_ups=("top_submission_chain", "back_take_transition"), tags=("ground", "transition")),
    move("knee_slice_pass", "knee-slice pass", "advance_position", frozenset({"guard", "half guard"}),
         attack_skills=("transitions", "top_control", "cage_wrestling"), defense_skills=("guard_work", "bottom_control"),
         preferred_styles=("BJJ", "Wrestler"), minimum_skill=54, energy=1.1,
         follow_ups=("arm_triangle", "mount_transition"), tags=("ground", "transition", "pass")),
    move("half_guard_pass", "half-guard pressure pass", "advance_position", frozenset({"half guard"}),
         attack_skills=("positional_ability", "top_control", "strength"), defense_skills=("bottom_control", "scrambles"),
         preferred_styles=("BJJ", "Wrestler", "Sambo"), minimum_skill=52,
         tags=("ground", "transition", "pass")),
    move("mount_transition", "side-control to mount transition", "advance_position", frozenset({"side control"}),
         attack_skills=("transitions", "positional_ability", "top_control"), defense_skills=("bottom_control", "scrambles"),
         preferred_styles=("BJJ", "Submission Grappler"), minimum_skill=56, energy=1.12,
         follow_ups=("arm_triangle",), tags=("ground", "transition", "mount")),
    move("back_take_transition", "back-take transition", "advance_position", frozenset({"half guard", "side control", "mount", "turtle"}),
         attack_skills=("back_control", "transitions", "scrambles"), defense_skills=("scrambles", "bottom_control"),
         preferred_styles=("BJJ", "Luta Livre", "Submission Grappler"), minimum_skill=58, energy=1.14,
         follow_ups=("rear_naked_choke",), tags=("ground", "transition", "back-take")),
    move("headquarters_pass", "headquarters passing sequence", "advance_position", frozenset({"guard"}),
         attack_skills=("transitions", "top_control", "footwork"), defense_skills=("guard_work", "bottom_control"),
         preferred_styles=("BJJ", "MMA Generalist", "Wrestler"), minimum_skill=54, energy=1.08,
         follow_ups=("half_guard_crossface_strikes",), tags=("ground", "transition", "pass", "guard")),
    move("body_lock_pass", "body-lock passing sequence", "advance_position", frozenset({"guard", "half guard"}),
         attack_skills=("top_control", "transitions", "strength"), defense_skills=("guard_work", "scrambles"),
         preferred_styles=("BJJ", "Wrestler", "Sambo"), minimum_skill=56, energy=1.12,
         follow_ups=("half_guard_crossface_strikes", "crucifix_elbows"), tags=("ground", "transition", "pass", "pressure")),
    move("underhook_half_guard_pass", "underhook half-guard pass", "advance_position", frozenset({"half guard"}),
         attack_skills=("top_control", "positional_ability", "strength"), defense_skills=("bottom_control", "scrambles"),
         preferred_styles=("Wrestler", "BJJ", "Catch Wrestler"), minimum_skill=55, energy=1.1,
         follow_ups=("crucifix_elbows",), tags=("ground", "transition", "pass", "underhook")),
    move("knee_on_belly_climb", "knee-on-belly climb", "advance_position", frozenset({"side control"}),
         attack_skills=("transitions", "positional_ability", "mobility"), defense_skills=("bottom_control", "scrambles"),
         preferred_styles=("BJJ", "Judo", "Submission Grappler"), minimum_skill=58, energy=1.12,
         follow_ups=("mounted_hammerfist_flurry", "back_control_short_punches"), tags=("ground", "transition", "mount", "pressure")),
    move("gift_wrap_transition", "gift-wrap transition", "advance_position", frozenset({"side control", "mount"}),
         attack_skills=("back_control", "transitions", "top_control"), defense_skills=("scrambles", "submission_defence_detail"),
         preferred_styles=("BJJ", "Catch Wrestler", "Submission Grappler"), minimum_skill=60, energy=1.14,
         follow_ups=("mounted_hammerfist_flurry", "rear_naked_choke"), tags=("ground", "transition", "back-take", "control")),
    move("turtle_breakdown", "turtle breakdown", "turtle_ride", frozenset({"turtle"}),
         attack_skills=("ride_control", "back_control", "strength"), defense_skills=("get_ups", "scrambles"),
         preferred_styles=("Wrestler", "Catch Wrestler", "BJJ"), minimum_skill=54,
         tags=("ground", "transition", "ride")),
    move("guard_recovery", "guard recovery", "recover_guard", frozenset({"half guard", "side control", "mount", "back control", "turtle", "front headlock", "leg entanglement"}),
         attack_skills=("guard_work", "bottom_control", "scrambles"), defense_skills=("top_control", "positional_ability"),
         preferred_styles=("BJJ", "Luta Livre"), tags=("ground", "escape", "transition")),
    move("closed_guard_retention", "closed-guard retention", "recover_guard", frozenset({"guard"}),
         attack_skills=("guard_work", "bottom_control", "reflexes"), defense_skills=("top_control", "positional_ability"),
         preferred_styles=("BJJ", "Luta Livre", "Submission Grappler"), minimum_skill=52,
         tags=("ground", "defense", "control", "guard")),
    move("butterfly_sweep", "butterfly sweep", "sweep", frozenset({"guard", "half guard"}),
         attack_skills=("guard_work", "scrambles", "transitions"), defense_skills=("top_control", "strength"),
         preferred_styles=("BJJ", "Judo"), tags=("ground", "sweep", "transition")),
    move("hip_bump_sweep", "hip-bump sweep", "sweep", frozenset({"guard"}),
         attack_skills=("guard_work", "transitions", "strength"), defense_skills=("top_control", "reflexes"),
         preferred_styles=("BJJ", "Luta Livre"), tags=("ground", "sweep", "transition")),
    move("scissor_sweep", "scissor sweep", "sweep", frozenset({"guard"}),
         attack_skills=("guard_work", "transitions", "reflexes"), defense_skills=("top_control", "strength"),
         preferred_styles=("BJJ", "Judo"), minimum_skill=53, energy=1.08,
         follow_ups=("guard_posture_elbows",), tags=("ground", "sweep", "transition", "guard")),
    move("flower_sweep", "flower sweep", "sweep", frozenset({"guard"}),
         attack_skills=("guard_work", "scrambles", "flexibility"), defense_skills=("top_control", "reflexes"),
         preferred_styles=("BJJ", "Submission Grappler"), minimum_skill=56, energy=1.1,
         follow_ups=("guard_posture_elbows",), tags=("ground", "sweep", "transition", "guard")),
    move("waiter_sweep", "waiter sweep", "sweep", frozenset({"guard", "half guard"}),
         attack_skills=("guard_work", "leg_locks", "transitions"), defense_skills=("top_control", "scrambles"),
         preferred_styles=("BJJ", "Luta Livre", "Submission Grappler"), minimum_skill=59, energy=1.12,
         follow_ups=("headquarters_pass",), tags=("ground", "sweep", "transition", "leg-entanglement")),
    move("lockdown_sweep", "lockdown sweep", "sweep", frozenset({"half guard"}),
         attack_skills=("bottom_control", "guard_work", "strength"), defense_skills=("top_control", "positional_ability"),
         preferred_styles=("BJJ", "Luta Livre"), minimum_skill=57, energy=1.12,
         follow_ups=("guard_posture_elbows",), tags=("ground", "sweep", "transition", "half-guard")),
    move("sit_out_reversal", "sit-out reversal", "turtle_escape", frozenset({"turtle", "front headlock"}),
         attack_skills=("scrambles", "mobility", "transitions"), defense_skills=("ride_control", "submission_defence_detail"),
         preferred_styles=("Wrestler", "Catch Wrestler"), minimum_skill=55, energy=1.14,
         tags=("ground", "sweep", "scramble")),
    move("technical_standup", "technical stand-up", "stand_up", frozenset({"guard", "half guard", "turtle"}),
         attack_skills=("get_ups", "mobility", "scrambles"), defense_skills=("ride_control", "top_control"),
         preferred_styles=("Wrestler", "Kickboxer", "Boxer"), tags=("ground", "escape")),
    move("post_and_build_getup", "post-and-build get-up", "stand_up", frozenset({"guard", "half guard", "turtle"}),
         attack_skills=("get_ups", "scrambles", "conditioning"), defense_skills=("ride_control", "top_control"),
         preferred_styles=("Wrestler", "Freestyle Wrestler", "MMA Generalist"), minimum_skill=54, energy=1.08,
         tags=("ground", "escape", "scramble")),
    move("tripod_standup", "tripod stand-up", "stand_up", frozenset({"guard", "half guard"}),
         attack_skills=("get_ups", "scrambles", "strength"), defense_skills=("ride_control", "top_control"),
         preferred_styles=("Wrestler", "Freestyle Wrestler", "Sambo"), minimum_skill=55, energy=1.1,
         tags=("ground", "escape", "scramble")),
    move("elbow_knee_guard_recovery", "elbow-knee guard recovery", "recover_guard", frozenset({"half guard", "side control", "mount"}),
         attack_skills=("guard_work", "bottom_control", "flexibility"), defense_skills=("top_control", "positional_ability"),
         preferred_styles=("BJJ", "Luta Livre", "Submission Grappler"), minimum_skill=54, energy=1.08,
         tags=("ground", "escape", "transition", "frame")),
    move("back_control_handfight_recovery", "back-control hand-fight recovery", "recover_guard", frozenset({"back control"}),
         attack_skills=("submission_defence_detail", "scrambles", "guard_work"), defense_skills=("back_control", "ride_control"),
         preferred_styles=("BJJ", "Wrestler", "Luta Livre"), minimum_skill=57, energy=1.1,
         tags=("ground", "escape", "transition", "back-control")),
    move("top_submission_chain", "top-position submission chain", "submission", GROUND_POSITIONS,
         attack_skills=("submission_attack", "positional_ability", "back_control"), defense_skills=("submission_defence_detail", "composure"),
         preferred_styles=("BJJ", "Submission Grappler", "Sambo"), tags=("ground", "submission"),
         attack_path="position-to-isolation", failure_outcomes=("retain position", "lose position", "return neutral")),
    move("guard_submission_chain", "guard submission chain", "bottom_submission", frozenset({"guard", "half guard"}),
         attack_skills=("submission_attack", "guard_work", "leg_locks"), defense_skills=("submission_defence_detail", "top_control"),
         preferred_styles=("BJJ", "Luta Livre"), tags=("ground", "submission", "guard"),
         attack_path="guard isolation", failure_outcomes=("retain guard", "concede pass", "return neutral")),
    move("rear_naked_choke", "rear-naked choke", "submission", frozenset({"back control"}),
         attack_skills=("submission_attack", "back_control", "positional_ability"), defense_skills=("submission_defence_detail", "composure"),
         preferred_styles=("BJJ", "Submission Grappler", "Luta Livre"), minimum_skill=58,
         tags=("ground", "submission", "choke"), attack_path="back-control neck exposure",
         failure_outcomes=("retain back", "lose hooks", "return neutral")),
    move("arm_triangle", "arm-triangle choke", "submission", frozenset({"side control", "mount"}),
         attack_skills=("submission_attack", "top_control", "positional_ability"), defense_skills=("submission_defence_detail", "strength"),
         preferred_styles=("BJJ", "Wrestler", "Sambo"), minimum_skill=57,
         tags=("ground", "submission", "choke"), attack_path="head-and-arm isolation",
         failure_outcomes=("retain top", "recover guard", "return neutral")),
    move("top_armbar", "top-position armbar", "submission", frozenset({"mount", "side control"}),
         attack_skills=("submission_attack", "positional_ability", "transitions"), defense_skills=("submission_defence_detail", "scrambles"),
         preferred_styles=("BJJ", "Judo", "Submission Grappler"), minimum_skill=59, energy=1.14, counter_risk=1.16,
         tags=("ground", "submission", "joint"), attack_path="arm isolation",
         failure_outcomes=("retain top", "lose position", "concede reversal")),
    move("americana", "Americana", "submission", frozenset({"side control", "mount"}),
         attack_skills=("submission_attack", "top_control", "strength"), defense_skills=("submission_defence_detail", "mobility"),
         preferred_styles=("BJJ", "Wrestler", "Catch Wrestler"), minimum_skill=54,
         tags=("ground", "submission", "joint"), attack_path="bent-arm isolation",
         failure_outcomes=("retain top", "recover guard")),
    move("guard_armbar", "armbar from guard", "bottom_submission", frozenset({"guard"}),
         attack_skills=("submission_attack", "guard_work", "flexibility"), defense_skills=("submission_defence_detail", "top_control"),
         preferred_styles=("BJJ", "Judo"), minimum_skill=56, energy=1.1,
         tags=("ground", "submission", "guard", "joint"), attack_path="guard arm isolation",
         failure_outcomes=("retain guard", "concede pass", "return neutral")),
    move("triangle_choke", "triangle choke", "bottom_submission", frozenset({"guard"}),
         attack_skills=("submission_attack", "guard_work", "flexibility"), defense_skills=("submission_defence_detail", "strength"),
         preferred_styles=("BJJ", "Submission Grappler"), minimum_skill=58, energy=1.12,
         tags=("ground", "submission", "guard", "choke"), attack_path="guard head-and-arm trap",
         failure_outcomes=("retain guard", "concede pass", "return neutral")),
    move("kimura_guard", "kimura from guard", "bottom_submission", frozenset({"guard", "half guard"}),
         attack_skills=("submission_attack", "guard_work", "positional_ability"), defense_skills=("submission_defence_detail", "strength"),
         preferred_styles=("BJJ", "Luta Livre", "Catch Wrestler"), minimum_skill=55,
         tags=("ground", "submission", "guard", "joint"), attack_path="figure-four shoulder isolation",
         failure_outcomes=("retain guard", "sweep", "concede pass")),
    move("omoplata", "omoplata", "bottom_submission", frozenset({"guard"}),
         attack_skills=("submission_attack", "guard_work", "flexibility"), defense_skills=("submission_defence_detail", "scrambles"),
         preferred_styles=("BJJ",), minimum_skill=63, energy=1.16, counter_risk=1.12,
         tags=("ground", "submission", "guard", "joint"), attack_path="leg-over shoulder isolation",
         failure_outcomes=("retain guard", "sweep", "concede pass")),
    move("guillotine_choke", "guillotine choke", "front_headlock_submission", frozenset({"front headlock"}),
         attack_skills=("submission_attack", "clinch_control", "strength"), defense_skills=("submission_defence_detail", "composure"),
         preferred_styles=("BJJ", "Luta Livre", "Catch Wrestler"), minimum_skill=55,
         tags=("ground", "submission", "front-headlock", "choke"), attack_path="front-headlock neck wrap",
         failure_outcomes=("retain front headlock", "concede guard", "return neutral")),
    move("anaconda_choke", "anaconda choke", "front_headlock_submission", frozenset({"front headlock"}),
         attack_skills=("submission_attack", "transitions", "strength"), defense_skills=("submission_defence_detail", "scrambles"),
         preferred_styles=("BJJ", "Submission Grappler"), minimum_skill=61, energy=1.14,
         tags=("ground", "submission", "front-headlock", "choke"), attack_path="arm-in front-headlock roll",
         failure_outcomes=("retain front headlock", "concede guard", "lose position")),
    move("darce_choke", "D'Arce choke", "front_headlock_submission", frozenset({"front headlock"}),
         attack_skills=("submission_attack", "transitions", "back_control"), defense_skills=("submission_defence_detail", "scrambles"),
         preferred_styles=("BJJ", "Luta Livre"), minimum_skill=62, energy=1.14,
         tags=("ground", "submission", "front-headlock", "choke"), attack_path="arm-in neck thread",
         failure_outcomes=("retain front headlock", "concede guard", "return neutral")),
    move("straight_ankle_lock", "straight ankle lock", "leg_attack", frozenset({"guard", "half guard", "leg entanglement"}),
         attack_skills=("leg_locks", "submission_attack", "transitions"), defense_skills=("submission_defence_detail", "scrambles"),
         preferred_styles=("BJJ", "Sambo", "Luta Livre"), minimum_skill=54,
         tags=("ground", "submission", "leg-lock"), attack_path="straight-leg entanglement",
         failure_outcomes=("retain entanglement", "recover guard", "return neutral")),
    move("kneebar", "kneebar", "leg_attack", frozenset({"guard", "half guard", "leg entanglement"}),
         attack_skills=("leg_locks", "submission_attack", "positional_ability"), defense_skills=("submission_defence_detail", "mobility"),
         preferred_styles=("Sambo", "BJJ", "Luta Livre"), minimum_skill=59, energy=1.12,
         tags=("ground", "submission", "leg-lock"), attack_path="knee-line isolation",
         failure_outcomes=("retain entanglement", "concede top", "return neutral")),
    move("heel_hook", "heel hook", "counter_leg_lock", frozenset({"leg entanglement"}),
         attack_skills=("leg_locks", "submission_attack", "counter_timing"), defense_skills=("submission_defence_detail", "composure"),
         preferred_styles=("Luta Livre", "Submission Grappler", "BJJ"), minimum_skill=66, energy=1.16, counter_risk=1.18,
         tags=("ground", "submission", "leg-lock", "counter"), attack_path="heel exposure from entanglement",
         failure_outcomes=("retain entanglement", "lose position", "return neutral")),
    move("toe_hold", "toe hold", "counter_leg_lock", frozenset({"leg entanglement"}),
         attack_skills=("leg_locks", "submission_attack", "strength"), defense_skills=("submission_defence_detail", "mobility"),
         preferred_styles=("Sambo", "Catch Wrestler", "Luta Livre"), minimum_skill=61, energy=1.1,
         tags=("ground", "submission", "leg-lock", "counter"), attack_path="figure-four foot isolation",
         failure_outcomes=("retain entanglement", "lose position", "return neutral")),
    move("ride_control", "heavy ride control", "ground_control", GROUND_POSITIONS,
         attack_skills=("ride_control", "top_control", "strength"), defense_skills=("scrambles", "get_ups"),
         preferred_styles=("Wrestler", "Catch Wrestler"), tags=("ground", "control")),
    move("half_guard_crossface_control", "crossface-and-underhook half-guard control", "ground_control", frozenset({"half guard"}),
         attack_skills=("top_control", "ride_control", "strength"), defense_skills=("bottom_control", "scrambles"),
         preferred_styles=("Wrestler", "Catch Wrestler", "Sambo"), minimum_skill=54,
         follow_ups=("underhook_half_guard_pass",), tags=("ground", "control", "pressure", "underhook")),
    move("mount_grapevine_control", "grapevine mount control", "ground_control", frozenset({"mount"}),
         attack_skills=("mount_control", "top_control", "strength"), defense_skills=("bottom_control", "scrambles"),
         preferred_styles=("BJJ", "Wrestler", "Submission Grappler"), minimum_skill=56,
         follow_ups=("mounted_hammerfist_flurry",), tags=("ground", "control", "mount")),
    move("body_triangle_back_control", "body-triangle back control", "ground_control", frozenset({"back control"}),
         attack_skills=("back_control", "ride_control", "conditioning"), defense_skills=("submission_defence_detail", "scrambles"),
         preferred_styles=("BJJ", "Submission Grappler", "Luta Livre"), minimum_skill=58, energy=1.06,
         follow_ups=("rear_naked_choke",), tags=("ground", "control", "back-control")),
    move("defensive_cling", "defensive clinch on the mat", "cling", GROUND_POSITIONS,
         attack_skills=("bottom_control", "composure", "guard_work"), defense_skills=("top_control", "ground_striking"),
         preferred_styles=("BJJ",), tags=("ground", "defense")),
    move("composed_survival", "composed survival", "survive", ALL_POSITIONS,
         attack_skills=("composure", "conditioning", "stun_recovery"), defense_skills=("killer_instinct",),
         preferred_styles=("Well-Rounded", "MMA Generalist"), tags=("defense", "recovery")),

    # --- Shallow-pool expansion -------------------------------------------------
    # "survive" and "cling" alone accounted for 26% of every move selection in the
    # game while holding a single technique each, so the two busiest actions in the
    # engine had no variety at all. These give the high-frequency actions a real
    # pool to draw from.
    move("shell_and_reset", "high shell and reset", "survive", STANDING_POSITIONS | CLINCH_POSITIONS,
         attack_skills=("guard_defence", "composure", "footwork"), defense_skills=("killer_instinct", "combination_punching"),
         preferred_styles=("Boxer", "Kickboxer"), tags=("defense", "recovery", "shell")),
    move("circling_breather", "circling breather", "survive", STANDING_POSITIONS,
         attack_skills=("footwork", "mobility", "conditioning"), defense_skills=("cage_pressure", "killer_instinct"),
         preferred_styles=("Karate", "Taekwondo", "MMA Generalist"), tags=("defense", "recovery", "movement")),
    move("clinch_lean_recovery", "clinch lean recovery", "survive", CLINCH_POSITIONS,
         attack_skills=("clinch_defence", "strength", "composure"), defense_skills=("clinch_control", "dirty_boxing"),
         preferred_styles=("Muay Thai", "Judo", "Wrestler"), tags=("defense", "recovery", "clinch")),
    move("bottom_frame_survival", "framing survival from bottom", "survive", GROUND_POSITIONS,
         attack_skills=("bottom_control", "guard_work", "composure"), defense_skills=("top_control", "ground_striking"),
         preferred_styles=("BJJ", "Luta Livre"), tags=("defense", "recovery", "ground")),
    move("heavy_top_breather", "heavy top breather", "survive", GROUND_POSITIONS,
         attack_skills=("top_control", "ride_control", "conditioning"), defense_skills=("scrambles", "bottom_control"),
         preferred_styles=("Wrestler", "Catch Wrestler"), tags=("defense", "recovery", "ground", "control")),

    move("wrist_ride_neutralize", "wrist-control neutralization", "cling", GROUND_POSITIONS,
         attack_skills=("bottom_control", "guard_work", "composure"), defense_skills=("ground_striking", "top_control"),
         preferred_styles=("BJJ", "Submission Grappler"), tags=("ground", "defense", "wrist-control")),
    move("closed_guard_hold", "closed guard hold", "cling", frozenset({"guard", "half guard"}),
         attack_skills=("guard_work", "flexibility", "strength"), defense_skills=("top_control", "positional_ability"),
         preferred_styles=("BJJ", "Luta Livre"), tags=("ground", "defense", "guard")),
    move("underhook_stall", "deep underhook stall", "cling", GROUND_POSITIONS,
         attack_skills=("bottom_control", "strength", "scrambles"), defense_skills=("ride_control", "top_control"),
         preferred_styles=("Wrestler", "Sambo"), tags=("ground", "defense", "underhook")),
    move("head_pinch_stall", "head-pinch stall", "cling", GROUND_POSITIONS,
         attack_skills=("guard_work", "composure", "submission_defence_detail"), defense_skills=("ground_striking", "transitions"),
         preferred_styles=("BJJ", "Catch Wrestler"), tags=("ground", "defense", "smother")),

    move("knee_on_belly_pressure", "knee-on-belly pressure", "ground_control", frozenset({"side control", "half guard"}),
         attack_skills=("top_control", "positional_ability", "ride_control"), defense_skills=("bottom_control", "scrambles"),
         preferred_styles=("BJJ", "Wrestler"), minimum_skill=54, tags=("ground", "control", "pressure")),
    move("chest_to_chest_pin", "chest-to-chest pin", "ground_control", GROUND_POSITIONS,
         attack_skills=("top_control", "strength", "conditioning"), defense_skills=("bottom_control", "guard_work"),
         preferred_styles=("Wrestler", "Judo", "Sambo"), tags=("ground", "control", "pressure")),
    move("hip_pressure_ride", "hip-pressure ride", "ground_control", GROUND_POSITIONS,
         attack_skills=("ride_control", "top_control", "discipline"), defense_skills=("scrambles", "get_ups"),
         preferred_styles=("Catch Wrestler", "Freestyle Wrestler"), tags=("ground", "control", "ride")),

    move("frame_and_pivot_exit", "frame and pivot exit", "break_clinch", CLINCH_POSITIONS,
         attack_skills=("clinch_defence", "footwork", "mobility"), defense_skills=("clinch_control", "cage_wrestling"),
         preferred_styles=("Karate", "Kickboxer", "Boxer"), tags=("clinch", "escape", "footwork")),
    move("post_and_push_exit", "post and push off the fence", "break_clinch", CLINCH_POSITIONS,
         attack_skills=("strength", "clinch_defence", "conditioning"), defense_skills=("cage_wrestling", "clinch_control"),
         preferred_styles=("Wrestler", "Sanda"), tags=("clinch", "escape", "cage")),
    move("swim_to_space", "swim inside and cut the angle", "break_clinch", CLINCH_POSITIONS,
         attack_skills=("clinch_defence", "scrambles", "reflexes"), defense_skills=("clinch_control", "strength"),
         preferred_styles=("MMA Generalist", "Freestyle Wrestler"), minimum_skill=54, tags=("clinch", "escape", "pummel")),

    move("inside_uppercut", "short inside uppercut", "dirty_boxing", CLINCH_POSITIONS,
         attack_skills=("dirty_boxing", "punch_technique", "hand_speed"), defense_skills=("clinch_defence", "guard_defence"),
         preferred_styles=("Boxer", "Muay Thai"), tags=("strike", "punch", "clinch")),
    move("collar_tie_elbow", "collar-tie elbow", "dirty_boxing", CLINCH_POSITIONS,
         attack_skills=("elbows", "clinch_control", "punch_technique"), defense_skills=("clinch_defence", "guard_defence"),
         preferred_styles=("Muay Thai", "Sanda"), minimum_skill=55, tags=("strike", "elbow", "clinch")),
    move("inside_body_hook", "inside body hook", "dirty_boxing", CLINCH_POSITIONS, targets=frozenset({"body"}),
         attack_skills=("body_punching", "dirty_boxing", "strength"), defense_skills=("clinch_defence", "conditioning"),
         preferred_styles=("Boxer", "Catch Wrestler"), tags=("strike", "punch", "body", "clinch")),
    move("shoulder_grind", "shoulder grind on the fence", "dirty_boxing", CLINCH_POSITIONS,
         attack_skills=("cage_pressure", "strength", "dirty_boxing"), defense_skills=("clinch_defence", "composure"),
         preferred_styles=("Wrestler", "Sambo"), tags=("strike", "clinch", "cage")),

    move("flicker_jab", "flicker jab", "jab", STANDING_POSITIONS,
         attack_skills=("hand_speed", "punch_technique", "footwork"), defense_skills=("head_movement", "reflexes"),
         preferred_styles=("Boxer", "Karate"), energy=0.94, follow_ups=("one_two",), tags=("strike", "punch", "setup")),
    move("power_jab", "stiff power jab", "jab", STANDING_POSITIONS,
         attack_skills=("punch_power", "punch_technique", "strength"), defense_skills=("guard_defence", "head_movement"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), minimum_skill=54, energy=1.06, tags=("strike", "punch", "power")),
    move("up_jab", "up-jab from the low hand", "jab", STANDING_POSITIONS,
         attack_skills=("creative_punches", "punch_technique", "feints"), defense_skills=("head_movement", "guard_defence"),
         preferred_styles=("Karate", "MMA Generalist"), minimum_skill=55, counter_risk=1.06, tags=("strike", "punch", "setup")),

    # Actions the engine can already choose but that had no technique defined at
    # all, so every one of them fell through to the generic fallback.
    move("fence_drive", "drive to the fence", "force_cage", CLINCH_POSITIONS,
         attack_skills=("cage_wrestling", "clinch_control", "strength"), defense_skills=("clinch_defence", "footwork"),
         preferred_styles=("Wrestler", "Sambo", "Judo"), tags=("clinch", "cage", "control")),
    move("front_headlock_posture_out", "posture out of the front headlock", "front_headlock_escape",
         frozenset({"front headlock", "turtle"}),
         attack_skills=("submission_defence_detail", "scrambles", "guard_work"), defense_skills=("ride_control", "top_control"),
         preferred_styles=("Wrestler", "Freestyle Wrestler"), tags=("escape", "scramble")),
)

MOVE_REGISTRY = {definition.move_id: definition for definition in MOVE_DEFINITIONS}
KNOWN_PARENT_ACTIONS = frozenset(definition.parent_action for definition in MOVE_DEFINITIONS)
KNOWN_SKILLS = frozenset(key for group in DETAILED_SKILL_GROUPS.values() for key in group)


def validate_move_registry():
    issues = []
    if len(MOVE_REGISTRY) != len(MOVE_DEFINITIONS):
        issues.append("Move IDs must be unique")
    for definition in MOVE_DEFINITIONS:
        if not definition.positions or not definition.positions <= ALL_POSITIONS:
            issues.append(f"{definition.move_id}: contains no positions or an unknown position")
        unknown_skills = set(definition.attack_skills + definition.defense_skills) - KNOWN_SKILLS
        if unknown_skills:
            issues.append(f"{definition.move_id}: unknown skills {', '.join(sorted(unknown_skills))}")
        unknown_styles = set(definition.preferred_styles) - set(STYLES)
        if unknown_styles:
            issues.append(f"{definition.move_id}: unknown styles {', '.join(sorted(unknown_styles))}")
        unknown_followups = set(definition.follow_ups) - set(MOVE_REGISTRY)
        if unknown_followups:
            issues.append(f"{definition.move_id}: unknown follow-ups {', '.join(sorted(unknown_followups))}")
        if definition.minimum_skill < 0 or definition.minimum_skill > 99:
            issues.append(f"{definition.move_id}: minimum skill must be 0-99")
        if min(definition.energy, definition.miss_risk, definition.counter_risk) <= 0:
            issues.append(f"{definition.move_id}: risk and energy values must be positive")
        if "kick" in definition.tags:
            if not definition.targets or not definition.side or not definition.range_band or not definition.defense_families:
                issues.append(f"{definition.move_id}: kick moves require target, side, range, and defense families")
        if "takedown" in definition.tags:
            if not definition.entry_family or not definition.finish_positions or not definition.defense_families:
                issues.append(f"{definition.move_id}: takedowns require entry, finish positions, and defense families")
        if "submission" in definition.tags:
            if not definition.attack_path or not definition.failure_outcomes:
                issues.append(f"{definition.move_id}: submissions require an attack path and explicit failure outcomes")
        if "finisher" in definition.tags:
            if not set(definition.positions) <= STANDING_POSITIONS or "strike" not in definition.tags:
                issues.append(f"{definition.move_id}: authored finishers must be standing strikes")
            if definition.minimum_skill < 60 or definition.energy <= 1 or definition.counter_risk <= 1:
                issues.append(f"{definition.move_id}: authored finishers must be skill-gated and carry explicit risk")
        if "style-combination" in definition.tags:
            if len(definition.preferred_styles) != 1:
                issues.append(f"{definition.move_id}: style combinations require exactly one owning style")
            if len(definition.components) < 3:
                issues.append(f"{definition.move_id}: style combinations require at least three ordered components")
        if "style-finisher" in definition.tags:
            if len(definition.preferred_styles) != 1:
                issues.append(f"{definition.move_id}: style finishers require exactly one owning style")
            if not set(definition.tags).intersection({"strike", "submission"}):
                issues.append(f"{definition.move_id}: style finishers must be a strike or submission")
    return issues


MOVE_REGISTRY_ERRORS = tuple(validate_move_registry())
if MOVE_REGISTRY_ERRORS:
    raise ValueError("Invalid MMA move registry: " + "; ".join(MOVE_REGISTRY_ERRORS))


def legal_moves(parent_action, position, target=""):
    result = []
    for definition in MOVE_DEFINITIONS:
        if definition.parent_action != parent_action or position not in definition.positions:
            continue
        if definition.targets and target and target not in definition.targets:
            continue
        if definition.targets and not target:
            continue
        result.append(definition)
    return tuple(result)


def normalize_signature_moves(values, limit=3):
    """Return unique, stable registry IDs while ignoring unknown future moves."""
    if not isinstance(values, (list, tuple)):
        return []
    result = []
    for value in values:
        move_id = str(value or "").strip()
        if move_id in MOVE_REGISTRY and move_id not in result:
            result.append(move_id)
        if len(result) >= max(0, int(limit)):
            break
    return result


def normalize_move_mastery(values):
    """Normalize save-compatible offensive and defensive mastery ratings."""
    if not isinstance(values, dict):
        return {}
    result = {}
    for raw_key, raw_value in values.items():
        key = str(raw_key or "")
        known = key in MOVE_REGISTRY or (key.startswith("defense:") and key[8:] in DEFENSE_REGISTRY)
        if not known:
            continue
        try:
            value = int(round(float(raw_value)))
        except (TypeError, ValueError):
            continue
        result[key] = max(0, min(100, value))
    return result
