"""Hand-authored portrait deltas. Keys deliberately match display names."""

# Tier 1 icons have extra silhouette and facial-shape direction.  They remain
# stylised art-direction cues, not ratings, simulation inputs, or claims to
# photorealistic likeness.
PORTRAIT_ICON_OVERRIDES = {
    "Sean O'Malley": {"skin": 0, "hair_style": 23, "dye": "rainbow", "facial_hair": 10, "jaw": 1, "chin": 1, "cheek": 2, "nose": 0, "bg": 4},
    "Conor McGregor": {"skin": 1, "hair_style": 6, "facial_hair": 11, "jaw": 3, "bg": 2},
    "Jon Jones": {"skin": 5, "hair_style": 0, "facial_hair": 9, "jaw": 3, "bg": 0},
    "Israel Adesanya": {"skin": 5, "hair_style": 4, "facial_hair": 5, "jaw": 2, "bg": 9},
    "Khabib Nurmagomedov": {"skin": 2, "hair_style": 3, "facial_hair": 11, "jaw": 3, "bg": 5},
    "Amanda Nunes": {"skin": 3, "hair_style": 16, "facial_hair": 0, "jaw": 3, "bg": 7},
    "Valentina Shevchenko": {"skin": 1, "hair_style": 25, "facial_hair": 0, "bg": 1},
    "Alex Pereira": {"skin": 3, "hair_style": 1, "facial_hair": 9, "jaw": 4, "bg": 3},
    "Max Holloway": {"skin": 3, "hair_style": 4, "facial_hair": 9, "bg": 8},
    "Dustin Poirier": {"skin": 1, "hair_style": 1, "facial_hair": 10, "jaw": 3, "bg": 2},
    "Charles Oliveira": {"skin": 2, "hair_style": 4, "facial_hair": 9, "bg": 3},
    "Justin Gaethje": {"skin": 1, "hair_style": 1, "facial_hair": 1, "bg": 5},
    "Islam Makhachev": {"skin": 2, "hair_style": 2, "facial_hair": 10, "jaw": 3, "bg": 0},
    "Leon Edwards": {"skin": 5, "hair_style": 1, "facial_hair": 9, "bg": 1},
    "Kamaru Usman": {"skin": 6, "hair_style": 1, "facial_hair": 9, "jaw": 4, "bg": 6},
    "Robert Whittaker": {"skin": 2, "hair_style": 3, "facial_hair": 9, "bg": 8},
    "Francis Ngannou": {"skin": 6, "hair_style": 0, "facial_hair": 9, "jaw": 4, "bg": 2},
    "Stipe Miocic": {"skin": 1, "hair_style": 2, "facial_hair": 1, "jaw": 3, "bg": 0},
    "Daniel Cormier": {"skin": 5, "hair_style": 0, "facial_hair": 10, "jaw": 4, "bg": 4},
    "Georges St-Pierre": {"skin": 1, "hair_style": 0, "facial_hair": 0, "jaw": 3, "bg": 1},
    "Anderson Silva": {"skin": 5, "hair_style": 0, "facial_hair": 1, "jaw": 3, "bg": 9},
    "Demetrious Johnson": {"skin": 4, "hair_style": 1, "facial_hair": 9, "bg": 6},
    "Fedor Emelianenko": {"skin": 1, "hair_style": 0, "facial_hair": 0, "jaw": 4, "bg": 5},
    "Ronda Rousey": {"skin": 1, "hair_style": 20, "facial_hair": 0, "jaw": 3, "bg": 2},
    "Cris Cyborg": {"skin": 2, "hair_style": 17, "facial_hair": 0, "jaw": 3, "bg": 7},
    "Zhang Weili": {"skin": 2, "hair_style": 24, "facial_hair": 0, "bg": 3},
    "Rose Namajunas": {"skin": 1, "hair_style": 0, "facial_hair": 0, "bg": 4},
    "Joanna Jedrzejczyk": {"skin": 1, "hair_style": 21, "facial_hair": 0, "bg": 1},
    "Holly Holm": {"skin": 1, "hair_style": 21, "facial_hair": 0, "bg": 8},
    "Jiri Prochazka": {"skin": 1, "hair_style": 19, "facial_hair": 9, "bg": 2},
    "Paddy Pimblett": {"skin": 1, "hair_colour": 5, "hair_style": 15, "facial_hair": 1, "bg": 3},
    "Ilia Topuria": {"skin": 2, "hair_style": 4, "facial_hair": 10, "jaw": 3, "bg": 7},
    "Merab Dvalishvili": {"skin": 2, "hair_style": 1, "facial_hair": 1, "bg": 0},
    "Aljamain Sterling": {"skin": 5, "hair_style": 27, "facial_hair": 9, "bg": 4},
    "Henry Cejudo": {"skin": 3, "hair_style": 2, "facial_hair": 9, "bg": 5},
    "Dominick Cruz": {"skin": 2, "hair_style": 1, "facial_hair": 1, "bg": 1},
    "Jose Aldo": {"skin": 3, "hair_style": 1, "facial_hair": 1, "bg": 2},
    "Marlon Vera": {"skin": 3, "hair_style": 25, "facial_hair": 10, "bg": 9},
    "Jorge Masvidal": {"skin": 3, "hair_style": 18, "facial_hair": 11, "bg": 7},
    "Nate Diaz": {"skin": 2, "hair_style": 3, "facial_hair": 1, "bg": 6},
    "Nick Diaz": {"skin": 2, "hair_style": 18, "facial_hair": 1, "bg": 6},
    "Tony Ferguson": {"skin": 2, "hair_style": 4, "facial_hair": 9, "bg": 0},
    "Michael Chandler": {"skin": 1, "hair_style": 0, "facial_hair": 9, "jaw": 4, "bg": 8},
    "Colby Covington": {"skin": 1, "hair_style": 2, "facial_hair": 1, "bg": 5},
    "Paulo Costa": {"skin": 3, "hair_style": 3, "facial_hair": 10, "jaw": 4, "bg": 2},
    "Dricus Du Plessis": {"skin": 1, "hair_style": 1, "facial_hair": 1, "bg": 3},
    "Sean Strickland": {"skin": 1, "hair_style": 3, "facial_hair": 1, "bg": 0},
    "Shavkat Rakhmonov": {"skin": 2, "hair_style": 2, "facial_hair": 9, "bg": 9},
    "Tom Aspinall": {"skin": 1, "hair_style": 0, "facial_hair": 9, "jaw": 3, "bg": 1},
    "Ciryl Gane": {"skin": 5, "hair_style": 1, "facial_hair": 9, "bg": 4},
    "Tai Tuivasa": {"skin": 4, "hair_style": 1, "facial_hair": 10, "jaw": 4, "bg": 7},
    "Glover Teixeira": {"skin": 3, "hair_style": 0, "facial_hair": 10, "bg": 3},
    "Vitor Belfort": {"skin": 2, "hair_style": 1, "facial_hair": 9, "bg": 5},
    "Rory MacDonald": {"skin": 1, "hair_style": 1, "facial_hair": 1, "bg": 1},
    "Eddie Alvarez": {"skin": 2, "hair_style": 1, "facial_hair": 9, "bg": 2},
}

# Tier 2 is intentionally limited to the most recognisable, durable cues.
# Leaving the rest of each vector derived keeps the set maintainable as hair
# changes over a career and avoids inventing detailed facial claims.
PORTRAIT_PARTIAL_OVERRIDES = {
    "Khamzat Chimaev": {"skin": 1, "hair_style": 3, "facial_hair": 10},
    "Wanderlei Silva": {"skin": 3, "hair_style": 0, "facial_hair": 1},
    "Alexander Volkanovski": {"skin": 1, "hair_style": 0, "facial_hair": 9},
    "Alexandre Pantoja": {"skin": 3, "hair_style": 1, "facial_hair": 9},
    "Brock Lesnar": {"skin": 1, "hair_style": 0, "facial_hair": 1},
    "Julianna Pena": {"skin": 2, "hair_style": 21, "facial_hair": 0},
    "Lyoto Machida": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Mirko Cro Cop": {"skin": 1, "hair_style": 2, "facial_hair": 1},
    "Kazushi Sakuraba": {"skin": 2, "hair_style": 15, "facial_hair": 1},
    "Mauricio Rua": {"skin": 2, "hair_style": 3, "facial_hair": 9},
    "Robbie Lawler": {"skin": 1, "hair_style": 0, "facial_hair": 1},
    "BJ Penn": {"skin": 2, "hair_style": 2, "facial_hair": 1},
    "Chuck Liddell": {"skin": 1, "hair_style": 0, "facial_hair": 3},
    "Demian Maia": {"skin": 2, "hair_style": 0, "facial_hair": 9},
    "Jake Paul": {"skin": 1, "hair_style": 9, "facial_hair": 1},
    "Kayla Harrison": {"skin": 1, "hair_style": 21, "facial_hair": 0},
    "Matt Hughes": {"skin": 1, "hair_style": 1, "facial_hair": 1},
    "Quinton Jackson": {"skin": 6, "hair_style": 0, "facial_hair": 9},
    "Raquel Pennington": {"skin": 1, "hair_style": 20, "facial_hair": 0},
    "Tatiana Suarez": {"skin": 2, "hair_style": 21, "facial_hair": 0},
    "Urijah Faber": {"skin": 1, "hair_style": 16, "facial_hair": 1},
    "Cristiane Justino": {"skin": 2, "hair_style": 17, "facial_hair": 0},
    "Petr Yan": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Usman Nurmagomedov": {"skin": 2, "hair_style": 3, "facial_hair": 9},
    "Virna Jandiroba": {"skin": 3, "hair_style": 21, "facial_hair": 0},
    "Corey Anderson": {"skin": 5, "hair_style": 1, "facial_hair": 9},
    "Gegard Mousasi": {"skin": 2, "hair_style": 0, "facial_hair": 9},
    "Gilbert Melendez": {"skin": 2, "hair_style": 1, "facial_hair": 1},
    "Gina Carano": {"skin": 1, "hair_style": 17, "facial_hair": 0},
    "Ian Machado Garry": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Jan Blachowicz": {"skin": 1, "hair_style": 0, "facial_hair": 9},
    "Kimbo Slice": {"skin": 6, "hair_style": 13, "facial_hair": 11},
    "Logan Paul": {"skin": 1, "hair_style": 9, "facial_hair": 1},
    "Magomed Ankalaev": {"skin": 2, "hair_style": 1, "facial_hair": 9},
    "Takanori Gomi": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Vadim Nemkov": {"skin": 1, "hair_style": 2, "facial_hair": 1},
    "Yan Xiaonan": {"skin": 2, "hair_style": 21, "facial_hair": 0},
    "Derrick Lewis": {"skin": 6, "hair_style": 0, "facial_hair": 9},
    "Jack Della Maddalena": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "AJ McKee": {"skin": 5, "hair_style": 11, "facial_hair": 9},
    "Ailin Perez": {"skin": 2, "hair_style": 18, "facial_hair": 0},
    "Arman Tsarukyan": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Belal Muhammad": {"skin": 3, "hair_style": 1, "facial_hair": 9},
    "Cain Velasquez": {"skin": 2, "hair_style": 0, "facial_hair": 9},
    "Dan Henderson": {"skin": 1, "hair_style": 1, "facial_hair": 1},
    "Igor Vovchanchyn": {"skin": 1, "hair_style": 1, "facial_hair": 1},
    "Khalil Rountree Jr.": {"skin": 5, "hair_style": 1, "facial_hair": 9},
    "Kyoji Horiguchi": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Michael Venom Page": {"skin": 5, "hair_style": 1, "facial_hair": 9},
    "Paul Daley": {"skin": 5, "hair_style": 1, "facial_hair": 9},
    "Rodtang Jitmuangnon": {"skin": 3, "hair_style": 3, "facial_hair": 1},
    "Royce Gracie": {"skin": 1, "hair_style": 18, "facial_hair": 1},
    "Ryan Garcia": {"skin": 2, "hair_style": 9, "facial_hair": 1},
    "Tenshin Nasukawa": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Yair Rodriguez": {"skin": 2, "hair_style": 18, "facial_hair": 1},
    "Alexander Volkov": {"skin": 1, "hair_style": 3, "facial_hair": 9},
    "Cung Le": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Kevin Randleman": {"skin": 6, "hair_style": 0, "facial_hair": 9},
    "Cory Sandhagen": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Diego Lopes": {"skin": 2, "hair_style": 18, "facial_hair": 9},
    "Don Frye": {"skin": 1, "hair_style": 1, "facial_hair": 4},
    "Donald Cerrone": {"skin": 1, "hair_style": 18, "facial_hair": 1},
    "Douglas Lima": {"skin": 3, "hair_style": 1, "facial_hair": 9},
    "Kevin Holland": {"skin": 5, "hair_style": 1, "facial_hair": 9},
    "Larissa Pacheco": {"skin": 3, "hair_style": 21, "facial_hair": 0},
    "Loopy Godinez": {"skin": 2, "hair_style": 21, "facial_hair": 0},
    "Mark Hunt": {"skin": 3, "hair_style": 0, "facial_hair": 9},
    "Randy Couture": {"skin": 1, "hair_style": 0, "facial_hair": 1},
    "Sergei Pavlovich": {"skin": 1, "hair_style": 0, "facial_hair": 1},
    "Mackenzie Dern": {"skin": 1, "hair_style": 21, "facial_hair": 0},
    "Mark Kerr": {"skin": 1, "hair_style": 0, "facial_hair": 9},
    "Umar Nurmagomedov": {"skin": 2, "hair_style": 3, "facial_hair": 9},
    "Alistair Overeem": {"skin": 3, "hair_style": 0, "facial_hair": 9},
    "Amanda Lemos": {"skin": 3, "hair_style": 17, "facial_hair": 0},
    "Anatoly Malykhin": {"skin": 1, "hair_style": 0, "facial_hair": 9},
    "Arnold Allen": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Brandon Royval": {"skin": 2, "hair_style": 3, "facial_hair": 9},
    "Carlos Prates": {"skin": 3, "hair_style": 18, "facial_hair": 9},
    "Curtis Blaydes": {"skin": 6, "hair_style": 1, "facial_hair": 9},
    "Dan Hardy": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Denis Goltsov": {"skin": 1, "hair_style": 3, "facial_hair": 9},
    "Gilbert Burns": {"skin": 3, "hair_style": 1, "facial_hair": 9},
    "Irene Aldana": {"skin": 2, "hair_style": 18, "facial_hair": 0},
    "Jake Shields": {"skin": 1, "hair_style": 0, "facial_hair": 9},
    "Jamahal Hill": {"skin": 5, "hair_style": 1, "facial_hair": 9},
    "Ken Shamrock": {"skin": 1, "hair_style": 0, "facial_hair": 1},
    "Mamed Khalidov": {"skin": 2, "hair_style": 3, "facial_hair": 9},
    "Mike Perry": {"skin": 1, "hair_style": 3, "facial_hair": 9},
    "Rickson Gracie": {"skin": 2, "hair_style": 18, "facial_hair": 1},
    "Stamp Fairtex": {"skin": 3, "hair_style": 21, "facial_hair": 0},
    "Tito Ortiz": {"skin": 1, "hair_style": 0, "facial_hair": 1},
    "Yoel Romero": {"skin": 5, "hair_style": 0, "facial_hair": 9},
    "Angela Lee": {"skin": 2, "hair_style": 18, "facial_hair": 0},
    "Bas Rutten": {"skin": 1, "hair_style": 0, "facial_hair": 1},
    "Genki Sudo": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Jens Pulver": {"skin": 1, "hair_style": 0, "facial_hair": 1},
    "Manel Kape": {"skin": 5, "hair_style": 1, "facial_hair": 9},
    "Mark Coleman": {"skin": 1, "hair_style": 0, "facial_hair": 1},
    "Mateusz Gamrot": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Nassourdine Imavov": {"skin": 3, "hair_style": 3, "facial_hair": 9},
    "Reinier de Ridder": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Ricardo Arona": {"skin": 2, "hair_style": 0, "facial_hair": 9},
    "Shinya Aoki": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Song Yadong": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Stephen Thompson": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Superlek Kiatmoo9": {"skin": 3, "hair_style": 3, "facial_hair": 1},
    "Tabatha Ricci": {"skin": 2, "hair_style": 21, "facial_hair": 0},
    "Dakota Ditcheva": {"skin": 1, "hair_style": 18, "facial_hair": 0},
    "Gary Goodridge": {"skin": 5, "hair_style": 0, "facial_hair": 9},
    "Johnny Eblen": {"skin": 2, "hair_style": 3, "facial_hair": 9},
    "Marvin Vettori": {"skin": 1, "hair_style": 3, "facial_hair": 9},
    "Anthony Pettis": {"skin": 2, "hair_style": 3, "facial_hair": 9},
    "Brandon Moreno": {"skin": 2, "hair_style": 3, "facial_hair": 9},
    "Caio Borralho": {"skin": 3, "hair_style": 3, "facial_hair": 9},
    "Christian Lee": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Dan Hooker": {"skin": 1, "hair_style": 3, "facial_hair": 9},
    "Deiveson Figueiredo": {"skin": 3, "hair_style": 0, "facial_hair": 9},
    "Frank Shamrock": {"skin": 1, "hair_style": 1, "facial_hair": 1},
    "Hidehiko Yoshida": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Jessica Andrade": {"skin": 3, "hair_style": 21, "facial_hair": 0},
    "Liz Carmouche": {"skin": 2, "hair_style": 1, "facial_hair": 0},
    "Mariusz Pudzianowski": {"skin": 1, "hair_style": 0, "facial_hair": 1},
    "Michael Bisping": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Mikuru Asakura": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Nong-O Hama": {"skin": 3, "hair_style": 3, "facial_hair": 1},
    "Paul Hughes": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Vicente Luque": {"skin": 3, "hair_style": 3, "facial_hair": 9},
    "Hayato Sakurai": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Jailton Almeida": {"skin": 5, "hair_style": 1, "facial_hair": 9},
    "Jonathan Haggerty": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "King Green": {"skin": 5, "hair_style": 1, "facial_hair": 9},
    "Aaron Pico": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Ben Askren": {"skin": 1, "hair_style": 0, "facial_hair": 9},
    "Benson Henderson": {"skin": 3, "hair_style": 1, "facial_hair": 9},
    "Brian Ortega": {"skin": 2, "hair_style": 18, "facial_hair": 9},
    "Carlos Condit": {"skin": 1, "hair_style": 18, "facial_hair": 1},
    "Chael Sonnen": {"skin": 1, "hair_style": 0, "facial_hair": 1},
    "Dominick Reyes": {"skin": 2, "hair_style": 1, "facial_hair": 9},
    "Geoff Neal": {"skin": 5, "hair_style": 1, "facial_hair": 9},
    "Jared Cannonier": {"skin": 5, "hair_style": 0, "facial_hair": 9},
    "Junior Dos Santos": {"skin": 3, "hair_style": 0, "facial_hair": 9},
    "Kai Kara-France": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Rafael Fiziev": {"skin": 2, "hair_style": 3, "facial_hair": 9},
    "Rashad Evans": {"skin": 5, "hair_style": 0, "facial_hair": 9},
    "Rich Franklin": {"skin": 1, "hair_style": 0, "facial_hair": 1},
    "Yaroslav Amosov": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Angela Hill": {"skin": 5, "hair_style": 1, "facial_hair": 0},
    "Anthony Johnson": {"skin": 5, "hair_style": 0, "facial_hair": 9},
    "Chan Sung Jung": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Forrest Griffin": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Johnny Walker": {"skin": 3, "hair_style": 18, "facial_hair": 9},
    "Josh Emmett": {"skin": 1, "hair_style": 0, "facial_hair": 9},
    "Aiemann Zahabi": {"skin": 2, "hair_style": 3, "facial_hair": 9},
    "Anthony Hernandez": {"skin": 2, "hair_style": 3, "facial_hair": 9},
    "Dovletdzhan Yagshimuradov": {"skin": 2, "hair_style": 3, "facial_hair": 9},
    "Heath Herring": {"skin": 1, "hair_style": 0, "facial_hair": 1},
    "Macy Chiasson": {"skin": 1, "hair_style": 21, "facial_hair": 0},
    "Paulina Wisniewska": {"skin": 1, "hair_style": 21, "facial_hair": 0},
    "Raufeon Stots": {"skin": 5, "hair_style": 1, "facial_hair": 9},
    "Robert Wilkinson": {"skin": 1, "hair_style": 3, "facial_hair": 9},
    "Tyrell Fortune": {"skin": 5, "hair_style": 1, "facial_hair": 9},
    "Aaron Jeffrey": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Ante Delija": {"skin": 1, "hair_style": 0, "facial_hair": 9},
    "Benoit Saint Denis": {"skin": 1, "hair_style": 3, "facial_hair": 9},
    "Bobby Lashley": {"skin": 5, "hair_style": 0, "facial_hair": 9},
    "Calvin Kattar": {"skin": 1, "hair_style": 3, "facial_hair": 9},
    "Darren Till": {"skin": 1, "hair_style": 0, "facial_hair": 9},
    "Joaquin Buckley": {"skin": 5, "hair_style": 1, "facial_hair": 9},
    "John Lineker": {"skin": 3, "hair_style": 1, "facial_hair": 9},
    "Joseph Benavidez": {"skin": 2, "hair_style": 1, "facial_hair": 9},
    "Kai Asakura": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Kiyoshi Tamura": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Marloes Coenen": {"skin": 1, "hair_style": 21, "facial_hair": 0},
    "Michel Pereira": {"skin": 3, "hair_style": 3, "facial_hair": 9},
    "Renato Moicano": {"skin": 3, "hair_style": 18, "facial_hair": 9},
    "Roberto Soldic": {"skin": 1, "hair_style": 3, "facial_hair": 9},
    "Ross Pearson": {"skin": 1, "hair_style": 3, "facial_hair": 9},
    "Salahdine Parnasse": {"skin": 3, "hair_style": 3, "facial_hair": 9},
    "Sean Brady": {"skin": 1, "hair_style": 0, "facial_hair": 9},
    "Sergio Pettis": {"skin": 2, "hair_style": 3, "facial_hair": 9},
    "Steve Erceg": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Tatsuro Taira": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Brian Bowles": {"skin": 1, "hair_style": 0, "facial_hair": 9},
    "Scott Smith": {"skin": 1, "hair_style": 1, "facial_hair": 1},
    "Adriano Moraes": {"skin": 3, "hair_style": 3, "facial_hair": 9},
    "Akihiro Gono": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Alexei Pergande": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Bia Mesquita": {"skin": 3, "hair_style": 21, "facial_hair": 0},
    "Bryan Battle": {"skin": 5, "hair_style": 1, "facial_hair": 9},
    "Clay Collard": {"skin": 1, "hair_style": 3, "facial_hair": 9},
    "Jeremy Stephens": {"skin": 1, "hair_style": 0, "facial_hair": 9},
    "Miesha Tate BAMMA": {"skin": 1, "hair_style": 21, "facial_hair": 0},
    "Luke Rockhold BAMMA": {"skin": 1, "hair_style": 3, "facial_hair": 9},
    "Patricio Pitbull BAMMA": {"skin": 3, "hair_style": 3, "facial_hair": 9},
    "Paulo Filho WEC": {"skin": 3, "hair_style": 0, "facial_hair": 9},
    "Regian Eersel": {"skin": 5, "hair_style": 1, "facial_hair": 9},
    "Amanda Ribas": {"skin": 2, "hair_style": 21, "facial_hair": 0},
    "Fatima Kline": {"skin": 1, "hair_style": 21, "facial_hair": 0},
    "Gillian Robertson": {"skin": 1, "hair_style": 21, "facial_hair": 0},
    "Neil Magny": {"skin": 5, "hair_style": 1, "facial_hair": 9},
    "Taila Santos": {"skin": 3, "hair_style": 21, "facial_hair": 0},
}

# Exact visual directions for the 50 highest-rated shipped fighters.  This is
# a deliberately explicit audit set: historical/Legend entries are separate
# records and must not silently fall back to a randomised portrait.
PORTRAIT_TOP_RATED_OVERRIDES = {
    "Islam Makhachev": {"skin": 2, "hair_style": 3, "facial_hair": 10},
    "Alexander Volkanovski": {"skin": 1, "hair_style": 0, "facial_hair": 9},
    "Demetrious Johnson": {"skin": 4, "hair_style": 4, "facial_hair": 9},
    "Demetrious Johnson Legend": {"skin": 4, "hair_style": 4, "facial_hair": 9},
    "Jon Jones": {"skin": 5, "hair_style": 0, "facial_hair": 9},
    "Fedor Emelianenko": {"skin": 1, "hair_style": 31, "facial_hair": 0},
    "Fedor Emelianenko Legend": {"skin": 1, "hair_style": 31, "facial_hair": 0},
    "Georges St-Pierre": {"skin": 1, "hair_style": 0, "facial_hair": 0},
    "Khabib Nurmagomedov": {"skin": 2, "hair_style": 14, "facial_hair": 11},
    "Usman Nurmagomedov": {"skin": 2, "hair_style": 3, "facial_hair": 9},
    "Amanda Nunes": {"skin": 3, "hair_style": 17, "facial_hair": 0},
    "Ilia Topuria": {"skin": 2, "hair_style": 4, "facial_hair": 10},
    "Tom Aspinall": {"skin": 1, "hair_style": 1, "facial_hair": 9},
    "Daniel Cormier": {"skin": 5, "hair_style": 0, "facial_hair": 10},
    "Daniel Cormier Legend": {"skin": 5, "hair_style": 0, "facial_hair": 10},
    "Dricus Du Plessis": {"skin": 1, "hair_style": 1, "facial_hair": 1},
    "Khamzat Chimaev": {"skin": 1, "hair_style": 3, "facial_hair": 10},
    "Magomed Ankalaev": {"skin": 2, "hair_style": 1, "facial_hair": 9},
    "Shavkat Rakhmonov": {"skin": 2, "hair_style": 2, "facial_hair": 9},
    "Umar Nurmagomedov": {"skin": 2, "hair_style": 3, "facial_hair": 9},
    "Anderson Silva": {"skin": 5, "hair_style": 0, "facial_hair": 1},
    "Arman Tsarukyan": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Cain Velasquez": {"skin": 2, "hair_style": 0, "facial_hair": 9},
    "Conor McGregor": {"skin": 1, "hair_style": 6, "facial_hair": 11},
    "Demetrious Johnson ONE": {"skin": 4, "hair_style": 4, "facial_hair": 9},
    "Frankie Edgar FA": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Frankie Edgar Legend": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Kayla Harrison": {"skin": 1, "hair_colour": 5, "hair_style": 21, "facial_hair": 0},
    "Merab Dvalishvili": {"skin": 2, "hair_style": 1, "facial_hair": 1},
    "Raquel Pennington": {"skin": 1, "hair_style": 18, "facial_hair": 0},
    "Tatiana Suarez": {"skin": 2, "hair_style": 21, "facial_hair": 0},
    "Vadim Nemkov": {"skin": 1, "hair_style": 2, "facial_hair": 1},
    "Alex Pereira": {"skin": 3, "hair_style": 4, "facial_hair": 9},
    "Gegard Mousasi": {"skin": 2, "hair_style": 0, "facial_hair": 9},
    "Jose Aldo": {"skin": 3, "hair_style": 1, "facial_hair": 1},
    "Jose Aldo Legend": {"skin": 3, "hair_style": 1, "facial_hair": 1},
    "Julianna Pena": {"skin": 2, "hair_style": 21, "facial_hair": 0},
    "Justin Gaethje": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Valentina Shevchenko": {"skin": 1, "hair_style": 25, "facial_hair": 0},
    "Zhang Weili": {"skin": 2, "hair_style": 24, "facial_hair": 0},
    "Alexandre Pantoja": {"skin": 3, "hair_style": 4, "facial_hair": 9},
    "Anatoly Malykhin": {"skin": 1, "hair_style": 0, "facial_hair": 9},
    "Kazushi Sakuraba": {"skin": 2, "hair_colour": 5, "hair_style": 14, "dye": "bleach", "facial_hair": 1},
    "BJ Penn": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Charles Oliveira": {"skin": 2, "hair_style": 4, "facial_hair": 9},
    "Demian Maia": {"skin": 2, "hair_style": 0, "facial_hair": 9},
    "Jack Della Maddalena": {"skin": 1, "hair_style": 3, "facial_hair": 1},
    "Joanna Jedrzejczyk": {"skin": 1, "hair_colour": 5, "hair_style": 21, "facial_hair": 0},
    "Lyoto Machida": {"skin": 2, "hair_style": 3, "facial_hair": 1},
    "Matt Hughes": {"skin": 1, "hair_style": 3, "facial_hair": 1},
}

# Public merged map kept name-keyed for the save/database validation contract.
if set(PORTRAIT_ICON_OVERRIDES) & set(PORTRAIT_PARTIAL_OVERRIDES):
    raise ValueError("portrait icon and partial override keys must be disjoint")
PORTRAIT_OVERRIDES = {name: dict(vector) for name, vector in
                      {**PORTRAIT_ICON_OVERRIDES, **PORTRAIT_PARTIAL_OVERRIDES}.items()}
for _name, _vector in PORTRAIT_TOP_RATED_OVERRIDES.items():
    # A hair correction must not discard an icon's authored jaw/chin/cheeks.
    PORTRAIT_OVERRIDES.setdefault(_name, {}).update(_vector)
