"""Hand-authored portrait deltas. Keys deliberately match display names."""

# Tier 1: partial vectors leave every unmentioned trait deterministic.  These
# are stylised art-direction cues, not ratings, simulation inputs, or claims to
# photorealistic likeness.
PORTRAIT_OVERRIDES = {
    "Sean O'Malley": {"skin": 0, "hair_style": 23, "dye": "rainbow", "facial_hair": 10, "jaw": 1, "chin": 1, "cheek": 2, "nose": 0, "bg": 4},
    "Conor McGregor": {"skin": 1, "hair_style": 6, "facial_hair": 11, "jaw": 3, "bg": 2},
    "Jon Jones": {"skin": 5, "hair_style": 0, "facial_hair": 9, "jaw": 3, "bg": 0},
    "Israel Adesanya": {"skin": 5, "hair_style": 4, "facial_hair": 5, "jaw": 2, "bg": 9},
    "Khabib Nurmagomedov": {"skin": 2, "hair_style": 3, "facial_hair": 11, "jaw": 3, "bg": 5},
    "Amanda Nunes": {"skin": 3, "hair_style": 16, "facial_hair": 0, "jaw": 3, "bg": 7},
    "Valentina Shevchenko": {"skin": 1, "hair_style": 25, "facial_hair": 0, "bg": 1},
    "Alex Pereira": {"skin": 3, "hair_style": 1, "facial_hair": 9, "jaw": 4, "bg": 3},
    "Max Holloway": {"skin": 3, "hair_style": 4, "facial_hair": 9, "bg": 8},
    "Dustin Poirier": {"skin": 1, "hair_style": 1, "facial_hair": 10, "jaw": 3, "bg": 2},
    "Charles Oliveira": {"skin": 2, "hair_style": 4, "facial_hair": 9, "bg": 3},
    "Justin Gaethje": {"skin": 1, "hair_style": 1, "facial_hair": 1, "bg": 5},
    "Islam Makhachev": {"skin": 2, "hair_style": 2, "facial_hair": 10, "jaw": 3, "bg": 0},
    "Leon Edwards": {"skin": 5, "hair_style": 1, "facial_hair": 9, "bg": 1},
    "Kamaru Usman": {"skin": 6, "hair_style": 1, "facial_hair": 9, "jaw": 4, "bg": 6},
    "Robert Whittaker": {"skin": 2, "hair_style": 3, "facial_hair": 9, "bg": 8},
    "Francis Ngannou": {"skin": 6, "hair_style": 0, "facial_hair": 9, "jaw": 4, "bg": 2},
    "Stipe Miocic": {"skin": 1, "hair_style": 2, "facial_hair": 1, "jaw": 3, "bg": 0},
    "Daniel Cormier": {"skin": 5, "hair_style": 0, "facial_hair": 10, "jaw": 4, "bg": 4},
    "Georges St-Pierre": {"skin": 1, "hair_style": 0, "facial_hair": 0, "jaw": 3, "bg": 1},
    "Anderson Silva": {"skin": 5, "hair_style": 0, "facial_hair": 1, "jaw": 3, "bg": 9},
    "Demetrious Johnson": {"skin": 4, "hair_style": 1, "facial_hair": 9, "bg": 6},
    "Fedor Emelianenko": {"skin": 1, "hair_style": 0, "facial_hair": 0, "jaw": 4, "bg": 5},
    "Ronda Rousey": {"skin": 1, "hair_style": 20, "facial_hair": 0, "jaw": 3, "bg": 2},
    "Cris Cyborg": {"skin": 2, "hair_style": 17, "facial_hair": 0, "jaw": 3, "bg": 7},
    "Zhang Weili": {"skin": 2, "hair_style": 24, "facial_hair": 0, "bg": 3},
    "Rose Namajunas": {"skin": 1, "hair_style": 0, "facial_hair": 0, "bg": 4},
    "Joanna Jedrzejczyk": {"skin": 1, "hair_style": 21, "facial_hair": 0, "bg": 1},
    "Holly Holm": {"skin": 1, "hair_style": 21, "facial_hair": 0, "bg": 8},
    "Jiri Prochazka": {"skin": 1, "hair_style": 19, "facial_hair": 9, "bg": 2},
    "Paddy Pimblett": {"skin": 1, "hair_style": 15, "facial_hair": 1, "bg": 3},
    "Ilia Topuria": {"skin": 2, "hair_style": 4, "facial_hair": 10, "jaw": 3, "bg": 7},
    "Merab Dvalishvili": {"skin": 2, "hair_style": 1, "facial_hair": 1, "bg": 0},
    "Aljamain Sterling": {"skin": 5, "hair_style": 27, "facial_hair": 9, "bg": 4},
    "Henry Cejudo": {"skin": 3, "hair_style": 2, "facial_hair": 9, "bg": 5},
    "Dominick Cruz": {"skin": 2, "hair_style": 1, "facial_hair": 1, "bg": 1},
    "Jose Aldo": {"skin": 3, "hair_style": 1, "facial_hair": 1, "bg": 2},
    "Marlon Vera": {"skin": 3, "hair_style": 25, "facial_hair": 10, "bg": 9},
    "Jorge Masvidal": {"skin": 3, "hair_style": 18, "facial_hair": 11, "bg": 7},
    "Nate Diaz": {"skin": 2, "hair_style": 3, "facial_hair": 1, "bg": 6},
    "Nick Diaz": {"skin": 2, "hair_style": 18, "facial_hair": 1, "bg": 6},
    "Tony Ferguson": {"skin": 2, "hair_style": 4, "facial_hair": 9, "bg": 0},
    "Michael Chandler": {"skin": 1, "hair_style": 0, "facial_hair": 9, "jaw": 4, "bg": 8},
    "Colby Covington": {"skin": 1, "hair_style": 2, "facial_hair": 1, "bg": 5},
    "Paulo Costa": {"skin": 3, "hair_style": 3, "facial_hair": 10, "jaw": 4, "bg": 2},
    "Dricus Du Plessis": {"skin": 1, "hair_style": 1, "facial_hair": 1, "bg": 3},
    "Sean Strickland": {"skin": 1, "hair_style": 3, "facial_hair": 1, "bg": 0},
    "Shavkat Rakhmonov": {"skin": 2, "hair_style": 2, "facial_hair": 9, "bg": 9},
    "Tom Aspinall": {"skin": 1, "hair_style": 0, "facial_hair": 9, "jaw": 3, "bg": 1},
    "Ciryl Gane": {"skin": 5, "hair_style": 1, "facial_hair": 9, "bg": 4},
    "Tai Tuivasa": {"skin": 4, "hair_style": 1, "facial_hair": 10, "jaw": 4, "bg": 7},
    "Glover Teixeira": {"skin": 3, "hair_style": 0, "facial_hair": 10, "bg": 3},
    "Vitor Belfort": {"skin": 2, "hair_style": 1, "facial_hair": 9, "bg": 5},
    "Rory MacDonald": {"skin": 1, "hair_style": 1, "facial_hair": 1, "bg": 1},
    "Eddie Alvarez": {"skin": 2, "hair_style": 1, "facial_hair": 9, "bg": 2},
}
