"""Photo-reviewed cosmetic directions for rating positions 51--100 (2026-09-07).

Sources and limits: docs/FIGHTER_PORTRAIT_TOP_100_REVIEW.md. The catalogue IDs
remain append-only. No database, rating, RNG or simulation data is changed here.
Matthew Green's separate user-directed partial override lives in overrides.py.
"""


def _look(skin, hair_style, hair_colour, facial_hair, *, jaw=2, chin=0,
          cheek=1, face_length=1, head_w=50, brow=0, eye_shape=0,
          eye_size=1, eye_spacing=1, nose=0, nose_length=4, mouth=0,
          lip_fullness=4, ear=1, iris_colour=0, neck_width=4,
          shoulder_width=4, hair_volume=4, hair_part=4, beard_colour=None,
          dye=""):
    """Author every facial control; retain the fighter's existing background."""
    return dict(skin=skin, hair_style=hair_style, hair_colour=hair_colour,
                facial_hair=facial_hair, jaw=jaw, chin=chin, cheek=cheek,
                face_length=face_length, head_w=head_w, brow=brow,
                eye_shape=eye_shape, eye_size=eye_size, eye_spacing=eye_spacing,
                nose=nose, nose_length=nose_length, mouth=mouth,
                lip_fullness=lip_fullness, ear=ear, iris_colour=iris_colour,
                neck_width=neck_width, shoulder_width=shoulder_width,
                hair_volume=hair_volume, hair_part=hair_part, complexion=0,
                feature_offset=4, dye=dye,
                beard_colour=hair_colour if beard_colour is None else beard_colour)


# Explicitly cosmetic correction for a mislabelled historical database row.
# Never use this set for division eligibility or mutate fighter.gender from it.
FEMALE_PRESENTATION_NAMES = frozenset({"Cristiane Justino"})

PORTRAIT_RANK_51_100_OVERRIDES = {
    "Max Holloway": _look(2, 1, 0, 1, jaw=7, chin=1, cheek=5, face_length=2,
                         brow=3, nose=8, nose_length=6, mouth=2, ear=2),
    "Mirko Cro Cop": _look(1, 2, 0, 1, jaw=4, chin=1, cheek=3, head_w=65,
                          eye_shape=2, eye_size=4, nose=0, neck_width=7, shoulder_width=8),
    "Mitch McKee": _look(1, 6, 2, 6, jaw=7, chin=1, cheek=5, face_length=2,
                        brow=9, eye_shape=2, iris_colour=4, hair_part=8, hair_volume=5),
    "Movsar Evloev": _look(1, 36, 1, 14, jaw=5, chin=3, cheek=5, face_length=2,
                          brow=3, eye_shape=6, nose=8, nose_length=6, hair_volume=7, hair_part=8),
    "Petr Yan": _look(1, 3, 2, 9, jaw=4, chin=1, cheek=6, head_w=64,
                     brow=7, eye_shape=2, eye_size=4, iris_colour=4, beard_colour=3),
    "Timur Khizriev": _look(1, 14, 1, 14, jaw=6, chin=0, cheek=4, head_w=58,
                           brow=3, eye_shape=2, nose=1, mouth=8, hair_volume=3),
    "Yaroslav Amosov PFL": _look(1, 3, 2, 10, jaw=4, chin=1, face_length=2,
                                brow=7, eye_shape=2, nose=1, ear=2, hair_volume=7),
    "AJ McKee": _look(4, 40, 0, 10, jaw=7, chin=1, cheek=3, face_length=2,
                     brow=0, eye_shape=0, nose=1, mouth=8, lip_fullness=6, ear=2),
    "Alexander Shabliy": _look(1, 6, 2, 9, jaw=4, chin=1, face_length=8,
                              brow=0, eye_shape=2, nose=0, hair_part=8, ear=2),
    "Aljamain Sterling": _look(4, 63, 0, 11, jaw=7, chin=3, cheek=3,
                              brow=3, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Belal Muhammad": _look(2, 1, 0, 11, jaw=7, chin=1, face_length=2,
                           brow=7, eye_shape=2, nose=6, nose_length=6, ear=2),
    "Caio Borralho": _look(2, 6, 1, 0, jaw=4, chin=1, cheek=6, head_w=70,
                          brow=3, eye_shape=2, nose=9, mouth=8, lip_fullness=6, hair_part=8),
    "Carlos Prates": _look(3, 40, 0, 0, jaw=7, chin=1, cheek=3, face_length=2,
                          brow=3, eye_shape=2, nose=1, mouth=8, lip_fullness=8, ear=2),
    "Corey Anderson": _look(5, 0, 0, 12, jaw=4, chin=1, cheek=3, head_w=70,
                           brow=7, nose=1, mouth=8, lip_fullness=6, neck_width=8, shoulder_width=8),
    "Cristiane Justino": _look(2, 150, 1, 0, jaw=3, chin=1, cheek=3, face_length=2,
                              brow=5, eye_shape=0, nose=8, nose_length=6, mouth=8,
                              lip_fullness=6, shoulder_width=6, dye="burgundy"),
    "Dan Henderson": _look(2, 1, 1, 2, jaw=4, chin=2, cheek=3, head_w=72,
                          brow=3, eye_shape=2, eye_size=4, nose=1, neck_width=8, shoulder_width=8),
    "Diego Lopes": _look(1, 149, 2, 3, jaw=4, chin=1, cheek=4, head_w=62,
                        brow=7, eye_shape=2, eye_size=4, nose=0, mouth=1, hair_part=8),
    "Dominick Cruz": _look(2, 9, 0, 9, jaw=7, chin=3, cheek=5, face_length=2,
                          brow=3, eye_shape=0, nose=6, nose_length=6, ear=2),
    "Gadzhi Rabadanov": _look(2, 36, 1, 10, jaw=7, chin=1, cheek=5, face_length=2,
                             brow=3, eye_shape=0, nose=6, nose_length=6, ear=2, hair_part=1),
    "Gilbert Melendez": _look(2, 41, 0, 2, jaw=4, chin=1, cheek=3, head_w=68,
                             brow=7, eye_shape=2, nose=1, mouth=8, hair_volume=2),
    "Jan Blachowicz": _look(1, 1, 2, 11, jaw=4, chin=1, cheek=3, head_w=68,
                           brow=7, eye_shape=2, nose=1, iris_colour=4,
                           neck_width=7, shoulder_width=8, beard_colour=3),
    "Jiri Prochazka": _look(1, 1, 2, 10, jaw=7, chin=1, cheek=5, face_length=2,
                           brow=0, eye_shape=2, nose=8, iris_colour=4, beard_colour=2),
    "Johnny Eblen": _look(1, 6, 2, 9, jaw=4, chin=1, cheek=6, head_w=68,
                         brow=0, eye_shape=2, nose=1, ear=2, beard_colour=3, hair_part=8),
    "Joselyne Edwards": _look(4, 37, 0, 0, jaw=5, chin=0, cheek=3, face_length=2,
                             brow=5, eye_shape=0, eye_size=5, nose=1, mouth=8, lip_fullness=7),
    "Josh Hokit": _look(2, 1, 1, 10, jaw=4, chin=1, cheek=6, head_w=80,
                       brow=7, eye_shape=2, nose=1, neck_width=9, shoulder_width=9),
    "Joshua Van": _look(2, 4, 0, 6, jaw=3, chin=1, cheek=3, head_w=54,
                       brow=0, eye_shape=8, nose=9, mouth=8, lip_fullness=5),
    "Kamaru Usman": _look(5, 0, 0, 2, jaw=4, chin=1, cheek=6, head_w=70,
                         brow=7, eye_shape=0, nose=1, mouth=8, lip_fullness=7,
                         neck_width=8, shoulder_width=8),
    "Mauricio Rua": _look(2, 1, 1, 2, jaw=4, chin=1, cheek=4, head_w=74,
                         brow=3, eye_shape=2, nose=1, mouth=8, lip_fullness=6, neck_width=7),
    "Michael Morales": _look(3, 66, 0, 6, jaw=7, chin=1, cheek=3, face_length=2,
                            brow=3, eye_shape=2, nose=1, mouth=8, lip_fullness=7, hair_volume=7),
    "Nassourdine Imavov": _look(1, 3, 1, 10, jaw=7, chin=1, face_length=2,
                               brow=0, eye_shape=2, nose=6, nose_length=6),
    "Norma Dumont": _look(2, 140, 0, 0, jaw=3, chin=1, cheek=3, head_w=60,
                         brow=3, eye_shape=0, nose=8, mouth=8, lip_fullness=5),
    "Ramazan Kuramagomedov": _look(1, 3, 2, 14, jaw=5, chin=3, face_length=2,
                                  brow=0, eye_shape=2, nose=8, beard_colour=3),
    "Renat Khavalov": _look(1, 1, 1, 14, jaw=7, chin=1, face_length=2,
                           brow=0, eye_shape=0, eye_size=5, nose=0, ear=2),
    "Ronda Rousey": _look(0, 150, 4, 0, jaw=3, chin=1, cheek=4, head_w=58,
                         brow=7, eye_shape=2, nose=0, mouth=8, iris_colour=5,
                         hair_part=8, hair_volume=6),
    "Sean Brady": _look(1, 4, 2, 10, jaw=4, chin=1, cheek=3, head_w=68,
                       brow=7, eye_shape=2, nose=1, neck_width=7, ear=2),
    "Urijah Faber": _look(1, 148, 3, 1, jaw=7, chin=2, cheek=5, face_length=2,
                         brow=0, eye_shape=0, nose=0, mouth=2, hair_part=8, hair_volume=7),
    "Virna Jandiroba": _look(2, 41, 1, 0, jaw=7, chin=1, cheek=5, face_length=2,
                            brow=9, eye_shape=2, nose=8, nose_length=6, mouth=8, ear=2),
    "Yan Xiaonan": _look(2, 20, 0, 0, jaw=3, chin=1, cheek=3, head_w=57,
                        brow=0, eye_shape=8, nose=9, mouth=2),
    "Aiemann Zahabi": _look(1, 1, 1, 10, jaw=7, chin=1, face_length=2,
                           brow=3, eye_shape=0, nose=8, nose_length=6),
    "Alexander Volkov": _look(1, 93, 3, 2, jaw=7, chin=1, cheek=5, face_length=6,
                             brow=9, eye_shape=0, nose=8, nose_length=7, iris_colour=5,
                             shoulder_width=7, hair_volume=2),
    "Amanda Lemos": _look(2, 110, 1, 0, jaw=7, chin=1, cheek=5, face_length=2,
                         brow=0, eye_shape=2, nose=1, mouth=2, dye="bleach"),
    "Anatoly Malykhin BAMMA": _look(1, 2, 2, 2, jaw=4, chin=1, cheek=6, head_w=78,
                                  brow=7, eye_shape=2, nose=1, iris_colour=4,
                                  neck_width=9, shoulder_width=9),
    "Anthony Hernandez": _look(2, 149, 0, 9, jaw=4, chin=1, cheek=4, head_w=64,
                              brow=3, eye_shape=2, nose=1, hair_volume=6, hair_part=8),
    "Anthony Pettis": _look(2, 1, 0, 7, jaw=7, chin=1, cheek=5, face_length=2,
                           brow=7, eye_shape=2, nose=0, mouth=8, lip_fullness=5),
    "Arnold Allen": _look(0, 149, 3, 6, jaw=7, chin=1, cheek=5, face_length=2,
                         brow=9, eye_shape=2, nose=8, iris_colour=4, hair_volume=6),
}

# These archived records represent the same documented fighter look. Copy each
# vector so editing an era-specific delta later cannot mutate its other version.
for _original in ("Mirko Cro Cop", "Mauricio Rua", "Ronda Rousey", "Urijah Faber"):
    PORTRAIT_RANK_51_100_OVERRIDES[_original + " Legend"] = dict(
        PORTRAIT_RANK_51_100_OVERRIDES[_original])
