"""Authored cosmetic directions for database rating positions 101--200.

These display-only vectors are deliberately independent of ratings, abilities,
popularity, combat simulation and stored identity vectors.  They use only
append-only portrait catalogue IDs already available at runtime.
"""

from .ranked_51_100 import _look


PORTRAIT_RANK_101_200_OVERRIDES = {
    "Benson Henderson": _look(3, 24, 0, 10, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=0, nose=1, hair_volume=6),
    "Ciryl Gane": _look(4, 0, 0, 2, jaw=4, chin=1, cheek=4, head_w=72, brow=3, nose=1, neck_width=8, shoulder_width=8),
    "Eddie Alvarez": _look(1, 0, 1, 10, jaw=4, chin=1, cheek=5, head_w=66, brow=3, eye_shape=2, nose=5, ear=2),
    "Gegard Mousasi SF": _look(1, 0, 1, 1, jaw=7, chin=1, cheek=5, face_length=2, brow=0, eye_shape=2, nose=8, iris_colour=4),
    "Henry Cejudo": _look(2, 4, 1, 10, jaw=4, chin=1, cheek=3, head_w=65, brow=7, eye_shape=2, nose=1),
    "Ian Machado Garry": _look(0, 1, 5, 1, jaw=7, chin=3, cheek=5, face_length=2, brow=0, eye_shape=2, nose=8, iris_colour=5, hair_part=4, hair_volume=3),
    "Irene Aldana": _look(2, 18, 1, 0, jaw=7, chin=3, cheek=5, face_length=2, brow=3, eye_shape=0, nose=8, mouth=8, lip_fullness=6, hair_part=8),
    "Israel Adesanya": _look(5, 155, 0, 0, jaw=7, chin=3, cheek=5, face_length=2, brow=0, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Jake Shields": _look(1, 0, 1, 10, jaw=4, chin=1, cheek=4, head_w=67, brow=3, eye_shape=2, nose=1),
    "Loopy Godinez": _look(2, 44, 0, 0, jaw=3, chin=2, cheek=4, face_length=2, head_w=53,
                           brow=5, eye_shape=5, eye_size=5, nose=1, mouth=8, lip_fullness=7,
                           hair_part=7, hair_volume=5, feature_offset=5),
    "Murad Ramazanov": _look(1, 1, 0, 10, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=2, nose=8),
    "Quinton Jackson": _look(5, 0, 0, 6, jaw=4, chin=1, cheek=3, head_w=78, brow=7, eye_shape=0, nose=1, mouth=8, lip_fullness=7, neck_width=9, shoulder_width=9),
    "Randy Couture": _look(1, 0, 2, 2, jaw=4, chin=1, cheek=5, head_w=72, brow=7, eye_shape=2, nose=1, neck_width=8, shoulder_width=8),
    "Regian Eersel": _look(4, 26, 0, 9, jaw=7, chin=1, cheek=5, face_length=2, brow=0, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Rickson Gracie": _look(2, 16, 1, 1, jaw=4, chin=1, cheek=5, face_length=2, brow=0, eye_shape=2, nose=1, hair_volume=6, hair_part=7),
    "Robbie Lawler": _look(1, 1, 2, 2, jaw=4, chin=1, cheek=4, head_w=68, brow=7, eye_shape=2, nose=1, neck_width=7),
    "Sean O'Malley": _look(0, 152, 4, 1, jaw=7, chin=3, cheek=5, face_length=2, brow=0, eye_shape=0, nose=8, mouth=2, hair_volume=7, dye="rainbow"),
    "Sean Strickland": _look(1, 4, 1, 1, jaw=4, chin=1, cheek=5, head_w=68, brow=7, eye_shape=2, nose=1),
    "Serghei Spivac": _look(0, 1, 2, 10, jaw=4, chin=1, cheek=3, head_w=70, brow=7, eye_shape=2, nose=1, neck_width=8),
    "T.J. Dillashaw": _look(1, 4, 2, 9, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=2, nose=8, hair_volume=4),
    "Tawanchai PK Saenchai": _look(2, 3, 0, 0, jaw=3, chin=1, cheek=3, head_w=58, brow=0, eye_shape=8, nose=9, mouth=2),
    "Wanderlei Silva": _look(2, 1, 0, 2, jaw=4, chin=1, cheek=3, head_w=75, brow=7, eye_shape=2, nose=1, neck_width=8),
    "Yana Santos": _look(0, 35, 5, 0, jaw=3, chin=1, cheek=4, face_length=2, brow=5, eye_shape=0, nose=1, mouth=8, iris_colour=5),
    "Abdoul Abdouraguimov": _look(1, 1, 0, 11, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=0, nose=8),
    "Abdul-Aziz Abdulvakhabov": _look(1, 4, 0, 11, jaw=6, chin=2, cheek=4, face_length=3,
                                        head_w=63, brow=3, eye_shape=6, eye_size=3, nose=6,
                                        mouth=2, hair_part=6, feature_offset=3),
    "Ailin Perez": _look(2, 35, 0, 0, jaw=3, chin=1, cheek=3, face_length=2, brow=5, eye_shape=0, nose=1, mouth=8, lip_fullness=7),
    "Archie Colgan": _look(3, 41, 0, 9, jaw=7, chin=1, cheek=3, face_length=2, brow=3, eye_shape=0, nose=1),
    "Brendan Allen": _look(1, 4, 1, 10, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=2, nose=1),
    "Carlos Ulberg": _look(3, 4, 0, 1, jaw=7, chin=1, cheek=5, face_length=2, brow=0, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Chris Weidman": _look(1, 4, 1, 10, jaw=4, chin=1, cheek=4, head_w=68, brow=3, eye_shape=2, nose=1),
    "Christian Lee": _look(2, 6, 0, 0, jaw=7, chin=1, cheek=5, face_length=2, brow=0, eye_shape=8, nose=9, hair_part=8),
    "Cory Sandhagen": _look(0, 1, 2, 1, jaw=7, chin=3, cheek=5, face_length=2, brow=0, eye_shape=2, nose=8, iris_colour=5),
    "Curtis Blaydes": _look(5, 40, 0, 2, jaw=4, chin=1, cheek=3, head_w=76, brow=7, eye_shape=0, nose=1, neck_width=9, shoulder_width=9),
    "Dakota Ditcheva": _look(0, 35, 1, 0, jaw=3, chin=1, cheek=4, face_length=2, brow=5, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Denis Goltsov": _look(1, 1, 1, 10, jaw=4, chin=1, cheek=4, head_w=70, brow=3, eye_shape=2, nose=1, neck_width=8),
    "Dustin Poirier": _look(1, 4, 2, 10, jaw=4, chin=1, cheek=5, head_w=68, brow=3, eye_shape=2, nose=1),
    "Kevin Randleman": _look(5, 0, 0, 2, jaw=4, chin=1, cheek=3, head_w=77, brow=7, eye_shape=0, nose=1, neck_width=9, shoulder_width=9),
    "Khalil Rountree Jr.": _look(4, 0, 0, 6, jaw=7, chin=1, cheek=3, head_w=72, brow=7, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Kyoji Horiguchi": _look(2, 1, 0, 0, jaw=3, chin=1, cheek=3, head_w=55, brow=0, eye_shape=8, nose=9),
    "Leon Edwards": _look(4, 63, 0, 9, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Lerone Murphy": _look(4, 63, 0, 10, jaw=7, chin=1, cheek=5, face_length=2, brow=0, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Luke Trainer": _look(0, 4, 4, 9, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=2, nose=1, iris_colour=5),
    "Mackenzie Dern": _look(1, 35, 5, 0, jaw=3, chin=1, cheek=4, face_length=2, brow=5, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Magomed Umalatov": _look(1, 1, 0, 10, jaw=7, chin=1, cheek=5, face_length=2, head_w=69,
                                brow=7, eye_shape=2, eye_size=3, nose=8, mouth=1,
                                feature_offset=6, complexion=7),
    "Manel Kape": _look(4, 40, 0, 9, jaw=6, chin=2, cheek=3, face_length=3, head_w=67,
                         brow=7, eye_shape=5, eye_size=4, nose=6, mouth=2, lip_fullness=7,
                         hair_volume=5, feature_offset=3),
    "Mark Kerr": _look(1, 0, 1, 2, jaw=4, chin=1, cheek=3, head_w=76, brow=7, eye_shape=2, nose=1, neck_width=9, shoulder_width=9),
    "Mauricio Ruffy": _look(3, 41, 0, 3, jaw=7, chin=1, cheek=5, face_length=3, head_w=65,
                              brow=0, eye_shape=6, eye_size=4, nose=8, mouth=2, lip_fullness=7,
                              hair_volume=6, feature_offset=5),
    "Robert Whittaker": _look(1, 4, 1, 10, jaw=4, chin=1, cheek=5, head_w=68, brow=3, eye_shape=2, nose=1),
    "Salahdine Parnasse": _look(3, 4, 0, 9, jaw=7, chin=1, cheek=5, face_length=2, brow=0, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Stipe Miocic": _look(1, 1, 2, 2, jaw=4, chin=1, cheek=3, head_w=72, brow=7, eye_shape=2, nose=1, neck_width=8, shoulder_width=8),
    "Superlek Kiatmoo9": _look(2, 3, 0, 0, jaw=3, chin=1, cheek=3, head_w=58, brow=0, eye_shape=8, nose=9),
    "Tatsuro Taira": _look(2, 14, 0, 0, jaw=3, chin=1, cheek=3, head_w=56, brow=0, eye_shape=8, nose=9, hair_volume=5),
    "Taylor Lapilus": _look(4, 4, 0, 9, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Aaron Pico": _look(1, 4, 2, 9, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=2, nose=1),
    "Angela Lee": _look(1, 35, 1, 0, jaw=3, chin=1, cheek=4, face_length=2, brow=5, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Askar Askarov": _look(1, 1, 0, 10, jaw=4, chin=1, cheek=3, head_w=65, brow=3, eye_shape=2, nose=1),
    "Benoit Saint Denis": _look(1, 45, 1, 10, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=2, nose=1, hair_volume=6),
    "Bogdan Guskov": _look(2, 1, 0, 10, jaw=4, chin=1, cheek=4, head_w=70, brow=3, eye_shape=2, nose=1),
    "Brandon Royval": _look(1, 45, 1, 2, jaw=7, chin=3, cheek=5, face_length=2, brow=0, eye_shape=2, nose=8, hair_volume=7),
    "Carlos Condit": _look(1, 17, 5, 6, jaw=7, chin=3, cheek=5, face_length=2, brow=0, eye_shape=2, nose=8, hair_volume=7),
    "Chuck Liddell": _look(1, 151, 5, 0, jaw=4, chin=1, cheek=3, head_w=70, brow=7, eye_shape=2, nose=1),
    "Cris Cyborg": _look(2, 150, 1, 0, jaw=3, chin=1, cheek=3, face_length=2, brow=5, eye_shape=0, nose=8, nose_length=6, mouth=8, lip_fullness=6, shoulder_width=6, dye="burgundy"),
    "Cung Le": _look(2, 1, 0, 0, jaw=4, chin=1, cheek=5, head_w=66, brow=0, eye_shape=8, nose=1),
    "Dan Hooker": _look(1, 149, 5, 10, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=2, nose=8, hair_volume=7, hair_part=7, beard_colour=2),
    "Douglas Lima": _look(2, 4, 0, 9, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Dovletdzhan Yagshimuradov": _look(2, 1, 0, 10, jaw=4, chin=1, cheek=5, head_w=70, brow=3, eye_shape=2, nose=1),
    "Francis Ngannou": _look(5, 0, 0, 10, jaw=4, chin=1, cheek=3, head_w=78, brow=7, eye_shape=0, nose=1, mouth=8, lip_fullness=6, neck_width=9, shoulder_width=9),
    "Gabriel Bonfim": _look(3, 4, 0, 3, jaw=7, chin=2, cheek=4, face_length=2, head_w=70,
                              brow=3, eye_shape=0, eye_size=3, nose=1, mouth=8, lip_fullness=6,
                              hair_part=6, feature_offset=3),
    "Gillian Robertson": _look(0, 37, 5, 0, jaw=3, chin=1, cheek=4, face_length=2, brow=5, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Glover Teixeira": _look(2, 0, 1, 10, jaw=4, chin=1, cheek=3, head_w=74, brow=7, eye_shape=2, nose=1, neck_width=8),
    "Jailton Almeida": _look(4, 1, 0, 9, jaw=4, chin=1, cheek=3, head_w=72, brow=7, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Kiamrian Abbasov": _look(2, 4, 0, 10, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=2, nose=1),
    "Luana Santos": _look(2, 21, 0, 0, jaw=3, chin=1, cheek=3, face_length=2, brow=5, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Marat Gafurov": _look(1, 16, 0, 10, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=2, nose=8, hair_volume=6),
    "Marvin Vettori": _look(1, 1, 1, 2, jaw=4, chin=1, cheek=3, head_w=72, brow=7, eye_shape=2, nose=1, neck_width=8),
    "Movlid Khaybulaev": _look(1, 0, 0, 10, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=2, nose=1),
    "Nate Diaz": _look(1, 3, 1, 1, jaw=7, chin=3, cheek=5, face_length=2, brow=0, eye_shape=2, nose=8, hair_volume=4),
    "Nick Diaz": _look(2, 3, 1, 5, jaw=7, chin=3, cheek=5, face_length=2, brow=0, eye_shape=2, nose=8, hair_volume=4),
    "Paddy Pimblett": _look(0, 150, 5, 0, jaw=7, chin=1, cheek=5, face_length=2, brow=0, eye_shape=2, nose=1, hair_volume=7, hair_part=6),
    "Patchy Mix": _look(4, 23, 0, 10, jaw=7, chin=1, cheek=5, face_length=2, brow=0, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Rafael dos Anjos": _look(2, 4, 0, 10, jaw=4, chin=1, cheek=3, head_w=68, brow=7, eye_shape=2, nose=1),
    "Rashad Evans": _look(4, 0, 0, 10, jaw=4, chin=1, cheek=3, head_w=74, brow=7, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Reinier de Ridder ONE": _look(0, 4, 3, 1, jaw=7, chin=1, cheek=5, face_length=2, brow=0, eye_shape=2, nose=8, iris_colour=5),
    "Salamat Isbulaev": _look(1, 1, 0, 10, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=2, nose=1, feature_offset=6, complexion=8),
    "Sergei Kharitonov": _look(1, 0, 1, 2, jaw=4, chin=1, cheek=3, head_w=74, brow=7, eye_shape=2, nose=1, neck_width=8),
    "Sergei Pavlovich": _look(1, 2, 6, 10, jaw=4, chin=1, cheek=3, head_w=77, brow=7, eye_shape=2, nose=1, neck_width=9),
    "Sergio Pettis": _look(2, 4, 0, 6, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=0, nose=1, mouth=8, lip_fullness=6),
    "Shamil Musaev": _look(2, 1, 0, 10, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=2, nose=1),
    "Song Yadong": _look(2, 3, 0, 0, jaw=3, chin=1, cheek=3, head_w=56, brow=0, eye_shape=8, nose=9),
    "Superbon Singha Mawynn": _look(2, 6, 0, 0, jaw=3, chin=2, cheek=4, face_length=3,
                                      head_w=61, brow=5, eye_shape=5, eye_size=3, nose=6,
                                      mouth=2, hair_part=7, feature_offset=5),
    "Valentin Moldavsky": _look(1, 1, 3, 2, jaw=4, chin=1, cheek=3, head_w=70, brow=7, eye_shape=2, nose=1),
    "Alistair Overeem": _look(3, 0, 0, 2, jaw=4, chin=1, cheek=3, head_w=77, brow=7, eye_shape=0, nose=1, neck_width=9, shoulder_width=9),
    "Andrei Arlovski": _look(1, 18, 1, 11, jaw=4, chin=1, cheek=5, head_w=70, brow=7, eye_shape=2, nose=1, hair_volume=6),
    "Asu Almabayev": _look(2, 3, 0, 10, jaw=3, chin=1, cheek=3, head_w=57, brow=0, eye_shape=8, nose=9),
    "Bo Nickal LFA": _look(1, 4, 2, 1, jaw=7, chin=1, cheek=5, face_length=2, brow=3, eye_shape=2, nose=1),
}


# Archive entries deliberately copy the reference-period look but not a mutable dict.
for _original in ("Quinton Jackson", "Robbie Lawler", "Wanderlei Silva", "Cris Cyborg", "Paddy Pimblett"):
    _suffix = " Legend" if _original in {"Quinton Jackson", "Robbie Lawler", "Wanderlei Silva"} else " SF" if _original == "Cris Cyborg" else " CW"
    PORTRAIT_RANK_101_200_OVERRIDES[_original + _suffix] = dict(PORTRAIT_RANK_101_200_OVERRIDES[_original])
