"""Phase 33 concrete answers for every existing defensive family."""
from .schema import defense, ALL_POSITIONS, STANDING_POSITIONS, CLINCH_POSITIONS, GROUND_POSITIONS

PHASE_33_DEFENSES = (
    defense("shoulder_roll", "shoulder roll", ("block", "slip-block", "parry"), STANDING_POSITIONS,
            ("head_movement", "guard_defence"), ("strike", "block", "punch")),
    defense("long_guard_frame", "long-guard frame", ("block", "jam", "parry-check"), STANDING_POSITIONS,
            ("guard_defence", "footwork"), ("strike", "frame")),
    defense("cross_guard_catch", "cross-guard catch", ("catch", "block-check"), STANDING_POSITIONS,
            ("guard_defence", "kick_defence"), ("strike", "catch")),
    defense("elbow_in_body_block", "elbow-in body block", ("block", "shell"), STANDING_POSITIONS,
            ("guard_defence", "reflexes"), ("strike", "block", "body")),
    defense("level_change_duck", "level-change duck", ("duck", "slip-block"), STANDING_POSITIONS,
            ("head_movement", "reflexes"), ("strike", "evasion")),
    defense("roll_under_hook", "roll underneath", ("duck", "evade"), STANDING_POSITIONS,
            ("head_movement", "footwork"), ("strike", "evasion")),
    defense("switch_step_evasion", "switch-step evasion", ("stance switch", "sidestep", "pullback"), STANDING_POSITIONS,
            ("footwork", "mobility"), ("strike", "evasion")),
    defense("pivot_off_line", "pivot off the attack line", ("stance switch", "evade"), STANDING_POSITIONS,
            ("footwork", "reflexes"), ("strike", "evasion")),
    defense("crossface_sprawl", "crossface-and-sprawl", ("sprawl", "whizzer"), ALL_POSITIONS,
            ("sprawl", "clinch_defence"), ("wrestling", "sprawl")),
    defense("underhook_recovery", "inside-underhook recovery", ("underhook", "hip turn", "hip block"), CLINCH_POSITIONS,
            ("clinch_defence", "scrambles"), ("clinch", "underhook")),
    defense("wide_base_recovery", "wide-base recovery", ("balance", "base", "wide base"), ALL_POSITIONS,
            ("strength", "mobility"), ("wrestling", "escape")),
    defense("fence_hip_frame", "fence-assisted hip frame", ("fence post", "hip pressure", "cage escape"), CLINCH_POSITIONS | {"failed shot"},
            ("cage_wrestling", "clinch_defence"), ("cage", "frame")),
    defense("hop_and_peel_leg", "hop-and-peel leg escape", ("hop", "limp leg"), ALL_POSITIONS,
            ("mobility", "scrambles"), ("wrestling", "escape")),
    defense("wrist_grip_strip", "wrist-grip strip", ("hand fight", "back take"), CLINCH_POSITIONS | GROUND_POSITIONS,
            ("scrambles", "clinch_defence"), ("control", "escape")),
    defense("hip_to_hip_escape", "hip-to-hip escape", ("back step", "scramble"), GROUND_POSITIONS,
            ("bottom_control", "scrambles"), ("ground", "escape")),
    defense("angled_shin_check", "angled shin check", ("check", "parry-check", "block-check"), STANDING_POSITIONS,
            ("kick_defence", "reflexes"), ("kick", "check")),
    defense("submission_grip_strip", "submission grip strip", ("submission defense", "stack"), GROUND_POSITIONS,
            ("submission_defence_detail", "scrambles"), ("submission", "grip-defense")),
    defense("posture_and_frame", "posture-and-frame defense", ("frame", "guard frame", "submission defense"), GROUND_POSITIONS,
            ("guard_work", "submission_defence_detail"), ("ground", "frame")),
    defense("leg_lock_rotation", "leg-lock rotation escape", ("leg escape", "stack"), {"guard", "half guard", "leg entanglement"},
            ("submission_defence_detail", "mobility"), ("leg-lock", "escape")),
    defense("wall_underhook_escape", "wall-underhook escape", ("wall walk", "cage escape", "hip turn"), CLINCH_POSITIONS | GROUND_POSITIONS,
            ("cage_wrestling", "get_ups"), ("cage", "escape")),
    defense("seatbelt_hand_fight", "seatbelt hand fight", ("back take", "hand fight"), CLINCH_POSITIONS | GROUND_POSITIONS,
            ("submission_defence_detail", "scrambles"), ("control", "escape")),
    defense("backstep_knee_clear", "backstep knee-line clearance", ("leg escape", "back step", "scramble"), GROUND_POSITIONS,
            ("scrambles", "submission_defence_detail"), ("leg-lock", "escape")),
)
