"""Reviewed Phase 31 successor-only updates for permanent original move IDs.

Edges follow staged paths: kicking setups/boxing -> entries -> top control ->
passing/submissions. Head round kicks, teeps, side kicks and rear uppercuts remain
standing terminals; escapes can reach them without looping back into a takedown.
Each tuple offers alternatives, not mandatory extra actions or guaranteed success.
"""

LEGACY_FOLLOWUP_UPDATES = {
    # Boxing setup and combination lanes. Entries remain available when the
    # independently resolved next action changes from striking to grappling.
    "body_jab": ("one_two", "jab_to_shot"),
    "power_jab": ("lead_hook_cross", "double_leg_entry"),
    "up_jab": ("one_two", "collar_tie_entry"),
    "lead_hook_cross": ("rear_uppercut", "body_lock_entry"),
    "double_jab_cross": ("lead_hook_cross", "double_leg_entry"),
    "cross_hook_cross": ("rear_uppercut", "over_under_entry"),
    "body_head_change": ("lead_hook_cross", "collar_tie_entry"),
    "jab_uppercut_lead_hook": ("rear_uppercut", "double_underhooks"),
    "double_jab_body_cross": ("lead_hook_cross", "jab_to_shot"),
    "cross_body_hook_lead_hook": ("rear_uppercut", "body_lock_entry"),
    "stance_shift_cross_hook": ("rear_uppercut", "single_leg_entry"),
    "boxing_pressure_flurry": ("rear_uppercut", "collar_tie_entry"),
    "corkscrew_cross": ("lead_hook_cross", "head_round_kick"),
    "spinning_backfist": ("side_kick", "body_lock_entry"),
    "check_hook": ("head_round_kick", "double_leg_entry"),
    "pull_counter": ("lead_hook_cross", "head_round_kick"),
    "slip_cross": ("rear_uppercut", "body_lock_entry"),
    "intercepting_knee": ("collar_tie_entry", "lead_teep"),
    "jab_cross_rear_knee": ("thai_plum_entry", "lead_teep"),
    "hook_elbow_knee": ("thai_plum_entry", "head_round_kick"),
    "flying_knee": ("collar_tie_entry", "lead_teep"),
    "switch_flying_knee": ("thai_plum_entry", "side_kick"),
    "step_in_elbow": ("collar_tie_entry", "rear_uppercut"),
    "spinning_elbow": ("body_lock_entry", "side_kick"),
    "boxer_double_jab_pivot_cross_hook": ("rear_uppercut", "collar_tie_entry"),
    "muay_thai_teep_cross_elbow_knee": ("thai_plum_entry", "lead_teep"),
    "karate_blitz_cross_hook_exit": ("side_kick", "head_round_kick"),
    "boxer_shift_step_cross_finisher": ("rear_uppercut", "collar_tie_entry"),
    "dutch_high_guard_cross_hook_finisher": ("head_round_kick", "collar_tie_entry"),
    "muay_thai_frame_elbow_finisher": ("thai_plum_entry", "lead_teep"),
    "karate_blitz_reverse_cross_finisher": ("side_kick", "head_round_kick"),
    "mma_generalist_elbow_knee_finisher": ("body_lock_entry", "lead_teep"),

    # Low/body kicking opens boxing and entry lanes; high kicks and distance
    # resets stay terminal so a finite sequence cannot feed its own bonus.
    "inside_low_kick": ("single_jab", "overhand"),
    "outside_low_kick": ("one_two", "head_round_kick"),
    "body_round_kick": ("single_jab", "head_round_kick"),
    "calf_kick": ("one_two", "single_leg_entry"),
    "low_kick_counter": ("one_two", "head_round_kick"),
    "question_mark_kick": ("single_jab", "collar_tie_entry"),
    "wheel_kick": ("side_kick", "single_jab"),
    "spinning_back_kick": ("single_jab", "side_kick"),
    "switch_body_kick": ("one_two", "thai_plum_entry"),
    "jab_low_kick": ("one_two", "double_leg_entry"),
    "cross_body_kick": ("lead_hook_cross", "head_round_kick"),
    "hook_low_kick": ("rear_uppercut", "collar_tie_entry"),
    "punch_head_kick": ("single_jab", "lead_teep"),
    "double_jab_low_kick": ("one_two", "jab_to_shot"),
    "cross_hook_body_kick": ("lead_hook_cross", "head_round_kick"),
    "axe_kick": ("single_jab", "side_kick"),
    "jumping_front_kick": ("single_jab", "lead_teep"),
    "kickboxer_cross_hook_switch_kick": ("one_two", "head_round_kick"),
    "dutch_high_guard_hook_cross_low_kick": ("lead_hook_cross", "head_round_kick"),
    "taekwondo_side_back_round_chain": ("side_kick", "single_jab"),
    "mma_generalist_cross_kick_clinch_chain": ("body_lock_entry", "lead_teep"),
    "kickboxer_cross_high_kick_finisher": ("single_jab", "lead_teep"),
    "taekwondo_spinning_hook_kick_finisher": ("side_kick", "single_jab"),
    "sanda_jumping_side_kick_finisher": ("single_jab", "body_lock_entry"),
    "well_rounded_cross_head_kick_finisher": ("single_jab", "lead_teep"),

    # Inside offense -> takedown or stronger tie. No strike -> exit -> entry
    # loops: exits below lead to the explicit terminal distance weapons.
    "short_clinch_boxing": ("clinch_knee", "double_leg_finish"),
    "clinch_knee": ("body_lock_trip", "inside_trip"),
    "inside_uppercut": ("clinch_knee", "knee_tap"),
    "collar_tie_elbow": ("clinch_knee", "inside_trip"),
    "inside_body_hook": ("inside_uppercut", "body_lock_trip"),
    "shoulder_grind": ("short_clinch_boxing", "double_leg_finish"),
    "fence_pressure": ("pummel_to_underhook", "short_clinch_boxing", "double_leg_finish"),
    "pummel_to_underhook": ("knee_tap", "clinch_knee"),
    "shoulder_pressure": ("short_clinch_boxing", "body_lock_trip"),
    "pivot_exit": ("side_kick", "lead_teep"),
    "frame_exit": ("lead_teep", "head_round_kick"),
    "frame_and_pivot_exit": ("side_kick", "head_round_kick"),
    "post_and_push_exit": ("lead_teep", "side_kick"),
    "swim_to_space": ("side_kick", "lead_teep"),

    # Both shoot and takedown settle successful attempts directly into top
    # guard/half guard. Original cage finishes remain useful near-success lanes.
    "double_leg_entry": ("double_leg_finish", "chest_to_chest_pin", "position_pass"),
    "single_leg_entry": ("single_leg_finish", "hip_pressure_ride", "knee_slice_pass"),
    "ankle_pick_entry": ("single_leg_finish", "chest_to_chest_pin", "position_pass"),
    "reactive_shot": ("double_leg_finish", "hip_pressure_ride", "knee_slice_pass"),
    "jab_to_shot": ("double_leg_finish", "chest_to_chest_pin", "position_pass"),
    "overhand_to_double": ("double_leg_finish", "hip_pressure_ride", "knee_slice_pass"),
    "sanda_side_kick_overhand_shot": ("single_leg_finish", "chest_to_chest_pin", "position_pass"),
    "wrestler_jab_overhand_double": ("double_leg_finish", "hip_pressure_ride", "knee_slice_pass"),
    "freestyle_feint_reshot_chain": ("single_leg_finish", "chest_to_chest_pin", "position_pass"),
    "well_rounded_jab_low_kick_level_change": ("double_leg_finish", "hip_pressure_ride", "knee_slice_pass"),
    "double_leg_finish": ("hip_pressure_ride", "posture_punches", "position_pass"),
    "single_leg_finish": ("chest_to_chest_pin", "short_ground_elbows", "knee_slice_pass"),
    "body_lock_trip": ("chest_to_chest_pin", "body_head_ground_chain", "position_pass"),
    "inside_trip": ("hip_pressure_ride", "posture_punches", "knee_slice_pass"),
    "outside_trip": ("chest_to_chest_pin", "short_ground_elbows", "position_pass"),
    "high_crotch_finish": ("hip_pressure_ride", "body_head_ground_chain", "knee_slice_pass"),
    "knee_tap": ("chest_to_chest_pin", "posture_punches", "position_pass"),
    "hip_toss": ("chest_to_chest_pin", "short_ground_elbows", "knee_slice_pass"),
    "lateral_drop": ("hip_pressure_ride", "body_head_ground_chain", "position_pass"),

    # Top-game stages retain the actual position. The broad templates cover
    # guards; specific submissions/strikes take over in dominant positions.
    "ride_control": ("ride_wrist_punches", "posture_punches", "half_guard_kimura"),
    "chest_to_chest_pin": ("short_ground_elbows", "position_pass", "guard_top_head_arm"),
    "hip_pressure_ride": ("body_head_ground_chain", "knee_slice_pass", "half_guard_arm_triangle"),
    "knee_on_belly_pressure": ("crucifix_elbows", "arm_triangle", "half_guard_brabo"),
    "posture_punches": ("position_pass", "guard_top_head_arm"),
    "short_ground_elbows": ("knee_slice_pass", "half_guard_darce"),
    "body_head_ground_chain": ("position_pass", "guard_top_head_arm"),
    "ride_wrist_punches": ("underhook_half_guard_pass", "rear_naked_choke", "turtle_breakdown"),
    "turtle_wrist_ride_strikes": ("turtle_breakdown",),
    "wrestler_wrist_ride_hammerfist_finisher": ("underhook_half_guard_pass", "arm_triangle", "turtle_breakdown"),
    "freestyle_mat_return_ground_pound_finisher": ("underhook_half_guard_pass", "arm_triangle", "turtle_breakdown"),
    "half_guard_pass": ("crucifix_elbows", "mount_transition", "arm_triangle"),
    "knee_slice_pass": ("half_guard_kimura", "arm_triangle", "mount_transition"),

    # Bottom attacks can switch submissions or build a genuine reversal. An
    # escaped lock does not grant top control; only a successful sweep does.
    "guard_armbar": ("triangle_choke", "kimura_guard", "technical_standup"),
    "triangle_choke": ("kimura_guard", "hip_bump_sweep", "technical_standup"),
    "kimura_guard": ("hip_bump_sweep", "butterfly_sweep", "technical_standup"),
    "omoplata": ("butterfly_sweep", "technical_standup"),
    "guard_submission_chain": ("butterfly_sweep", "technical_standup"),
    "bjj_triangle_armbar_finisher": ("kimura_guard", "hip_bump_sweep", "technical_standup"),
    "luta_outside_heel_hook_finisher": ("guard_submission_chain", "butterfly_sweep", "technical_standup"),
    "sambo_rolling_kneebar_finisher": ("kimura_guard", "butterfly_sweep", "technical_standup"),
    "guard_recovery": ("guard_armbar", "butterfly_sweep", "technical_standup"),
    "closed_guard_retention": ("triangle_choke", "hip_bump_sweep", "technical_standup"),
    "elbow_knee_guard_recovery": ("guard_submission_chain", "butterfly_sweep", "technical_standup"),
    "back_control_handfight_recovery": ("guard_submission_chain", "hip_bump_sweep", "technical_standup"),
    "butterfly_sweep": ("chest_to_chest_pin", "posture_punches", "position_pass"),
    "hip_bump_sweep": ("hip_pressure_ride", "short_ground_elbows", "knee_slice_pass"),
    "technical_standup": ("lead_teep", "side_kick"),
    "post_and_build_getup": ("lead_teep", "head_round_kick"),
    "tripod_standup": ("side_kick", "lead_teep"),
    "defensive_cling": ("guard_recovery", "guard_submission_chain", "technical_standup"),
    "wrist_ride_neutralize": ("guard_recovery", "guard_submission_chain", "technical_standup"),
    "closed_guard_hold": ("guard_submission_chain", "butterfly_sweep", "technical_standup"),
    "underhook_stall": ("guard_recovery", "butterfly_sweep", "technical_standup"),
    "head_pinch_stall": ("guard_recovery", "guard_submission_chain", "technical_standup"),
}
