"""ground control catalogue; historical batches preserve selection order."""
from ..schema import move, ALL_POSITIONS, STANDING_POSITIONS, CLINCH_POSITIONS, GROUND_POSITIONS

BATCH_012 = (
    move("posture_punches", "postured ground punches", "ground_strikes", GROUND_POSITIONS,
         attack_skills=("ground_striking", "top_control", "punch_power"), defense_skills=("guard_work", "bottom_control"),
         preferred_styles=("Wrestler", "Sambo"), tags=("ground", "strike", "punch")),
    move("short_ground_elbows", "short ground elbows", "ground_strikes", GROUND_POSITIONS,
         attack_skills=("ground_striking", "elbows", "positional_ability"), defense_skills=("guard_work", "scrambles"),
         preferred_styles=("Muay Thai", "BJJ"), minimum_skill=52, tags=("ground", "strike", "elbow")),
    move("body_head_ground_chain", "body-head ground-punch chain", "ground_strikes", GROUND_POSITIONS,
         attack_skills=("ground_striking", "combination_punching", "top_control"), defense_skills=("bottom_control", "guard_work"),
         preferred_styles=("Wrestler", "Sambo", "MMA Generalist"), minimum_skill=54, energy=1.12,
         tags=("ground", "strike", "combination")),
    move("ride_wrist_punches", "wrist-ride punches", "ground_strikes", frozenset({"turtle", "back control", "half guard"}),
         attack_skills=("ride_control", "ground_striking", "top_control"), defense_skills=("scrambles", "get_ups"),
         preferred_styles=("Wrestler", "Catch Wrestler"), minimum_skill=55,
         tags=("ground", "strike", "ride")),
    move("guard_posture_elbows", "posture-punch and elbow chain from guard", "ground_strikes", frozenset({"guard"}),
         attack_skills=("ground_striking", "elbows", "top_control"), defense_skills=("guard_work", "bottom_control"),
         preferred_styles=("Muay Thai", "Wrestler", "MMA Generalist"), minimum_skill=54, energy=1.12,
         follow_ups=("headquarters_pass",), tags=("ground", "strike", "elbow", "combination", "guard")),
    move("half_guard_crossface_strikes", "crossface striking chain from half guard", "ground_strikes", frozenset({"half guard"}),
         attack_skills=("ground_striking", "top_control", "punch_power"), defense_skills=("bottom_control", "guard_work"),
         preferred_styles=("Wrestler", "Sambo", "Catch Wrestler"), minimum_skill=55, energy=1.1,
         follow_ups=("underhook_half_guard_pass",), tags=("ground", "strike", "punch", "combination", "pressure")),
    move("crucifix_elbows", "crucifix elbows", "ground_strikes", frozenset({"side control"}),
         attack_skills=("ground_striking", "elbows", "positional_ability"), defense_skills=("scrambles", "bottom_control"),
         preferred_styles=("BJJ", "Wrestler", "Muay Thai"), minimum_skill=60, energy=1.18,
         follow_ups=("arm_triangle",), tags=("ground", "strike", "elbow", "control")),
    move("mounted_hammerfist_flurry", "mounted hammerfist flurry", "ground_strikes", frozenset({"mount"}),
         attack_skills=("ground_striking", "mount_control", "punch_power"), defense_skills=("bottom_control", "composure"),
         preferred_styles=("Wrestler", "Sambo", "MMA Generalist"), minimum_skill=58, energy=1.2,
         follow_ups=("arm_triangle", "top_armbar"), tags=("ground", "strike", "punch", "combination", "mount", "power")),
    move("back_control_short_punches", "short punches from back control", "ground_strikes", frozenset({"back control"}),
         attack_skills=("ground_striking", "back_control", "hand_speed"), defense_skills=("submission_defence_detail", "scrambles"),
         preferred_styles=("BJJ", "Wrestler", "Submission Grappler"), minimum_skill=56, energy=1.08,
         follow_ups=("rear_naked_choke",), tags=("ground", "strike", "punch", "back-control")),
    move("turtle_wrist_ride_strikes", "wrist-ride striking chain against turtle", "ground_strikes", frozenset({"turtle"}),
         attack_skills=("ride_control", "ground_striking", "elbows"), defense_skills=("get_ups", "scrambles"),
         preferred_styles=("Wrestler", "Catch Wrestler", "Sambo"), minimum_skill=57, energy=1.14,
         tags=("ground", "strike", "ride", "combination")),
)

BATCH_022 = (
    move("ride_control", "heavy ride control", "ground_control", GROUND_POSITIONS,
         attack_skills=("ride_control", "top_control", "strength"), defense_skills=("scrambles", "get_ups"),
         preferred_styles=("Wrestler", "Catch Wrestler"), tags=("ground", "control")),
    move("half_guard_crossface_control", "crossface-and-underhook half-guard control", "ground_control", frozenset({"half guard"}),
         attack_skills=("top_control", "ride_control", "strength"), defense_skills=("bottom_control", "scrambles"),
         preferred_styles=("Wrestler", "Catch Wrestler", "Sambo"), minimum_skill=54,
         follow_ups=("underhook_half_guard_pass",), tags=("ground", "control", "pressure", "underhook")),
    move("mount_grapevine_control", "grapevine mount control", "ground_control", frozenset({"mount"}),
         attack_skills=("mount_control", "top_control", "strength"), defense_skills=("bottom_control", "scrambles"),
         preferred_styles=("BJJ", "Wrestler", "Submission Grappler"), minimum_skill=56,
         follow_ups=("mounted_hammerfist_flurry",), tags=("ground", "control", "mount")),
    move("body_triangle_back_control", "body-triangle back control", "ground_control", frozenset({"back control"}),
         attack_skills=("back_control", "ride_control", "conditioning"), defense_skills=("submission_defence_detail", "scrambles"),
         preferred_styles=("BJJ", "Submission Grappler", "Luta Livre"), minimum_skill=58, energy=1.06,
         follow_ups=("rear_naked_choke",), tags=("ground", "control", "back-control")),
    move("defensive_cling", "defensive clinch on the mat", "cling", GROUND_POSITIONS,
         attack_skills=("bottom_control", "composure", "guard_work"), defense_skills=("top_control", "ground_striking"),
         preferred_styles=("BJJ",), tags=("ground", "defense")),
)

BATCH_024 = (
    move("wrist_ride_neutralize", "wrist-control neutralization", "cling", GROUND_POSITIONS,
         attack_skills=("bottom_control", "guard_work", "composure"), defense_skills=("ground_striking", "top_control"),
         preferred_styles=("BJJ", "Submission Grappler"), tags=("ground", "defense", "wrist-control")),
    move("closed_guard_hold", "closed guard hold", "cling", frozenset({"guard", "half guard"}),
         attack_skills=("guard_work", "flexibility", "strength"), defense_skills=("top_control", "positional_ability"),
         preferred_styles=("BJJ", "Luta Livre"), tags=("ground", "defense", "guard")),
    move("underhook_stall", "deep underhook stall", "cling", GROUND_POSITIONS,
         attack_skills=("bottom_control", "strength", "scrambles"), defense_skills=("ride_control", "top_control"),
         preferred_styles=("Wrestler", "Sambo"), tags=("ground", "defense", "underhook")),
    move("head_pinch_stall", "head-pinch stall", "cling", GROUND_POSITIONS,
         attack_skills=("guard_work", "composure", "submission_defence_detail"), defense_skills=("ground_striking", "transitions"),
         preferred_styles=("BJJ", "Catch Wrestler"), tags=("ground", "defense", "smother")),
    move("knee_on_belly_pressure", "knee-on-belly pressure", "ground_control", frozenset({"side control", "half guard"}),
         attack_skills=("top_control", "positional_ability", "ride_control"), defense_skills=("bottom_control", "scrambles"),
         preferred_styles=("BJJ", "Wrestler"), minimum_skill=54, tags=("ground", "control", "pressure")),
    move("chest_to_chest_pin", "chest-to-chest pin", "ground_control", GROUND_POSITIONS,
         attack_skills=("top_control", "strength", "conditioning"), defense_skills=("bottom_control", "guard_work"),
         preferred_styles=("Wrestler", "Judo", "Sambo"), tags=("ground", "control", "pressure")),
    move("hip_pressure_ride", "hip-pressure ride", "ground_control", GROUND_POSITIONS,
         attack_skills=("ride_control", "top_control", "discipline"), defense_skills=("scrambles", "get_ups"),
         preferred_styles=("Catch Wrestler", "Freestyle Wrestler"), tags=("ground", "control", "ride")),
)
