"""kicks catalogue; historical batches preserve selection order."""
from ..schema import move, ALL_POSITIONS, STANDING_POSITIONS, CLINCH_POSITIONS, GROUND_POSITIONS

BATCH_002 = (
    move("inside_low_kick", "inside low kick", "kick", STANDING_POSITIONS, targets=frozenset({"leg"}),
         attack_skills=("low_kick_technique", "low_kick_speed"), defense_skills=("kick_defence", "reflexes"),
         preferred_styles=("Muay Thai", "Kickboxer", "Sanda"), tags=("strike", "kick", "leg"),
         side="lead", range_band="kicking", defense_families=("check", "pullback", "catch")),
    move("outside_low_kick", "outside low kick", "kick", STANDING_POSITIONS, targets=frozenset({"leg"}),
         attack_skills=("low_kick_power", "low_kick_technique"), defense_skills=("kick_defence", "mobility"),
         preferred_styles=("Muay Thai", "Dutch Kickboxer"), energy=1.08, tags=("strike", "kick", "leg"),
         side="rear", range_band="kicking", defense_families=("check", "pullback", "catch")),
    move("body_round_kick", "round kick to the body", "kick", STANDING_POSITIONS, targets=frozenset({"body"}),
         attack_skills=("high_kick_technique", "low_kick_power", "flexibility"), defense_skills=("kick_defence", "guard_defence"),
         preferred_styles=("Kickboxer", "Muay Thai", "Sanda"), energy=1.1, tags=("strike", "kick", "body"),
         side="rear", range_band="kicking", defense_families=("block", "catch", "evade")),
    move("head_round_kick", "round kick to the head", "kick", STANDING_POSITIONS, targets=frozenset({"head"}),
         attack_skills=("high_kick_power", "high_kick_technique", "high_kick_speed"), defense_skills=("kick_defence", "head_movement"),
         preferred_styles=("Kickboxer", "Taekwondo", "Karate"), minimum_skill=58, energy=1.22,
         miss_risk=1.16, counter_risk=1.18, tags=("strike", "kick", "head", "power"),
         side="rear", range_band="kicking", defense_families=("block", "evade", "catch")),
    move("calf_kick", "rear calf kick", "kick", STANDING_POSITIONS, targets=frozenset({"leg"}),
         attack_skills=("low_kick_technique", "low_kick_speed", "creative_kicks"), defense_skills=("kick_defence", "mobility"),
         preferred_styles=("Kickboxer", "Muay Thai", "MMA Generalist"), minimum_skill=52, energy=1.06,
         tags=("strike", "kick", "leg"), side="rear", range_band="kicking",
         defense_families=("check", "pullback", "stance switch")),
    move("low_kick_counter", "check-return low kick", "kick", STANDING_POSITIONS, targets=frozenset({"leg"}),
         attack_skills=("counter_timing", "low_kick_speed", "low_kick_technique"), defense_skills=("kick_defence", "reflexes"),
         preferred_styles=("Muay Thai", "Dutch Kickboxer"), minimum_skill=57, counter_risk=0.82,
         tags=("strike", "kick", "leg", "counter"), side="rear", range_band="kicking",
         defense_families=("check", "pullback")),
    move("lead_teep", "lead teep", "kick", STANDING_POSITIONS, targets=frozenset({"body"}),
         attack_skills=("creative_kicks", "low_kick_technique", "footwork"), defense_skills=("kick_defence", "reflexes"),
         preferred_styles=("Muay Thai", "Sanda"), tags=("strike", "kick", "body", "intercept"),
         side="lead", range_band="long", defense_families=("parry", "catch", "sidestep")),
    move("side_kick", "lead side kick", "kick", STANDING_POSITIONS, targets=frozenset({"body"}),
         attack_skills=("creative_kicks", "high_kick_technique", "mobility"), defense_skills=("kick_defence", "footwork"),
         preferred_styles=("Karate", "Taekwondo", "Sanda"), minimum_skill=54, energy=1.08,
         tags=("strike", "kick", "body"), side="lead", range_band="long",
         defense_families=("sidestep", "catch", "pullback")),
    move("question_mark_kick", "question-mark kick", "kick", STANDING_POSITIONS, targets=frozenset({"head"}),
         attack_skills=("creative_kicks", "high_kick_technique", "feints"), defense_skills=("kick_defence", "head_movement"),
         preferred_styles=("Kickboxer", "Karate", "Taekwondo"), minimum_skill=64, energy=1.2, miss_risk=1.18, counter_risk=1.2,
         tags=("strike", "kick", "head", "creative"), side="rear", range_band="kicking",
         defense_families=("block", "evade", "catch")),
    move("wheel_kick", "wheel kick", "kick", STANDING_POSITIONS, targets=frozenset({"head"}),
         attack_skills=("creative_kicks", "high_kick_speed", "flexibility"), defense_skills=("kick_defence", "reflexes"),
         preferred_styles=("Taekwondo", "Karate"), minimum_skill=70, energy=1.34, miss_risk=1.32, counter_risk=1.36,
         tags=("strike", "kick", "head", "spinning", "high-risk"), side="rear", range_band="long",
         defense_families=("evade", "duck", "jam")),
    move("spinning_back_kick", "spinning back kick", "kick", STANDING_POSITIONS, targets=frozenset({"body"}),
         attack_skills=("creative_kicks", "low_kick_power", "mobility"), defense_skills=("kick_defence", "footwork"),
         preferred_styles=("Taekwondo", "Karate", "Sanda"), minimum_skill=66, energy=1.3, miss_risk=1.28, counter_risk=1.32,
         tags=("strike", "kick", "body", "spinning", "high-risk"), side="rear", range_band="long",
         defense_families=("sidestep", "jam", "catch")),
    move("switch_body_kick", "switch kick to the body", "kick", STANDING_POSITIONS, targets=frozenset({"body"}),
         attack_skills=("high_kick_technique", "low_kick_speed", "footwork"), defense_skills=("kick_defence", "guard_defence"),
         preferred_styles=("Muay Thai", "Kickboxer"), minimum_skill=57, energy=1.16,
         tags=("strike", "kick", "body", "stance-shift"), side="lead", range_band="kicking",
         defense_families=("block", "catch", "evade")),
    move("jab_low_kick", "jab to outside low kick", "kick", STANDING_POSITIONS, targets=frozenset({"leg"}),
         attack_skills=("combination_punching", "low_kick_technique", "hand_speed"), defense_skills=("guard_defence", "kick_defence"),
         preferred_styles=("Kickboxer", "Dutch Kickboxer"), minimum_skill=55, energy=1.18, counter_risk=1.12,
         tags=("strike", "kick", "leg", "mixed-combination"), side="rear", range_band="pocket-to-kicking",
         defense_families=("parry-check", "pullback", "catch")),
    move("cross_body_kick", "cross to body kick", "kick", STANDING_POSITIONS, targets=frozenset({"body"}),
         attack_skills=("combination_punching", "high_kick_technique", "punch_technique"), defense_skills=("head_movement", "kick_defence"),
         preferred_styles=("Kickboxer", "Muay Thai"), minimum_skill=58, energy=1.22, counter_risk=1.15,
         tags=("strike", "kick", "body", "mixed-combination"), side="rear", range_band="pocket-to-kicking",
         defense_families=("slip-block", "catch", "evade")),
    move("hook_low_kick", "lead hook to low kick", "kick", STANDING_POSITIONS, targets=frozenset({"leg"}),
         attack_skills=("combination_punching", "low_kick_power", "creative_punches"), defense_skills=("guard_defence", "kick_defence"),
         preferred_styles=("Dutch Kickboxer", "Muay Thai"), minimum_skill=59, energy=1.24, counter_risk=1.18,
         tags=("strike", "kick", "leg", "mixed-combination"), side="rear", range_band="pocket-to-kicking",
         defense_families=("block-check", "pullback", "catch")),
    move("punch_head_kick", "one-two to head kick", "kick", STANDING_POSITIONS, targets=frozenset({"head"}),
         attack_skills=("combination_punching", "high_kick_technique", "creative_kicks"), defense_skills=("guard_defence", "head_movement"),
         preferred_styles=("Kickboxer", "Taekwondo"), minimum_skill=65, energy=1.34, miss_risk=1.2, counter_risk=1.28,
         tags=("strike", "kick", "head", "mixed-combination", "high-risk"), side="rear", range_band="pocket-to-kicking",
         defense_families=("shell", "evade", "jam")),
    move("double_jab_low_kick", "double jab to outside low kick", "kick", STANDING_POSITIONS,
         targets=frozenset({"leg"}),
         attack_skills=("combination_punching", "low_kick_technique", "hand_speed"),
         defense_skills=("guard_defence", "kick_defence"),
         preferred_styles=("Dutch Kickboxer", "Kickboxer"), minimum_skill=58, energy=1.24,
         counter_risk=1.16, tags=("strike", "kick", "leg", "mixed-combination"), side="rear",
         range_band="pocket-to-kicking", defense_families=("parry-check", "pullback", "catch")),
    move("cross_hook_body_kick", "cross-lead hook to body kick", "kick", STANDING_POSITIONS,
         targets=frozenset({"body"}),
         attack_skills=("combination_punching", "high_kick_technique", "punch_power"),
         defense_skills=("guard_defence", "kick_defence"),
         preferred_styles=("Dutch Kickboxer", "Muay Thai"), minimum_skill=61, energy=1.28,
         counter_risk=1.2, tags=("strike", "kick", "body", "mixed-combination", "power"), side="rear",
         range_band="pocket-to-kicking", defense_families=("shell", "catch", "evade")),
    move("axe_kick", "axe kick", "kick", STANDING_POSITIONS, targets=frozenset({"head"}),
         attack_skills=("creative_kicks", "high_kick_technique", "flexibility"),
         defense_skills=("kick_defence", "reflexes"),
         preferred_styles=("Taekwondo", "Karate"), minimum_skill=68, energy=1.3, miss_risk=1.28,
         counter_risk=1.34, tags=("strike", "kick", "head", "power", "finisher"), side="rear",
         range_band="long", defense_families=("sidestep", "evade", "jam")),
    move("jumping_front_kick", "jumping front kick", "kick", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("creative_kicks", "high_kick_speed", "mobility"),
         defense_skills=("kick_defence", "footwork"),
         preferred_styles=("Karate", "Taekwondo", "Sanda"), minimum_skill=69, energy=1.34,
         miss_risk=1.32, counter_risk=1.38,
         tags=("strike", "kick", "head", "flying", "power", "finisher"), side="lead",
         range_band="long", defense_families=("sidestep", "evade", "jam")),
)
