"""passes catalogue; historical batches preserve selection order."""
from ..schema import move, ALL_POSITIONS, STANDING_POSITIONS, CLINCH_POSITIONS, GROUND_POSITIONS

BATCH_013 = (
    move("position_pass", "guard-passing transition", "advance_position", frozenset({"guard", "half guard"}),
         attack_skills=("transitions", "positional_ability", "top_control"), defense_skills=("guard_work", "bottom_control"),
         preferred_styles=("BJJ", "Submission Grappler"), follow_ups=("top_submission_chain", "back_take_transition"), tags=("ground", "transition")),
    move("knee_slice_pass", "knee-slice pass", "advance_position", frozenset({"guard", "half guard"}),
         attack_skills=("transitions", "top_control", "cage_wrestling"), defense_skills=("guard_work", "bottom_control"),
         preferred_styles=("BJJ", "Wrestler"), minimum_skill=54, energy=1.1,
         follow_ups=("arm_triangle", "mount_transition"), tags=("ground", "transition", "pass")),
    move("half_guard_pass", "half-guard pressure pass", "advance_position", frozenset({"half guard"}),
         attack_skills=("positional_ability", "top_control", "strength"), defense_skills=("bottom_control", "scrambles"),
         preferred_styles=("BJJ", "Wrestler", "Sambo"), minimum_skill=52,
         tags=("ground", "transition", "pass")),
    move("mount_transition", "side-control to mount transition", "advance_position", frozenset({"side control"}),
         attack_skills=("transitions", "positional_ability", "top_control"), defense_skills=("bottom_control", "scrambles"),
         preferred_styles=("BJJ", "Submission Grappler"), minimum_skill=56, energy=1.12,
         follow_ups=("arm_triangle",), tags=("ground", "transition", "mount")),
    move("back_take_transition", "back-take transition", "advance_position", frozenset({"half guard", "side control", "mount", "turtle"}),
         attack_skills=("back_control", "transitions", "scrambles"), defense_skills=("scrambles", "bottom_control"),
         preferred_styles=("BJJ", "Luta Livre", "Submission Grappler"), minimum_skill=58, energy=1.14,
         follow_ups=("rear_naked_choke",), tags=("ground", "transition", "back-take")),
    move("headquarters_pass", "headquarters passing sequence", "advance_position", frozenset({"guard"}),
         attack_skills=("transitions", "top_control", "footwork"), defense_skills=("guard_work", "bottom_control"),
         preferred_styles=("BJJ", "MMA Generalist", "Wrestler"), minimum_skill=54, energy=1.08,
         follow_ups=("half_guard_crossface_strikes",), tags=("ground", "transition", "pass", "guard")),
    move("body_lock_pass", "body-lock passing sequence", "advance_position", frozenset({"guard", "half guard"}),
         attack_skills=("top_control", "transitions", "strength"), defense_skills=("guard_work", "scrambles"),
         preferred_styles=("BJJ", "Wrestler", "Sambo"), minimum_skill=56, energy=1.12,
         follow_ups=("half_guard_crossface_strikes", "crucifix_elbows"), tags=("ground", "transition", "pass", "pressure")),
    move("underhook_half_guard_pass", "underhook half-guard pass", "advance_position", frozenset({"half guard"}),
         attack_skills=("top_control", "positional_ability", "strength"), defense_skills=("bottom_control", "scrambles"),
         preferred_styles=("Wrestler", "BJJ", "Catch Wrestler"), minimum_skill=55, energy=1.1,
         follow_ups=("crucifix_elbows",), tags=("ground", "transition", "pass", "underhook")),
    move("knee_on_belly_climb", "knee-on-belly climb", "advance_position", frozenset({"side control"}),
         attack_skills=("transitions", "positional_ability", "mobility"), defense_skills=("bottom_control", "scrambles"),
         preferred_styles=("BJJ", "Judo", "Submission Grappler"), minimum_skill=58, energy=1.12,
         follow_ups=("mounted_hammerfist_flurry", "back_control_short_punches"), tags=("ground", "transition", "mount", "pressure")),
    move("gift_wrap_transition", "gift-wrap transition", "advance_position", frozenset({"side control", "mount"}),
         attack_skills=("back_control", "transitions", "top_control"), defense_skills=("scrambles", "submission_defence_detail"),
         preferred_styles=("BJJ", "Catch Wrestler", "Submission Grappler"), minimum_skill=60, energy=1.14,
         follow_ups=("mounted_hammerfist_flurry", "rear_naked_choke"), tags=("ground", "transition", "back-take", "control")),
)
