"""Slice 5 boxing depth: ten identities beneath existing punch resolution."""
from ..presets import punch


POWER_PUNCH_DEVELOPMENT = (
    punch("rear_straight_body", "rear straight to the body", styles=("Well-Rounded", "Karate"),
          tags=("body", "level-change"), targets=frozenset({"body"}), side="rear",
          attack_skills=("body_punching", "punch_technique", "feints"),
          follow_ups=("single_jab", "double_leg_entry")),
    punch("lead_shovel_body", "lead shovel hook to the body", styles=("Boxer", "Dutch Kickboxer"),
          tags=("body", "power"), targets=frozenset({"body"}),
          attack_skills=("body_punching", "creative_punches", "punch_power"),
          follow_ups=("single_jab",)),
    punch("rear_shovel_body", "rear shovel hook to the body", styles=("Dutch Kickboxer", "Well-Rounded"),
          tags=("body", "power"), targets=frozenset({"body"}), side="rear",
          attack_skills=("body_punching", "punch_technique", "punch_power"),
          follow_ups=("collar_tie_entry",)),
    punch("lead_body_uppercut", "lead uppercut to the body", styles=("Boxer", "MMA Generalist"),
          tags=("body",), targets=frozenset({"body"}),
          attack_skills=("body_punching", "creative_punches", "hand_speed"),
          follow_ups=("single_jab", "body_lock_entry")),
    punch("rear_body_uppercut", "rear uppercut to the body", styles=("Sanda", "Well-Rounded"),
          tags=("body",), targets=frozenset({"body"}), side="rear",
          attack_skills=("body_punching", "punch_technique", "strength"),
          follow_ups=("collar_tie_entry",)),
    punch("step_around_body_hook", "step-around body hook", styles=("Boxer", "Dutch Kickboxer"),
          tags=("body", "footwork"), targets=frozenset({"body"}), minimum_skill=48,
          attack_skills=("body_punching", "footwork", "punch_technique"),
          follow_ups=("single_jab",)),
    punch("lead_straight", "lead straight", styles=("Karate", "Taekwondo", "Well-Rounded"),
          tags=("head", "intercept"), targets=frozenset({"head"}), range_band="boxing",
          attack_skills=("punch_technique", "hand_speed", "footwork"),
          follow_ups=("double_leg_entry", "collar_tie_entry")),
    punch("rear_check_hook", "rear check hook", styles=("Boxer", "Well-Rounded"),
          tags=("head", "counter"), targets=frozenset({"head"}), side="rear", minimum_skill=50,
          attack_skills=("counter_timing", "footwork", "punch_technique"),
          follow_ups=("single_jab",)),
    punch("lead_uppercut", "lead uppercut", styles=("Dutch Kickboxer", "MMA Generalist"),
          tags=("head",), targets=frozenset({"head"}),
          attack_skills=("punch_technique", "creative_punches", "hand_speed"),
          follow_ups=("collar_tie_entry",)),
    punch("looping_lead_hook", "looping lead hook", styles=("Sambo", "Freestyle Wrestler", "Well-Rounded"),
          tags=("head", "level-change"), targets=frozenset({"head"}),
          attack_skills=("punch_power", "feints", "punch_technique"),
          follow_ups=("double_leg_entry", "body_lock_entry")),
)
