"""punches catalogue; historical batches preserve selection order."""
from ..schema import move, ALL_POSITIONS, STANDING_POSITIONS, CLINCH_POSITIONS, GROUND_POSITIONS

BATCH_001 = (
    move("single_jab", "single jab", "jab", STANDING_POSITIONS,
         attack_skills=("punch_technique", "hand_speed"), defense_skills=("head_movement", "guard_defence"),
         preferred_styles=("Boxer", "Kickboxer"), follow_ups=("one_two", "jab_to_shot"), tags=("strike", "punch", "setup")),
    move("double_jab", "double jab", "jab", STANDING_POSITIONS,
         attack_skills=("punch_technique", "combination_punching", "conditioning"), defense_skills=("head_movement", "footwork"),
         preferred_styles=("Boxer", "MMA Generalist"), energy=1.08, follow_ups=("one_two", "double_jab_cross"), tags=("strike", "combination")),
    move("body_jab", "jab to the body", "jab", STANDING_POSITIONS, targets=frozenset({"body"}),
         attack_skills=("body_punching", "punch_technique", "feints"), defense_skills=("guard_defence", "reflexes"),
         preferred_styles=("Boxer",), counter_risk=1.08, tags=("strike", "punch", "body")),
    move("one_two", "one-two", "power_punch", STANDING_POSITIONS,
         attack_skills=("combination_punching", "punch_technique", "hand_speed"), defense_skills=("guard_defence", "head_movement"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), energy=1.08, follow_ups=("lead_hook_cross",), tags=("strike", "combination")),
    move("lead_hook_cross", "lead hook to rear cross", "power_punch", STANDING_POSITIONS,
         attack_skills=("combination_punching", "creative_punches", "punch_power"), defense_skills=("head_movement", "reflexes"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), minimum_skill=55, energy=1.16, counter_risk=1.12,
         tags=("strike", "combination", "power")),
    move("double_jab_cross", "double jab to rear cross", "power_punch", STANDING_POSITIONS,
         attack_skills=("combination_punching", "hand_speed", "punch_technique"), defense_skills=("guard_defence", "footwork"),
         preferred_styles=("Boxer", "Kickboxer"), minimum_skill=54, energy=1.2, counter_risk=1.14,
         tags=("strike", "combination")),
    move("cross_hook_cross", "cross-hook-cross", "power_punch", STANDING_POSITIONS,
         attack_skills=("combination_punching", "punch_power", "creative_punches"), defense_skills=("head_movement", "guard_defence"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), minimum_skill=58, energy=1.24, counter_risk=1.18,
         tags=("strike", "combination", "power")),
    move("body_head_change", "shovel hook to cross", "power_punch", STANDING_POSITIONS,
         attack_skills=("body_punching", "combination_punching", "punch_power"), defense_skills=("guard_defence", "head_movement"),
         preferred_styles=("Boxer", "Kickboxer"), minimum_skill=55, energy=1.16, counter_risk=1.12,
         tags=("strike", "combination", "body-head")),
    move("jab_cross_lead_hook", "jab-cross-lead hook", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("combination_punching", "punch_technique", "hand_speed"),
         defense_skills=("guard_defence", "head_movement"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), minimum_skill=56, energy=1.2, counter_risk=1.14,
         follow_ups=("rear_uppercut",), tags=("strike", "combination", "power", "head")),
    move("jab_uppercut_lead_hook", "jab-rear uppercut-lead hook", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("combination_punching", "creative_punches", "punch_power"),
         defense_skills=("head_movement", "guard_defence"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), minimum_skill=60, energy=1.24, counter_risk=1.18,
         tags=("strike", "combination", "power", "head")),
    move("double_jab_body_cross", "double body jab to cross upstairs", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("combination_punching", "body_punching", "punch_technique"),
         defense_skills=("guard_defence", "footwork"),
         preferred_styles=("Boxer", "MMA Generalist"), minimum_skill=56, energy=1.2, counter_risk=1.12,
         tags=("strike", "combination", "body-head", "head")),
    move("cross_body_hook_lead_hook", "cross-body hook-lead hook", "power_punch", STANDING_POSITIONS,
         attack_skills=("combination_punching", "body_punching", "creative_punches"),
         defense_skills=("guard_defence", "head_movement"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), minimum_skill=59, energy=1.24, counter_risk=1.18,
         tags=("strike", "combination", "body-head", "power")),
    move("stance_shift_cross_hook", "stance-shift cross to lead hook", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("combination_punching", "footwork", "punch_technique"),
         defense_skills=("head_movement", "reflexes"),
         preferred_styles=("Karate", "Boxer", "MMA Generalist"), minimum_skill=62, energy=1.2,
         counter_risk=1.16, tags=("strike", "combination", "stance-shift", "head")),
    move("boxing_pressure_flurry", "jab-cross-hook pressure flurry", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("combination_punching", "hand_speed", "conditioning"),
         defense_skills=("guard_defence", "composure"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), minimum_skill=68, energy=1.36, miss_risk=1.12,
         counter_risk=1.3, tags=("strike", "combination", "pressure", "head")),
    move("rear_uppercut", "rear uppercut", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("punch_power", "creative_punches", "hand_speed"),
         defense_skills=("head_movement", "guard_defence"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), minimum_skill=62, energy=1.18, miss_risk=1.08,
         counter_risk=1.16, tags=("strike", "punch", "power", "head", "finisher")),
    move("corkscrew_cross", "corkscrew cross", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("punch_power", "punch_technique", "counter_timing"),
         defense_skills=("guard_defence", "head_movement"),
         preferred_styles=("Boxer", "Karate"), minimum_skill=61, energy=1.16, miss_risk=1.06,
         counter_risk=1.14, tags=("strike", "punch", "power", "head", "finisher")),
    move("spinning_backfist", "spinning backfist", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("creative_punches", "hand_speed", "mobility"),
         defense_skills=("reflexes", "head_movement"),
         preferred_styles=("Karate", "Sanda", "MMA Generalist"), minimum_skill=66, energy=1.28,
         miss_risk=1.26, counter_risk=1.34,
         tags=("strike", "punch", "power", "spinning", "head", "finisher")),
    move("check_hook", "check hook", "power_punch", STANDING_POSITIONS,
         attack_skills=("counter_timing", "footwork", "punch_technique"), defense_skills=("head_movement", "guard_defence"),
         preferred_styles=("Boxer", "Karate"), minimum_skill=56, counter_risk=0.82,
         tags=("strike", "punch", "counter")),
    move("pull_counter", "pull counter", "power_punch", STANDING_POSITIONS,
         attack_skills=("counter_timing", "head_movement", "punch_power"), defense_skills=("reflexes", "guard_defence"),
         preferred_styles=("Boxer", "Kickboxer"), minimum_skill=58, energy=1.05, miss_risk=1.08, counter_risk=0.84,
         tags=("strike", "punch", "counter")),
    move("slip_cross", "slip and rear cross", "power_punch", STANDING_POSITIONS,
         attack_skills=("counter_timing", "head_movement", "hand_speed"), defense_skills=("reflexes", "guard_defence"),
         preferred_styles=("Boxer", "MMA Generalist"), minimum_skill=55, counter_risk=0.8,
         tags=("strike", "punch", "counter")),
    move("overhand", "rear overhand", "power_punch", STANDING_POSITIONS,
         attack_skills=("punch_power", "feints"), defense_skills=("head_movement", "footwork"),
         preferred_styles=("Wrestler", "Sambo", "Boxer"), energy=1.14, miss_risk=1.12, counter_risk=1.14,
         follow_ups=("double_leg_entry",), tags=("strike", "power", "level-change")),
)

BATCH_003 = (
    move("intercepting_knee", "intercepting knee", "power_punch", STANDING_POSITIONS,
         attack_skills=("knees", "counter_timing", "reflexes"), defense_skills=("footwork", "takedown_defence_detail"),
         preferred_styles=("Muay Thai", "Sanda"), minimum_skill=60, energy=1.18, counter_risk=1.08,
         tags=("strike", "knee", "counter")),
    move("jab_cross_rear_knee", "jab-cross to rear knee upstairs", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("combination_punching", "knees", "punch_technique"),
         defense_skills=("guard_defence", "clinch_defence"),
         preferred_styles=("Muay Thai", "Kickboxer"), minimum_skill=60, energy=1.26,
         counter_risk=1.2, tags=("strike", "combination", "knee", "head", "mixed-combination")),
    move("hook_elbow_knee", "lead hook-rear elbow-lead knee", "power_punch", STANDING_POSITIONS,
         attack_skills=("combination_punching", "elbows", "knees"),
         defense_skills=("guard_defence", "reflexes"),
         preferred_styles=("Muay Thai", "Sanda"), minimum_skill=64, energy=1.3, miss_risk=1.1,
         counter_risk=1.24, tags=("strike", "combination", "elbow", "knee", "power")),
    move("flying_knee", "flying knee", "power_punch", STANDING_POSITIONS,
         attack_skills=("knees", "creative_kicks", "strength"), defense_skills=("reflexes", "footwork"),
         preferred_styles=("Muay Thai", "Kickboxer"), minimum_skill=72, energy=1.42, miss_risk=1.4, counter_risk=1.45,
         tags=("strike", "knee", "flying", "high-risk")),
    move("switch_flying_knee", "switch flying knee", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}),
         attack_skills=("knees", "creative_kicks", "footwork"),
         defense_skills=("reflexes", "head_movement"),
         preferred_styles=("Muay Thai", "Kickboxer", "Sanda", "MMA Generalist"), minimum_skill=70, energy=1.38,
         miss_risk=1.34, counter_risk=1.4,
         tags=("strike", "knee", "flying", "power", "head", "finisher")),
    move("step_in_elbow", "step-in elbow", "power_punch", STANDING_POSITIONS,
         attack_skills=("elbows", "hand_speed", "footwork"), defense_skills=("guard_defence", "reflexes"),
         preferred_styles=("Muay Thai", "Sanda"), minimum_skill=60, energy=1.14, counter_risk=1.15,
         tags=("strike", "elbow")),
    move("spinning_elbow", "spinning elbow", "power_punch", STANDING_POSITIONS,
         attack_skills=("elbows", "creative_punches", "mobility"), defense_skills=("reflexes", "head_movement"),
         preferred_styles=("Muay Thai", "Sanda"), minimum_skill=70, energy=1.32, miss_risk=1.32, counter_risk=1.4,
         tags=("strike", "elbow", "spinning", "high-risk")),
)

BATCH_027 = (
    move("flicker_jab", "flicker jab", "jab", STANDING_POSITIONS,
         attack_skills=("hand_speed", "punch_technique", "footwork"), defense_skills=("head_movement", "reflexes"),
         preferred_styles=("Boxer", "Karate"), energy=0.94, follow_ups=("one_two",), tags=("strike", "punch", "setup")),
    move("power_jab", "stiff power jab", "jab", STANDING_POSITIONS,
         attack_skills=("punch_power", "punch_technique", "strength"), defense_skills=("guard_defence", "head_movement"),
         preferred_styles=("Boxer", "Dutch Kickboxer"), minimum_skill=54, energy=1.06, tags=("strike", "punch", "power")),
    move("up_jab", "up-jab from the low hand", "jab", STANDING_POSITIONS,
         attack_skills=("creative_punches", "punch_technique", "feints"), defense_skills=("head_movement", "guard_defence"),
         preferred_styles=("Karate", "MMA Generalist"), minimum_skill=55, counter_risk=1.06, tags=("strike", "punch", "setup")),
)
