"""style signatures catalogue; historical batches preserve selection order."""
from ..schema import move, ALL_POSITIONS, STANDING_POSITIONS, CLINCH_POSITIONS, GROUND_POSITIONS

BATCH_004 = (
    move("boxer_double_jab_pivot_cross_hook", "double jab-pivot-cross-hook", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("combination_punching", "footwork", "punch_technique"),
         defense_skills=("guard_defence", "head_movement"), preferred_styles=("Boxer",), minimum_skill=62,
         energy=1.24, counter_risk=1.16, tags=("strike", "punch", "combination", "style-combination", "head"),
         components=("jab", "jab", "pivot cross", "lead hook")),
    move("kickboxer_cross_hook_switch_kick", "cross-hook-switch body kick", "kick", STANDING_POSITIONS,
         targets=frozenset({"body"}), attack_skills=("combination_punching", "high_kick_technique", "footwork"),
         defense_skills=("guard_defence", "kick_defence"), preferred_styles=("Kickboxer",), minimum_skill=61,
         energy=1.28, counter_risk=1.18, tags=("strike", "kick", "mixed-combination", "style-combination", "body"),
         side="lead", range_band="pocket-to-kicking", defense_families=("shell", "catch", "evade"),
         components=("cross", "lead hook", "switch body kick")),
    move("dutch_high_guard_hook_cross_low_kick", "high-guard hook-cross-low-kick chain", "kick", STANDING_POSITIONS,
         targets=frozenset({"leg"}), attack_skills=("combination_punching", "low_kick_power", "conditioning"),
         defense_skills=("guard_defence", "kick_defence"), preferred_styles=("Dutch Kickboxer",), minimum_skill=62,
         energy=1.3, counter_risk=1.2,
         tags=("strike", "kick", "mixed-combination", "style-combination", "leg", "pressure"), side="rear",
         range_band="pocket-to-kicking", defense_families=("block-check", "pullback", "catch"),
         components=("high guard entry", "lead hook", "rear cross", "outside low kick")),
    move("muay_thai_teep_cross_elbow_knee", "teep-cross-elbow-knee chain", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("combination_punching", "elbows", "knees"),
         defense_skills=("guard_defence", "clinch_defence"), preferred_styles=("Muay Thai",), minimum_skill=64,
         energy=1.32, counter_risk=1.22,
         tags=("strike", "combination", "style-combination", "elbow", "knee", "head"),
         components=("lead teep", "rear cross", "lead elbow", "rear knee")),
    move("karate_blitz_cross_hook_exit", "blitz cross-hook angle exit", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("combination_punching", "footwork", "hand_speed"),
         defense_skills=("head_movement", "reflexes"), preferred_styles=("Karate",), minimum_skill=62,
         energy=1.2, miss_risk=1.08, counter_risk=1.1,
         tags=("strike", "punch", "combination", "style-combination", "stance-shift", "head"),
         components=("blitzing straight", "reverse cross", "lead hook", "angle exit")),
    move("taekwondo_side_back_round_chain", "side-kick-back-kick-round-kick chain", "kick", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("creative_kicks", "high_kick_speed", "flexibility"),
         defense_skills=("kick_defence", "reflexes"), preferred_styles=("Taekwondo",), minimum_skill=68,
         energy=1.36, miss_risk=1.2, counter_risk=1.28,
         tags=("strike", "kick", "combination", "style-combination", "spinning", "head"), side="rear",
         range_band="long", defense_families=("sidestep", "evade", "jam"),
         components=("lead side kick", "spinning back kick", "rear round kick to head")),
    move("sanda_side_kick_overhand_shot", "side-kick-overhand-to-shot chain", "shoot", STANDING_POSITIONS,
         attack_skills=("creative_kicks", "punch_technique", "takedown_setup"), defense_skills=("kick_defence", "sprawl"),
         preferred_styles=("Sanda",), minimum_skill=59, energy=1.24, follow_ups=("single_leg_finish",),
         tags=("strike", "wrestling", "entry", "mixed-combination", "style-combination"),
         components=("lead side kick", "rear overhand", "single-leg entry")),
    move("wrestler_jab_overhand_double", "jab-overhand-double-leg chain", "shoot", STANDING_POSITIONS,
         attack_skills=("takedown_setup", "takedowns", "punch_power"), defense_skills=("head_movement", "sprawl"),
         preferred_styles=("Wrestler",), minimum_skill=58, energy=1.22, follow_ups=("double_leg_finish",),
         tags=("strike", "wrestling", "entry", "mixed-combination", "style-combination"),
         components=("jab", "rear overhand", "double-leg entry")),
    move("freestyle_feint_reshot_chain", "level-change-feint to re-shot chain", "shoot", STANDING_POSITIONS,
         attack_skills=("takedown_speed", "chain_wrestling", "scrambles"),
         defense_skills=("sprawl", "takedown_defence_detail"), preferred_styles=("Freestyle Wrestler",),
         minimum_skill=60, energy=1.22, follow_ups=("single_leg_finish",),
         tags=("wrestling", "entry", "scramble", "style-combination"),
         components=("level-change feint", "outside single", "re-shot")),
    move("catch_snapdown_go_behind_chain", "collar-tie snapdown-go-behind chain", "clinch", STANDING_POSITIONS,
         attack_skills=("clinch_control", "chain_wrestling", "ride_control"), defense_skills=("clinch_defence", "scrambles"),
         preferred_styles=("Catch Wrestler",), minimum_skill=60, energy=1.18, follow_ups=("body_lock_trip",),
         tags=("clinch", "entry", "front-headlock", "style-combination"),
         components=("collar tie", "snapdown", "go-behind")),
    move("bjj_arm_drag_back_take_chain", "arm-drag-back-take-seatbelt chain", "advance_position",
         frozenset({"guard", "half guard", "side control", "mount", "turtle"}),
         attack_skills=("transitions", "back_control", "submission_attack"),
         defense_skills=("scrambles", "submission_defence_detail"), preferred_styles=("BJJ",), minimum_skill=61,
         energy=1.16, follow_ups=("back_take_transition", "rear_naked_choke"),
         tags=("ground", "transition", "back-take", "style-combination"),
         components=("arm drag", "back take", "seatbelt control")),
    move("luta_knee_line_leg_entanglement_chain", "knee-line entry to leg-entanglement chain", "sweep",
         frozenset({"guard", "half guard", "leg entanglement"}),
         attack_skills=("leg_locks", "scrambles", "bottom_control"),
         defense_skills=("submission_defence_detail", "guard_work"), preferred_styles=("Luta Livre",), minimum_skill=62,
         energy=1.18, follow_ups=("heel_hook",), tags=("ground", "leg-lock", "scramble", "style-combination"),
         components=("knee-line entry", "leg entanglement", "heel-hook threat")),
    move("sambo_overhand_body_lock_trip", "overhand-body-lock-outside-trip chain", "clinch", STANDING_POSITIONS,
         attack_skills=("punch_power", "clinch_control", "throws"), defense_skills=("head_movement", "clinch_defence"),
         preferred_styles=("Sambo",), minimum_skill=60, energy=1.22, follow_ups=("outside_trip",),
         tags=("strike", "clinch", "entry", "trip", "style-combination"),
         components=("rear overhand", "body lock", "outside trip")),
    move("judo_grip_foot_sweep_throw_chain", "grip-foot-sweep-hip-throw chain", "clinch", STANDING_POSITIONS,
         attack_skills=("clinch_control", "throws", "mobility"), defense_skills=("clinch_defence", "strength"),
         preferred_styles=("Judo",), minimum_skill=61, energy=1.2, follow_ups=("inside_trip",),
         tags=("clinch", "entry", "throw", "trip", "style-combination"),
         components=("collar grip", "foot sweep", "hip-turn throw")),
    move("grappler_jab_body_lock_mat_return", "jab-body-lock-mat-return chain", "clinch", STANDING_POSITIONS,
         attack_skills=("takedown_setup", "clinch_control", "positional_ability"),
         defense_skills=("guard_defence", "clinch_defence"), preferred_styles=("Grappler",), minimum_skill=58,
         energy=1.18, follow_ups=("body_lock_trip",),
         tags=("strike", "clinch", "entry", "control", "style-combination"),
         components=("jab", "body lock", "mat-return entry")),
    move("submission_grappler_pass_back_take_chain", "pass-back-take-choke chain", "advance_position",
         frozenset({"guard", "half guard", "side control", "mount", "turtle"}),
         attack_skills=("transitions", "back_control", "submission_attack"), defense_skills=("guard_work", "scrambles"),
         preferred_styles=("Submission Grappler",), minimum_skill=62, energy=1.18,
         follow_ups=("back_take_transition", "top_submission_chain"),
         tags=("ground", "transition", "back-take", "choke", "style-combination"),
         components=("guard pass", "back-take transition", "choke threat")),
    move("well_rounded_jab_low_kick_level_change", "jab-low-kick-level-change chain", "shoot", STANDING_POSITIONS,
         attack_skills=("combination_punching", "low_kick_technique", "takedown_setup"),
         defense_skills=("guard_defence", "kick_defence", "sprawl"), preferred_styles=("Well-Rounded",), minimum_skill=59,
         energy=1.22, follow_ups=("double_leg_finish",),
         tags=("strike", "low-kick", "wrestling", "entry", "mixed-combination", "style-combination"),
         components=("jab", "outside low kick", "level change")),
    move("mma_generalist_cross_kick_clinch_chain", "cross-body-kick-clinch chain", "kick", STANDING_POSITIONS,
         targets=frozenset({"body"}), attack_skills=("combination_punching", "high_kick_technique", "clinch_control"),
         defense_skills=("guard_defence", "kick_defence"), preferred_styles=("MMA Generalist",), minimum_skill=59,
         energy=1.24, counter_risk=1.16,
         tags=("strike", "kick", "mixed-combination", "style-combination", "body"), side="rear",
         range_band="pocket-to-kicking", defense_families=("slip-block", "catch", "evade"),
         components=("rear cross", "body kick", "collar-tie entry")),
    move("boxer_shift_step_cross_finisher", "shift-step rear cross", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("punch_power", "punch_technique", "footwork"),
         defense_skills=("head_movement", "guard_defence"), preferred_styles=("Boxer",), minimum_skill=65,
         energy=1.2, miss_risk=1.08, counter_risk=1.16,
         tags=("strike", "punch", "power", "head", "finisher", "style-finisher")),
    move("kickboxer_cross_high_kick_finisher", "rear cross to high kick", "kick", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("combination_punching", "high_kick_power", "high_kick_technique"),
         defense_skills=("guard_defence", "head_movement"), preferred_styles=("Kickboxer",), minimum_skill=66,
         energy=1.3, miss_risk=1.16, counter_risk=1.24,
         tags=("strike", "kick", "head", "power", "mixed-combination", "finisher", "style-finisher"),
         side="rear", range_band="pocket-to-kicking", defense_families=("shell", "evade", "jam"),
         components=("rear cross", "high kick")),
    move("dutch_high_guard_cross_hook_finisher", "high-guard cross-hook finish", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("combination_punching", "punch_power", "conditioning"),
         defense_skills=("guard_defence", "head_movement"), preferred_styles=("Dutch Kickboxer",), minimum_skill=66,
         energy=1.26, miss_risk=1.1, counter_risk=1.2,
         tags=("strike", "punch", "combination", "head", "power", "finisher", "style-finisher"),
         components=("high guard entry", "rear cross", "lead hook")),
    move("muay_thai_frame_elbow_finisher", "collar-frame slicing elbow", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("elbows", "thai_plum", "killer_instinct"),
         defense_skills=("guard_defence", "clinch_defence"), preferred_styles=("Muay Thai",), minimum_skill=66,
         energy=1.22, miss_risk=1.08, counter_risk=1.18,
         tags=("strike", "elbow", "power", "head", "finisher", "style-finisher")),
    move("karate_blitz_reverse_cross_finisher", "blitzing reverse cross", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("punch_power", "hand_speed", "footwork"),
         defense_skills=("head_movement", "reflexes"), preferred_styles=("Karate",), minimum_skill=65,
         energy=1.18, miss_risk=1.1, counter_risk=1.16,
         tags=("strike", "punch", "power", "head", "stance-shift", "finisher", "style-finisher")),
    move("taekwondo_spinning_hook_kick_finisher", "spinning hook kick", "kick", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("creative_kicks", "high_kick_power", "flexibility"),
         defense_skills=("kick_defence", "reflexes"), preferred_styles=("Taekwondo",), minimum_skill=70,
         energy=1.36, miss_risk=1.3, counter_risk=1.38,
         tags=("strike", "kick", "head", "power", "spinning", "finisher", "style-finisher"), side="rear",
         range_band="long", defense_families=("evade", "duck", "jam")),
    move("sanda_jumping_side_kick_finisher", "jumping side kick to the head", "kick", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("creative_kicks", "high_kick_speed", "mobility"),
         defense_skills=("kick_defence", "footwork"), preferred_styles=("Sanda",), minimum_skill=67,
         energy=1.32, miss_risk=1.24, counter_risk=1.3,
         tags=("strike", "kick", "head", "power", "flying", "finisher", "style-finisher"), side="lead",
         range_band="long", defense_families=("sidestep", "evade", "jam")),
    move("wrestler_wrist_ride_hammerfist_finisher", "wrist-ride hammerfist barrage", "ground_strikes",
         frozenset({"half guard", "side control", "turtle"}),
         attack_skills=("ground_striking", "ride_control", "punch_power"),
         defense_skills=("bottom_control", "get_ups"), preferred_styles=("Wrestler",), minimum_skill=62,
         energy=1.22, counter_risk=1.14, tags=("ground", "strike", "punch", "power", "style-finisher"),
         components=("wrist ride", "hammerfist", "short punch", "hammerfist")),
    move("freestyle_mat_return_ground_pound_finisher", "mat-return ground-and-pound barrage", "ground_strikes",
         frozenset({"half guard", "side control", "turtle"}),
         attack_skills=("ground_striking", "chain_wrestling", "conditioning"),
         defense_skills=("scrambles", "get_ups"), preferred_styles=("Freestyle Wrestler",), minimum_skill=62,
         energy=1.24, counter_risk=1.14, tags=("ground", "strike", "punch", "power", "style-finisher"),
         components=("mat return", "short punch", "hammerfist", "ride punch")),
    move("catch_cradle_neck_crank_finisher", "cradle neck crank", "submission",
         frozenset({"side control", "turtle"}),
         attack_skills=("submission_attack", "ride_control", "strength"),
         defense_skills=("submission_defence_detail", "scrambles"), preferred_styles=("Catch Wrestler",),
         minimum_skill=64, energy=1.16, counter_risk=1.14,
         tags=("ground", "submission", "joint", "style-finisher"), attack_path="cradle-and-neck isolation",
         failure_outcomes=("retain ride", "concede guard", "lose the cradle")),
    move("bjj_triangle_armbar_finisher", "triangle-to-armbar finish", "bottom_submission",
         frozenset({"guard"}), attack_skills=("submission_attack", "guard_work", "transitions"),
         defense_skills=("submission_defence_detail", "composure"), preferred_styles=("BJJ",), minimum_skill=65,
         energy=1.16, counter_risk=1.14,
         tags=("ground", "submission", "guard", "joint", "choke", "style-finisher"),
         attack_path="triangle lock chained to arm extension",
         failure_outcomes=("retain guard", "concede pass", "return neutral")),
    move("luta_outside_heel_hook_finisher", "outside heel hook finish", "bottom_submission",
         frozenset({"guard", "half guard"}), attack_skills=("leg_locks", "submission_attack", "scrambles"),
         defense_skills=("submission_defence_detail", "mobility"), preferred_styles=("Luta Livre",), minimum_skill=66,
         energy=1.18, counter_risk=1.18, tags=("ground", "submission", "leg-lock", "style-finisher"),
         attack_path="outside ashi heel exposure",
         failure_outcomes=("retain entanglement", "recover guard", "concede top")),
    move("sambo_rolling_kneebar_finisher", "rolling kneebar finish", "bottom_submission",
         frozenset({"guard", "half guard"}), attack_skills=("leg_locks", "submission_attack", "throws"),
         defense_skills=("submission_defence_detail", "mobility"), preferred_styles=("Sambo",), minimum_skill=65,
         energy=1.18, counter_risk=1.18, tags=("ground", "submission", "leg-lock", "style-finisher"),
         attack_path="rolling knee-line isolation",
         failure_outcomes=("retain entanglement", "recover guard", "concede top")),
    move("judo_kesa_armbar_finisher", "kesa-gatame armbar", "submission",
         frozenset({"side control"}), attack_skills=("submission_attack", "top_control", "throws"),
         defense_skills=("submission_defence_detail", "scrambles"), preferred_styles=("Judo",), minimum_skill=64,
         energy=1.14, counter_risk=1.12, tags=("ground", "submission", "joint", "style-finisher"),
         attack_path="scarf-hold arm isolation",
         failure_outcomes=("retain side control", "concede half guard", "lose the arm")),
    move("grappler_arm_triangle_finisher", "mounted arm-triangle finish", "submission",
         frozenset({"side control", "mount"}),
         attack_skills=("submission_attack", "top_control", "positional_ability"),
         defense_skills=("submission_defence_detail", "scrambles"), preferred_styles=("Grappler",), minimum_skill=64,
         energy=1.14, counter_risk=1.12, tags=("ground", "submission", "choke", "style-finisher"),
         attack_path="head-and-arm compression from top",
         failure_outcomes=("retain mount", "retain side control", "concede half guard")),
    move("submission_grappler_rear_triangle_finisher", "rear-triangle finish", "submission",
         frozenset({"back control", "mount"}),
         attack_skills=("submission_attack", "back_control", "transitions"),
         defense_skills=("submission_defence_detail", "scrambles"), preferred_styles=("Submission Grappler",),
         minimum_skill=66, energy=1.16, counter_risk=1.14,
         tags=("ground", "submission", "choke", "back-control", "style-finisher"),
         attack_path="back-control leg triangle",
         failure_outcomes=("retain back control", "concede guard", "lose the triangle")),
    move("well_rounded_cross_head_kick_finisher", "rear cross to head-kick finish", "kick", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("combination_punching", "high_kick_power", "adaptability"),
         defense_skills=("guard_defence", "head_movement"), preferred_styles=("Well-Rounded",), minimum_skill=66,
         energy=1.3, miss_risk=1.16, counter_risk=1.24,
         tags=("strike", "kick", "head", "power", "mixed-combination", "finisher", "style-finisher"),
         side="rear", range_band="pocket-to-kicking", defense_families=("shell", "evade", "jam"),
         components=("rear cross", "head kick")),
    move("mma_generalist_elbow_knee_finisher", "step-in elbow to rear knee", "power_punch", STANDING_POSITIONS,
         targets=frozenset({"head"}), attack_skills=("elbows", "knees", "combination_punching"),
         defense_skills=("guard_defence", "clinch_defence"), preferred_styles=("MMA Generalist",), minimum_skill=65,
         energy=1.28, miss_risk=1.12, counter_risk=1.22,
         tags=("strike", "elbow", "knee", "power", "head", "finisher", "style-finisher"),
         components=("step-in elbow", "rear knee")),
)
