"""submissions catalogue; historical batches preserve selection order."""
from ..schema import move, ALL_POSITIONS, STANDING_POSITIONS, CLINCH_POSITIONS, GROUND_POSITIONS

BATCH_018 = (
    move("top_submission_chain", "top-position submission chain", "submission", GROUND_POSITIONS,
         attack_skills=("submission_attack", "positional_ability", "back_control"), defense_skills=("submission_defence_detail", "composure"),
         preferred_styles=("BJJ", "Submission Grappler", "Sambo"), tags=("ground", "submission"),
         attack_path="position-to-isolation", failure_outcomes=("retain position", "lose position", "return neutral")),
    move("guard_submission_chain", "guard submission chain", "bottom_submission", frozenset({"guard", "half guard"}),
         attack_skills=("submission_attack", "guard_work", "leg_locks"), defense_skills=("submission_defence_detail", "top_control"),
         preferred_styles=("BJJ", "Luta Livre"), tags=("ground", "submission", "guard"),
         attack_path="guard isolation", failure_outcomes=("retain guard", "concede pass", "return neutral")),
    move("rear_naked_choke", "rear-naked choke", "submission", frozenset({"back control"}),
         attack_skills=("submission_attack", "back_control", "positional_ability"), defense_skills=("submission_defence_detail", "composure"),
         preferred_styles=("BJJ", "Submission Grappler", "Luta Livre"), minimum_skill=58,
         tags=("ground", "submission", "choke"), attack_path="back-control neck exposure",
         failure_outcomes=("retain back", "lose hooks", "return neutral")),
    move("arm_triangle", "arm-triangle choke", "submission", frozenset({"side control", "mount"}),
         attack_skills=("submission_attack", "top_control", "positional_ability"), defense_skills=("submission_defence_detail", "strength"),
         preferred_styles=("BJJ", "Wrestler", "Sambo"), minimum_skill=57,
         tags=("ground", "submission", "choke"), attack_path="head-and-arm isolation",
         failure_outcomes=("retain top", "recover guard", "return neutral")),
    move("top_armbar", "top-position armbar", "submission", frozenset({"mount", "side control"}),
         attack_skills=("submission_attack", "positional_ability", "transitions"), defense_skills=("submission_defence_detail", "scrambles"),
         preferred_styles=("BJJ", "Judo", "Submission Grappler"), minimum_skill=59, energy=1.14, counter_risk=1.16,
         tags=("ground", "submission", "joint"), attack_path="arm isolation",
         failure_outcomes=("retain top", "lose position", "concede reversal")),
    move("americana", "Americana", "submission", frozenset({"side control", "mount"}),
         attack_skills=("submission_attack", "top_control", "strength"), defense_skills=("submission_defence_detail", "mobility"),
         preferred_styles=("BJJ", "Wrestler", "Catch Wrestler"), minimum_skill=54,
         tags=("ground", "submission", "joint"), attack_path="bent-arm isolation",
         failure_outcomes=("retain top", "recover guard")),
    move("guard_armbar", "armbar from guard", "bottom_submission", frozenset({"guard"}),
         attack_skills=("submission_attack", "guard_work", "flexibility"), defense_skills=("submission_defence_detail", "top_control"),
         preferred_styles=("BJJ", "Judo"), minimum_skill=56, energy=1.1,
         tags=("ground", "submission", "guard", "joint"), attack_path="guard arm isolation",
         failure_outcomes=("retain guard", "concede pass", "return neutral")),
    move("triangle_choke", "triangle choke", "bottom_submission", frozenset({"guard"}),
         attack_skills=("submission_attack", "guard_work", "flexibility"), defense_skills=("submission_defence_detail", "strength"),
         preferred_styles=("BJJ", "Submission Grappler"), minimum_skill=58, energy=1.12,
         tags=("ground", "submission", "guard", "choke"), attack_path="guard head-and-arm trap",
         failure_outcomes=("retain guard", "concede pass", "return neutral")),
    move("kimura_guard", "kimura from guard", "bottom_submission", frozenset({"guard", "half guard"}),
         attack_skills=("submission_attack", "guard_work", "positional_ability"), defense_skills=("submission_defence_detail", "strength"),
         preferred_styles=("BJJ", "Luta Livre", "Catch Wrestler"), minimum_skill=55,
         tags=("ground", "submission", "guard", "joint"), attack_path="figure-four shoulder isolation",
         failure_outcomes=("retain guard", "sweep", "concede pass")),
    move("omoplata", "omoplata", "bottom_submission", frozenset({"guard"}),
         attack_skills=("submission_attack", "guard_work", "flexibility"), defense_skills=("submission_defence_detail", "scrambles"),
         preferred_styles=("BJJ",), minimum_skill=63, energy=1.16, counter_risk=1.12,
         tags=("ground", "submission", "guard", "joint"), attack_path="leg-over shoulder isolation",
         failure_outcomes=("retain guard", "sweep", "concede pass")),
)

BATCH_020 = (
    move("straight_ankle_lock", "straight ankle lock", "leg_attack", frozenset({"guard", "half guard", "leg entanglement"}),
         attack_skills=("leg_locks", "submission_attack", "transitions"), defense_skills=("submission_defence_detail", "scrambles"),
         preferred_styles=("BJJ", "Sambo", "Luta Livre"), minimum_skill=54,
         tags=("ground", "submission", "leg-lock"), attack_path="straight-leg entanglement",
         failure_outcomes=("retain entanglement", "recover guard", "return neutral")),
    move("kneebar", "kneebar", "leg_attack", frozenset({"guard", "half guard", "leg entanglement"}),
         attack_skills=("leg_locks", "submission_attack", "positional_ability"), defense_skills=("submission_defence_detail", "mobility"),
         preferred_styles=("Sambo", "BJJ", "Luta Livre"), minimum_skill=59, energy=1.12,
         tags=("ground", "submission", "leg-lock"), attack_path="knee-line isolation",
         failure_outcomes=("retain entanglement", "concede top", "return neutral")),
)
