"""takedowns catalogue; historical batches preserve selection order."""
from ..schema import move, ALL_POSITIONS, STANDING_POSITIONS, CLINCH_POSITIONS, GROUND_POSITIONS

BATCH_005 = (
    move("double_leg_entry", "double-leg entry", "shoot", STANDING_POSITIONS,
         attack_skills=("takedowns", "takedown_setup", "takedown_speed"), defense_skills=("sprawl", "takedown_defence_detail"),
         preferred_styles=("Wrestler", "Freestyle Wrestler"), energy=1.15, follow_ups=("double_leg_finish",), tags=("wrestling", "entry")),
    move("single_leg_entry", "single-leg entry", "shoot", STANDING_POSITIONS,
         attack_skills=("takedowns", "chain_wrestling", "takedown_speed"), defense_skills=("sprawl", "scrambles"),
         preferred_styles=("Wrestler", "Sanda", "Sambo"), follow_ups=("single_leg_finish",), tags=("wrestling", "entry")),
)

BATCH_007 = (
    move("double_leg_finish", "double-leg finish", "takedown", CLINCH_POSITIONS,
         attack_skills=("takedowns", "chain_wrestling", "strength"), defense_skills=("takedown_defence_detail", "sprawl"),
         preferred_styles=("Wrestler", "Freestyle Wrestler"), energy=1.18, tags=("wrestling", "takedown"),
         defense_families=("sprawl", "whizzer", "fence post"), entry_family="double leg",
         finish_positions=("guard", "half guard")),
    move("single_leg_finish", "single-leg finish", "takedown", CLINCH_POSITIONS,
         attack_skills=("takedowns", "chain_wrestling", "cage_wrestling"), defense_skills=("takedown_defence_detail", "scrambles"),
         preferred_styles=("Wrestler", "Sanda"), tags=("wrestling", "takedown"),
         defense_families=("whizzer", "limp leg", "balance"), entry_family="single leg",
         finish_positions=("guard", "half guard")),
    move("body_lock_trip", "body-lock trip", "takedown", CLINCH_POSITIONS,
         attack_skills=("clinch_takedowns", "throws", "clinch_control"), defense_skills=("clinch_defence", "mobility"),
         preferred_styles=("Judo", "Sambo", "Sanda"), tags=("clinch", "takedown", "trip"),
         defense_families=("base", "underhook", "hip turn"), entry_family="body lock",
         finish_positions=("guard", "half guard")),
    move("inside_trip", "inside trip", "takedown", CLINCH_POSITIONS,
         attack_skills=("throws", "clinch_takedowns", "clinch_control"), defense_skills=("clinch_defence", "mobility"),
         preferred_styles=("Judo", "Sambo", "Muay Thai"), minimum_skill=54, energy=1.08,
         tags=("clinch", "takedown", "trip"), defense_families=("wide base", "hip turn", "whizzer"),
         entry_family="over-under", finish_positions=("guard", "half guard")),
    move("outside_trip", "outside trip", "takedown", CLINCH_POSITIONS,
         attack_skills=("clinch_takedowns", "throws", "clinch_control"), defense_skills=("clinch_defence", "strength"),
         preferred_styles=("Judo", "Sambo"), minimum_skill=56, energy=1.12,
         tags=("clinch", "takedown", "trip"), defense_families=("hop", "underhook", "hip turn"),
         entry_family="over-under", finish_positions=("guard", "half guard")),
    move("high_crotch_finish", "high-crotch finish", "takedown", CLINCH_POSITIONS,
         attack_skills=("takedowns", "chain_wrestling", "slams"), defense_skills=("takedown_defence_detail", "scrambles"),
         preferred_styles=("Freestyle Wrestler", "Wrestler"), minimum_skill=58, energy=1.2,
         tags=("wrestling", "takedown", "chain"), defense_families=("whizzer", "hip pressure", "limp leg"),
         entry_family="high crotch", finish_positions=("guard", "half guard")),
    move("knee_tap", "knee-tap takedown", "takedown", CLINCH_POSITIONS,
         attack_skills=("clinch_takedowns", "chain_wrestling", "cage_wrestling"), defense_skills=("clinch_defence", "sprawl"),
         preferred_styles=("Wrestler", "Freestyle Wrestler"), minimum_skill=55, energy=1.12,
         tags=("wrestling", "takedown", "chain"), defense_families=("underhook", "sprawl", "fence post"),
         entry_family="underhook", finish_positions=("guard", "half guard")),
    move("hip_toss", "hip toss", "takedown", CLINCH_POSITIONS,
         attack_skills=("throws", "clinch_takedowns", "strength"), defense_skills=("clinch_defence", "mobility"),
         preferred_styles=("Judo", "Sambo"), minimum_skill=60, energy=1.18, counter_risk=1.16,
         tags=("clinch", "takedown", "throw"), defense_families=("hip block", "back step", "underhook"),
         entry_family="over-under", finish_positions=("side control", "guard")),
    move("lateral_drop", "lateral drop", "takedown", CLINCH_POSITIONS,
         attack_skills=("throws", "clinch_control", "strength"), defense_skills=("clinch_defence", "scrambles"),
         preferred_styles=("Catch Wrestler", "Sambo", "Judo"), minimum_skill=66, energy=1.3, miss_risk=1.22, counter_risk=1.3,
         tags=("clinch", "takedown", "throw", "high-risk"), defense_families=("base", "hip turn", "back take"),
         entry_family="over-under", finish_positions=("side control", "guard")),
)

BATCH_010 = (
    move("ankle_pick_entry", "ankle-pick entry", "shoot", STANDING_POSITIONS,
         attack_skills=("takedown_setup", "takedown_speed", "creative_punches"), defense_skills=("sprawl", "mobility"),
         preferred_styles=("Wrestler", "Freestyle Wrestler", "Judo"), minimum_skill=58, energy=1.08,
         follow_ups=("single_leg_finish",), tags=("wrestling", "entry")),
    move("reactive_shot", "reactive double-leg shot", "shoot", STANDING_POSITIONS,
         attack_skills=("counter_timing", "takedown_speed", "takedowns"), defense_skills=("sprawl", "reflexes"),
         preferred_styles=("Wrestler", "Freestyle Wrestler"), minimum_skill=57, energy=1.12,
         follow_ups=("double_leg_finish",), tags=("wrestling", "entry", "counter")),
    move("jab_to_shot", "jab to double-leg entry", "shoot", STANDING_POSITIONS,
         attack_skills=("takedown_setup", "punch_technique", "takedown_speed"), defense_skills=("guard_defence", "sprawl"),
         preferred_styles=("Wrestler", "MMA Generalist"), minimum_skill=54, energy=1.14,
         follow_ups=("double_leg_finish",), tags=("wrestling", "entry", "mixed-combination")),
    move("overhand_to_double", "overhand to double-leg entry", "shoot", STANDING_POSITIONS,
         attack_skills=("takedown_setup", "punch_power", "chain_wrestling"), defense_skills=("head_movement", "sprawl"),
         preferred_styles=("Wrestler", "Sambo"), minimum_skill=58, energy=1.2, counter_risk=1.15,
         follow_ups=("double_leg_finish",), tags=("wrestling", "entry", "mixed-combination")),
)
