"""Phase 29: positional submission identities beneath the existing top resolver."""
from ..presets import submission

_FAILURES = ("retain top", "recover guard", "return neutral")

PHASE_29 = (
    submission("half_guard_kimura", "kimura from top half guard", positions={"half guard"},
               attack_path="figure-four shoulder isolation", failure_outcomes=_FAILURES,
               styles=("Catch Wrestler", "Sambo"), tags=("joint", "half-guard"), minimum_skill=53,
               attack_skills=("submission_attack", "top_control", "strength"),
               follow_ups=("arm_triangle",)),
    submission("half_guard_darce", "D'Arce from top half guard", positions={"half guard"},
               attack_path="arm-in neck thread", failure_outcomes=_FAILURES,
               styles=("BJJ", "Luta Livre"), tags=("choke", "half-guard"), minimum_skill=56,
               attack_skills=("submission_attack", "positional_ability", "top_control"),
               follow_ups=("arm_triangle",)),
    submission("half_guard_brabo", "Brabo choke from half guard", positions={"half guard"},
               attack_path="head-and-arm isolation", failure_outcomes=_FAILURES,
               styles=("BJJ", "Submission Grappler"), tags=("choke", "half-guard"), minimum_skill=54,
               attack_skills=("submission_attack", "positional_ability", "strength"),
               follow_ups=("arm_triangle",)),
    submission("half_guard_von_flue", "Von Flue choke from half guard", positions={"half guard"},
               attack_path="head-and-arm compression from top", failure_outcomes=_FAILURES,
               styles=("Catch Wrestler", "Wrestler"), tags=("choke", "pressure"), minimum_skill=53,
               attack_skills=("submission_attack", "top_control", "ride_control"),
               follow_ups=("chest_to_chest_pin",)),
    submission("half_guard_americana", "Americana from half guard", positions={"half guard"},
               attack_path="bent-arm isolation", failure_outcomes=_FAILURES,
               styles=("BJJ", "Judo"), tags=("joint", "half-guard"), minimum_skill=49,
               attack_skills=("submission_attack", "top_control", "strength"),
               follow_ups=("top_armbar",)),
    submission("half_guard_arm_triangle", "arm-triangle from half guard", positions={"half guard"},
               attack_path="head-and-arm compression from top", failure_outcomes=_FAILURES,
               styles=("Wrestler", "Submission Grappler"), tags=("choke", "pressure"), minimum_skill=51,
               attack_skills=("submission_attack", "top_control", "positional_ability"),
               follow_ups=("arm_triangle",)),
    submission("half_guard_shoulder_choke", "shoulder-pressure choke from half guard", positions={"half guard"},
               attack_path="head-and-arm compression from top", failure_outcomes=_FAILURES,
               styles=("Grappler", "Sambo"), tags=("choke", "pressure"), minimum_skill=50,
               attack_skills=("submission_attack", "top_control", "strength"),
               follow_ups=("chest_to_chest_pin",)),
    submission("guard_top_guillotine", "guillotine from top guard", positions={"guard"},
               attack_path="front-headlock neck wrap", failure_outcomes=_FAILURES,
               styles=("BJJ", "Luta Livre"), tags=("choke", "guard"), minimum_skill=52,
               attack_skills=("submission_attack", "positional_ability", "top_control"),
               follow_ups=("chest_to_chest_pin",)),
    submission("guard_top_head_arm", "head-and-arm choke from top guard", positions={"guard", "half guard"},
               attack_path="head-and-arm compression from top", failure_outcomes=_FAILURES,
               styles=("Judo", "Sambo"), tags=("choke", "guard"), minimum_skill=49,
               attack_skills=("submission_attack", "strength", "top_control"),
               follow_ups=("arm_triangle",)),
    submission("guard_can_opener", "can-opener neck crank", positions={"guard"},
               attack_path="guard isolation", failure_outcomes=_FAILURES,
               styles=("Catch Wrestler",), tags=("joint", "guard"), minimum_skill=52,
               attack_skills=("submission_attack", "strength", "top_control"),
               follow_ups=("chest_to_chest_pin",)),
    submission("guard_top_ankle_lock", "straight ankle lock from top guard", positions={"guard"},
               attack_path="straight-leg entanglement", failure_outcomes=_FAILURES,
               styles=("Sambo", "Luta Livre"), tags=("leg-lock", "guard"), minimum_skill=53,
               attack_skills=("submission_attack", "leg_locks", "transitions"),
               follow_ups=("guard_submission_chain",)),
    submission("guard_top_wrist_lock", "wrist lock from top guard", positions={"guard"},
               attack_path="arm isolation", failure_outcomes=_FAILURES,
               styles=("Judo", "Catch Wrestler"), tags=("joint", "guard"), minimum_skill=50,
               attack_skills=("submission_attack", "positional_ability", "top_control"),
               follow_ups=("top_submission_chain",)),
    submission("guard_top_ezekiel", "no-gi Ezekiel choke from top guard", positions={"guard"},
               attack_path="guard head-and-arm trap", failure_outcomes=_FAILURES,
               styles=("BJJ", "Judo"), tags=("choke", "guard"), minimum_skill=54,
               attack_skills=("submission_attack", "top_control", "positional_ability"),
               follow_ups=("top_submission_chain",)),
    submission("guard_top_punch_choke", "punch choke from top guard", positions={"guard"},
               attack_path="guard isolation", failure_outcomes=_FAILURES,
               styles=("Catch Wrestler", "Grappler"), tags=("choke", "pressure"), minimum_skill=48,
               attack_skills=("submission_attack", "strength", "top_control"),
               follow_ups=("chest_to_chest_pin",)),
    submission("north_south_choke", "north-south choke", positions={"side control"},
               attack_path="head-and-arm isolation", failure_outcomes=_FAILURES,
               styles=("Catch Wrestler", "BJJ"), tags=("choke", "pressure"), minimum_skill=53,
               attack_skills=("submission_attack", "top_control", "positional_ability"),
               follow_ups=("chest_to_chest_pin",)),
    submission("scarf_hold_straight_armbar", "straight armbar from scarf hold", positions={"side control"},
               attack_path="scarf-hold arm isolation", failure_outcomes=_FAILURES,
               styles=("Judo", "Sambo"), tags=("joint", "control"), minimum_skill=51,
               attack_skills=("submission_attack", "top_control", "strength"),
               follow_ups=("americana",)),
)
